### ISSUE TITLE
[BUG] `pueue follow` should not use 100% of a CPU

### ISSUE THREAD

**Issue by bheisler** [Nukesor/pueue#106]
I'm experimenting with pueue to manage some long-running tasks, and I noticed that when I ran `pueue follow` to see the output of a command, it was taking up a whole CPU. This task was not producing very much output at all, so this suggests that `pueue follow` is busy-waiting.

**To Reproduce**
1. Submit a long-running task to the daemon
2. Run `pueue follow $task_id`
3. In another terminal, run `top` and see that `pueue follow` is using 100% of a CPU

**Expected behavior**
`pueue follow` should not be busy-waiting, and should use a very small amount of CPU time, especially when there is no output for it to show.

**Additional context**
- Linux
- Pueue client 0.6.1

**Comment by Nukesor** [comment]
Damn. That's a big one.

I'll look into it as soon as I find some time.
