### ISSUE TITLE
[BUG] `pueue log` should not print escape codes if stdout is not a tty

### ISSUE THREAD

**Issue by bheisler** [Nukesor/pueue#107]
**Describe the bug**
`pueue log` prints color escape codes regardless of whether stdout is a terminal or a file/pipe.

**To Reproduce**
1. Run `pueue log $some_task_id | less`
2. See the escape codes in less

**Expected behavior**
Pueue should use something like the [atty crate](https://crates.io/crates/atty) to detect if stdout is a terminal and avoid printing the escape codes if it is.

**Additional context**
- Linux
- Pueue version 0.6.1

**Comment by Nukesor** [comment]
Good point. Thanks for the bug report :)

I'll look into it.

**Comment by Nukesor** [comment]
Fixed in #e566111fe6e8d9903fbf1927a7167c4a667ec436
