### ISSUE TITLE
[Request] Truncate very long commands.

### ISSUE THREAD

**Issue by she3o** [Nukesor/pueue#123]
**Describe the bug**
Commands are printed with `$ pueue status` as is, even if commands are too long. When commands are too long (e.g. containing several URIs, filenames, etc) the output will not be pretty or useful.

**To Reproduce**
1. Add the task 
```
# aria2c is a CLI bittorrent client among other things
# aria2c 'magnet URI' 'magnet URI' 'webpage URL'
pueue add -- 'aria2c "magnet:?xt=urn:btih:1c28ff99b2f7a84d57d38b48211bfedf513915f5&tr=http%3A%2F%2Facademictorrents.com%2Fannounce.php&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969" "magnet:?xt=urn:btih:325fc900c2c7bb7a0cfcfd45851a65c2f5b5391d&tr=http%3A%2F%2Facademictorrents.com%2Fannounce.php&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969" "magnet:?xt=urn:btih:136ffddd0959108becb2b3a86630bec049fcb0ff&tr=http%3A%2F%2Facademictorrents.com%2Fannounce.php&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969" "magnet:?xt=urn:btih:6be335f0d038fd4ed4422dd318705e0843059718&tr=http%3A%2F%2Facademictorrents.com%2Fannounce.php&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969"'
```
2. run `$ pueue status`

**Expected behavior**
1. a good behaviour for my case: grap a display name or at least an infohash from from the magnet link. the displayed command would look like `aria2c "dn:Hubble+telescope_dataset" "dn:covid+dataset"` or `aria2c "btih:6be335f0d038fd4ed4422dd318705e0843059718" "btih:136ffddd0959108becb2b3a86630bec049fcb0ff"`

2. Generally **good** behaviours for any cases:
- truncate everything longer than some length (e.g. 120 bytes) and replace with three dots. Command becomes `aria2c "magnet:?xt=urn:btih:1c28ff99b2f7a84d57d38b48211bfedf513915f5&tr=http%3A%2F...`.
- truncate all filenames and URIs from command (i.e. `aria2c "..." "..." "..."`).
- only print command name (i.e. `find . -name *.mp4 -print0 | xargs -0 -I% ffmpeg -i % -vcodec libx265 -crf 24 -y %` becomes `find ... | xargs ... ffmpeg ...`) 
3. Generally **ok** behaviour:
- optionally print the output in non-tabular format.

**Screenshots**
The output is not pretty:
![Blurred-out-because-it-contains-private-info](https://user-images.githubusercontent.com/26515372/97146572-becfd680-1770-11eb-86ac-c3e4f2d44f85.png)
The output is not pretty or useful:
![20201026_10h15m21s_grim](https://user-images.githubusercontent.com/26515372/97149590-a0b8a500-1775-11eb-9183-44e55bf22b4a.png)
This also happens with normal-sized commands when terminal width is small

![20201026_11h38m53s_grim](https://user-images.githubusercontent.com/26515372/97157489-d44cfc80-1780-11eb-819b-c8edb804553c.png)

**Additional context**
- Operating System: Linux 5.9.1
- Pueue version: 0.7.2

**Also Thank you for this, I used to have three tmux windows open just for running and pending commands**

**Comment by Nukesor** [comment]
Wow :D 
That's a super long link chain.

Well, what would be the best solution for this? I guess some people will always want to see the full command, no matter what.
So adding a option to truncate long commands is probably the best solution.

The hardest problem is probably to decide when to truncate...
If there's a lot of screen space one will naturally want to see much more content.
A good solution might be to limit the vertical space per command to a fix amount of rows. Something like "Always truncate the command after 5 rows of content".

This requires a new feature in the `comfy-table` upstream crate, though.

**Comment by Nukesor** [comment]
I wouldn't consider this a bug, though. Everything works as expected and truncating output is definitely a (missing) feature.

**Comment by Nukesor** [comment]
@she3o 
How about [this](https://github.com/Nukesor/comfy-table/pull/13/files#diff-db056e1ba3739a72e463234d67d7220240e266b84b91399fdf40de5d59596996R97)?

**Comment by Nukesor** [comment]
Your other two alternatives require a lot of information about the command structure, which we don't have.
Pueue doesn't know antyhing about the actual commands. The internal representation of them is a simple string.

Another problem would be, that we would have to know, if the content should be truncated or not in Pueue, even though we can only know this in the middle of the arrangement process in comfy-table.

I think that a simple truncate after a certain length is the most pragmatic and simple solution.

**Comment by she3o** [comment]
> How about something like [this](https://github.com/Nukesor/comfy-table/pull/13/files#diff-db056e1ba3739a72e463234d67d7220240e266b84b91399fdf40de5d59596996R97)?

>
```
+----------------+--------+-------+
| Header1        | Header | Head  |
|                | 2      |       |
+=================================+
| This is a very | This   | smol  |
| long line with | is ano |       |
| a lot of text  | therve |       |
|                | ryl... |       |
|----------------+--------+-------|
| Now let's      | This   | smol  |
| add a really   | is ano |       |
| long line in   | ther   |       |
| the middle ... | text   |       |
+----------------+--------+-------+"

```

Yes, that's the expected behaviour!

> I think that a simple truncate after a certain length is the most pragmatic and simple solution.

I agree. I don't know plenty of Rust but maybe parsing commands like I suggested (`find ...| xargs ...` or `aria2c '...' '...'`) should be the job of at least one other dependency, and will probably not end up working 100% perfectly. unless you can always trust it's output, This solution (truncating after fixed number of rows) solves the issue, is elegant and always predictable.
