### ISSUE TITLE
Allow Scheduling a command for a specific time

### ISSUE THREAD

**Issue by soruh** [Nukesor/pueue#129]
**Is your feature request related to a problem? Please describe.**
I have not found a way to schedule a task to run (in parallel) at a specific time.

**Describe the solution you'd like**
- add `pueue schedule [time] [command]` which schedules `[command]` to run at `[time]`
- add `Scheduled` state for Tasks and display scheduled tasks as such in `pueue status`

**Describe alternatives you've considered**
It is possible to call `pueue add sleep [time until command should be run]` before adding
the actual command but that blocks everything until the command is run.

**Open questions**
[ ] How should the scheduled time be displayed in `pueue status` (does it make sense to display it in the `Start` field)?
[ ] Is this something `pueue` should do?

**Comment by Nukesor** [comment]
There's a `--delay` flag on the `add` and `enqueue` subcommand.
Do you think you can use this?

Check the `enqueue -h` page

```
    The --delay argument must be either a number of seconds or a "date expression" similar to GNU `date -d` with some
extensions. It does not attempt to parse all natural language, but is incredibly flexible. Here are some supported
examples.

    2020-04-01T18:30:00   // RFC 3339 timestamp
    2020-4-1 18:2:30      // Optional leading zeros
    2020-4-1 5:30pm       // Informal am/pm time
    2020-4-1 5pm          // Optional minutes and seconds
    April 1 2020 18:30:00 // English months
    1 Apr 8:30pm          // Implies current year
    4/1                   // American form date
    wednesday 10:30pm     // The closest wednesday in the future at 22:30
    wednesday             // The closest wednesday in the future
    4 months              // 4 months from today at 00:00:00
    1 week                // 1 week at the current time
    1days                 // 1 day from today at the current time
    1d 03:00              // The closest 3:00 after 1 day (24 hours)
    3h                    // 3 hours from now
    3600s                 // 3600 seconds from now
```

**Comment by soruh** [comment]
Ah I'm sorry, I seem to have missed that completely. Thank you.

**Comment by Nukesor** [comment]
No problem :)
You aren't the first that missed a feature :D. I probably have to write better docs :sweat_smile:
