### ISSUE TITLE
Replace `cron` with calendar feature

### ISSUE THREAD

**Issue by Piping** [Nukesor/pueue#131]
Cron is well known task scheduler that repeatedly execute commands on defined time.

But it is always a pain to manage cron tasks (e.g. check ruining status,  collect error log, get proper notification, get a list of task being executed, etc). So many features has to be manually implemented by users etc. And I see pueue has a lot nice support for queued commands.

I want to add a new sub command `calendar` to `pueue` so that it can execute commands periodically. 

@Nukesor  What do you think? Is it gonna be a good feature accept by the project?

**Comment by Nukesor** [comment]
Hm.

Pueue is designed to be more of an commandline helper.
Rebuilding `cron` or `systemd-timer` seems a little out of scope, to be honest.

I think it would be better to write another stand-alone tool for recurring system/user jobs.

IMO, Pueue should stay a on-demand command scheduler. Let's keep the scope small :)

It shouldn't be too hard to do a fork from Pueue and built the another cool tool with the existing code :D.

**Comment by Piping** [comment]
@Nukesor understood.
