### ISSUE TITLE
Sleep 60 Cannot be properly paused

### ISSUE THREAD

**Issue by Piping** [Nukesor/pueue#132]
I have ran `pueue add -- sleep 60`, `pueue pasue` , `pueue start`, `pueue status` in sequence. 

I found that my sleep task was ended earlier with success return.

```bash

user@ryzen:~$ pueue status
Default queue (1 parallel): running
────────────────────────────────────────────────────────────────────────────────
 Index   Status    Exitcode   Command    Path                     Start   End
════════════════════════════════════════════════════════════════════════════════
 0       Success   0          sleep 60   /home/robin/code/pueue   11:17   11:18
────────────────────────────────────────────────────────────────────────────────
 1       Success   0          sleep 60   /home/robin/code/pueue   11:19   11:20
────────────────────────────────────────────────────────────────────────────────

```

The time has shown the sleep did not execute to its full length.

**Comment by Nukesor** [comment]
First of all, do you use MacOs or linux? Child process signal handling is not fully working for MacOS yet.


Anyway, `sleep` sleeps for 60 absolute seconds.
This means, that it will exit 60 seconds later, no matter whether you send an `SIGSTOP` or not.
You can reproduce this yourself, if you spawn a `sleep 60` in a shell, send it a `SIGSTOP`, wait for a minute and send `SIGCONT` again. The `sleep 60` process will exit immediately.

That's not a bug with Pueue, but rather an implementation detail of `sleep`

**Comment by Piping** [comment]
@Nukesor I am using the Linux. is it a special case or related to how pueue is implemented? Becuase I expect that Start and End time are exact 60 second. Right now it is only last one sec after pause/start.

**Comment by Nukesor** [comment]
Pueue checks about every 100ms whether the child processes are finished or not.

This doesn't affect the child processes at all. The only difference will be , that the `end` date will have a difference of at most one second, which really shouldn't be a problem. We don't need exact times anyway.

Regarding the absolute `sleep` time, it's a implementation detail of `sleep`.

This has nothing to do with Pueue, but is a feature of `sleep`

**Comment by Piping** [comment]
I understand that `pueue pause` sends `SIGSTOP` to `sleep 60` command, and then 60s later with `pueue start` sends `SIGCONT`,  `pueue` will find the process terminated successfully and the start/end time might not accurate. 

But the problem is that `pueue pause` and `pause start` are executed in relatively quick manner. when it resumes, it should able to find `sleep 60` command is still running(slept).  Just like `Ctrl-z` does to `sleep 60` command in terminal. You can stop it and resume it without `sleep 60` quitting early.

**Comment by Nukesor** [comment]
Weird.
I just tried to reproduce your issue and it seems to work quite fine.

![image](https://user-images.githubusercontent.com/3322822/97487218-dec3ed80-195c-11eb-883f-fcf6710e942f.png)

Pausing and resuming doesn't affect `sleep` at all.

Maybe I'm still getting something wrong? As far as I'm understanding your `sleep` process exits early, on `pause` and `start`?

**Comment by Piping** [comment]
@Nukesor I did some experiments now and found that `sleep 60` does work. Only displayed time (end) is not correct. Thanks for the troubleshooting.

**Comment by Nukesor** [comment]
I'm still confused, the time in your original example looks perfectly fine as well.

When starting `sleep 60` and running it normally, it finishes after 1 minute and the time is displayed correctly.
If you're pausing `sleep 60` process for two minutes and continue the process, the end time will be two minutes from the start time, just as expected.

In which scenario is the end time incorrect?

```
pueue add sleep 60 && \
pueue add sleep 60 && \
sleep 0.5 && \
pueue pause 0 && \
pueue start 1 && \
sleep 120 && \
pueue start 0 && \
pueue status && \
date

> Thu Oct 29 11:47:39 AM CET 2020
> New task added (id 0).
> New task added (id 1).
> Tasks are being paused: 0
> Tasks are being started: 1
> Tasks are being started: 0
> Default queue (1 parallel): running
> ────────────────────────────────────────────────────────────────────────────────
>  Index   Status    Exitcode   Command    Path                     Start   End   
> ════════════════════════════════════════════════════════════════════════════════
>  0       Paused               sleep 60   /home/nuke/repos/games   11:47         
> ────────────────────────────────────────────────────────────────────────────────
>  1       Success   0          sleep 60   /home/nuke/repos/games   11:47   11:48 
> ────────────────────────────────────────────────────────────────────────────────
> Thu Oct 29 11:49:40 AM CET 2020
```
