### ISSUE TITLE
[BUG] zsh completion still broken as of version 0.8.1

### ISSUE THREAD

**Issue by gotbletu** [Nukesor/pueue#133]
**Describe the bug**
bash one works fine but zsh completion still broken

everytime i source the **_pueue** file it gives me this message.
> _arguments:comparguments:325: can only be called from completion function

**To Reproduce**
```
pueue completions zsh ~/.config/pueue/
source "$HOME/.config/pueue/_pueue"
```

**Additional context**
- Pueue client 0.8.1
- Kernel: 5.9.1-arch1-1 x86_64 bits: 64 Desktop: Xfce 4.14.2 Distro: Antergos Linux
- zsh 5.8-1

**Comment by Nukesor** [comment]
The completion file must be installed into the zsh completion directory.

Feel free to check the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=pueue) for Arch's AUR install.

For arch the completion files are located in `/usr/share/zsh/site-functions/_pueue`.
```
install -Dm644 "utils/completions/_pueue" "${pkgdir}/usr/share/zsh/site-functions/_pueue"
```

**Comment by Nukesor** [comment]
I'm not exactly sure, if there's a user directory for zsh completions.

**Comment by Nukesor** [comment]
https://github.com/zsh-users/zsh-completions/blob/master/zsh-completions-howto.org#telling-zsh-which-function-to-use-for-completing-a-command

**Comment by gotbletu** [comment]
oh thanks, seems like it works now that i use the path /usr/share/zsh/site-functions
