### ISSUE TITLE
Notification after long running tasks are done

### ISSUE THREAD

**Issue by jbreitbart** [Nukesor/pueue#134]
**Is your feature request related to a problem? Please describe.**
I use pueue for example for long running downloads. I would like to get a notification when long running tasks are done. Something like https://github.com/jml/undistract-me/ just for tasks.

**Describe the solution you'd like**
As said, I'd like to get some sort of notification once a long running (or a set of long running?) tasks are done. I would not mind getting it for every long running task, but checking the status regularly is annoying. Also `watch 'pueue status'` looks a bit strange in my terminal

**Describe alternatives you've considered**
I am currently adding something like `notify-send "Downloads done"` to the end of my queue to get a notification. But that way I cannot enable parallel tasks.

**Comment by Nukesor** [comment]
Did you check the Readme or the wiki?
Pueues feature list includes a callback command which can be used for notifications.

There is an extensive configuration and miscellaneous guide in the wiki as well.

**Comment by jbreitbart** [comment]
Obviously not careful enough, I guess. Thanks for the hint. Here is the small shell script I am using for now, in case anyone is interested in the same funcationality:

```bash
#!/bin/sh

if [ $# -ne 3 ]
  then
    echo "Wrong parameter count"
    exit
fi

time=$(($2-$1))

# commands must at least run 15 minutes
if [ $time -lt 900 ]
  then
    exit
fi

time=$((time/60))

notify-send "pueue" "$3  - $time minutes"
```
