### ISSUE TITLE
[BUG] pueue version output behavior change

### ISSUE THREAD

**Issue by chenrui333** [Nukesor/pueue#143]
### reproduce

```
wget https://github.com/Nukesor/pueue/releases/download/v0.8.2/pueue-macos-x86_64 -O pueue
chmod +x pueue
./pueue --version
```

### output
```
$ ./pueue --version
Pueue client
```

### desired output
```
$ ./pueue --version
Pueue client 0.8.2
```

relates to https://github.com/Homebrew/homebrew-core/pull/65908

**Comment by Nukesor** [comment]
To be honest, I wasn't even fully aware of the existence of this flag.
It seems to come with Clap/Structopt by default :D
