### ISSUE TITLE
Feature request: pueue restar --replace

### ISSUE THREAD

**Issue by CharlesGueunet** [Nukesor/pueue#147]
I often find myself restarting a task then removing the old finished one.
So : `pueue restart <id>; pueue remove <id>`

Would it be possible to add a flag to the restart command so it also remove the old restarted task ?
(I have a long list of tasks that I like to keep so I can restart them easily, so I do not want to clean them all)

**Comment by Nukesor** [comment]
Hmm.

There're two different approaches to this problem.
Either a `--replace` flag, which actually "restarts" or in-place replaces the old task.
Or a `--remove-old` flag, which creates a new task, but deletes the old one.

The first solution seems to be the more elegant one.
This would also allow us to implement another nice feature. Right now, when one is using dependencies and a single dependency fails, all dependant tasks will fail and have to be restarted as well.

However, if we could restart tasks in-place while using the `pause-on-failure` setting, people could debug the failing command, edit and restart in-place and continue without having to restart any other dependant tasks.

**Comment by Nukesor** [comment]
While we're at it.

Should the `restart` command create a new task by default?
I did it, so one doesn't lose the logs of the previously failed task. But I'm no longer sure, if this is a good default.

**Comment by Nukesor** [comment]
Could you check, if the changes in #148 resolve your problem?

I really like the new behavior, since it makes the usage of dependencies much more feasible.

**Comment by CharlesGueunet** [comment]
Hello  @Nukesor - the new behavior seems really cool :) better that what I asked for primarily ! Thank you very much

**Comment by Nukesor** [comment]
Perfect :)

This will be released pretty soon as well :D
I actually wanted to publish a release earlier this week, but luckily I didn't manage to ;) This way we get another nice quality of life improvement.
