### ISSUE TITLE
Add command to move suspended jobs to pueue

### ISSUE THREAD

**Issue by OrangeFran** [Nukesor/pueue#166]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I start a command and realize some minutes later that the command
is taking a lot of time to finish.

**Describe the solution you'd like**
I would like to move a suspended command (job) to `pueue`.

**Describe alternatives you've considered**
I know that you can suspend the command and then use `bg` to run the command in the background
but I would like to use the features of `pueue`. And that is not possible with jobs.

**Additional context**
I imagine something like `pueue add --pid PID`.

**Comment by OrangeFran** [comment]
I will work on this if you think this is something viable to add.

**Comment by Nukesor** [comment]
Phew, 

I'm not sure, if something like this makes a lot of sense and if it's even possible.
We have to research a few things at first:

1. Is it possible to set a new parent process of any existing and detached processes. From what I can see in [here](https://unix.stackexchange.com/questions/193902/change-the-parent-process-of-a-process) it looks like it's not possible?
2. Is it possible to take an existing Process and create a new [Child](https://doc.rust-lang.org/std/process/struct.Child.html) instance from it?

What are your expected benefits?

From what I see, this only makes it easier to:

1. Pause/resume the task
2. Specify dependencies on this task.

Furthermore I would only like to add this feature, if it doesn't involve adding a LOT of additional code.
It would also be interesting how viable this is for Mac/Windows

**Comment by OrangeFran** [comment]
I hadn't though about if it's possible before creating this pr. Sorry. It seems that there is a thing called `reptyr` that can move a running command to a tmux session, so essentially changing the parent. But it only works on linux and is hackish, here is a link to a blog post of the creator explaining how the utility works: https://blog.nelhage.com/2011/02/changing-ctty/.

You're probably right that it's an edge case and I just have to get used to prepending `pueue` for long running commands. Thanks for you quick and clear response.

**Comment by Nukesor** [comment]
No need to apologize :)
I see how this could have been a useful feature! Unfortunately, from an implementation perspective, it's not very feasible.

I also aggree, that `reptyr` looks kinda hacky. Plus, this would require us to add C bindings to this library, which is something I would like to prevent :)

Let's close this issue for now.
