### ISSUE TITLE
Support different priorities in the queue

### ISSUE THREAD

**Issue by joe-antognini** [Nukesor/pueue#170]
**Is your feature request related to a problem? Please describe.**
I am often training many ML experiments, but I have a single GPU so I can only run one experiment at a time.  I like to have a queue of some low-priority experiments that are ready to go so that the GPU is always busy, but if I have an idea for a very interesting experiment, I would want it to run immediately (or after the current job finishes).  Likewise I might have an idea for an experiment that is more important than the low-priority backlog, but less important than another idea and would want it to run somewhere in the middle.

**Describe the solution you'd like**
When adding a job to the queue, allow the user to optionally specify a priority number.  Higher priority jobs always run before lower priority jobs.  Maybe similar to `nice` tasks can have priorities that range from -20 to 19 with 19 being the lowest priority and 0 being the default.  (Or it could have a more natural range like 0 to 100, it doesn't really matter.)

**Describe alternatives you've considered**
A hack that at least allows high priority jobs to run first is to do `pueue enqueue ...` followed by `pueue switch ...` to put it at the top.  But a priority number would allow for easier and finer grained control over the order in which jobs get run.

**Additional context**
n/a

**Comment by Nukesor** [comment]
Hm.

I see how this can be useful, but I'm not sure if this fits into the scope of Pueue.
It's main purpose is to be an ergonomic alternative to a terminal multiplexer.

Your request however, is rather related to load-balancing, and full-featured task scheduling.
There have already been quite a few requests/issues that wanted similar or related features, but I still think that it would be better to write a dedicated project for this.

That project could then have:

- Distributed workers
- Distributed load balancing
- Dynamic task stopping/starting depending on priorities of incoming tasks

To be honest, this sounds like an awesome and super interesting project.
But it just doesn't fit into the current scope of Pueue, which aims to just be a featue-complete, useful and neat little commandline helper.

**Comment by Nukesor** [comment]
There's one alternative to this whole thing.
Pueue actually offers a library, which allows communication with the Pueue daemon and thereby the task scheduler.

You could easily write your own wrapper around Pueue or run your own Pueue fork.
I just don't think, that this should be a default feature of Pueue, since this dramatically increases the complexity of this project.

**Comment by Nukesor** [comment]
Closing for now :)
