### ISSUE TITLE
Feature Request: coloring via config

### ISSUE THREAD

**Issue by Mephistophiles** [Nukesor/pueue#171]
**Is your feature request related to a problem? Please describe.**
My terminal with the solarized-dark theme does not show me the correct green colors. 
![colors](https://user-images.githubusercontent.com/4850908/105990347-65e74580-60b3-11eb-9273-ddaceee13f8f.png)

**Describe the solution you'd like**
It will be nice if the colors can change from the config file

**Comment by Nukesor** [comment]
Hm. To be honest, I would rather find out, why the green color is incorrectly rendered.

Pueue uses Crossterm for its color handling, which implements the default terminal colors.
Those are colors understood and used by pretty much every terminal.
https://docs.rs/crossterm/0.19.0/crossterm/style/enum.Color.html

Solarized however uses `0x586e75` for `green`.... Which is a color called `pale sky` (https://www.htmlcsscolor.com/hex/586E75). I'm not exactly sure why someone would use a blue/greyish color for green, though.
However, Solarized seems to properly display `darkgreen` as a normal green color.

Are `Dark*` Colors used by default and normal/"bright" colors are used for special stuff?
I'm not sure if there're any conventions for this.
In that case, we could simply adjust Pueue's Colors to use the Dark ones.

I would REALLY like to not support any custom color styling.

**Comment by Mephistophiles** [comment]
I has locally replaced green and red to dark green and dark red respectively.  At the same time, I decided to see how it would look on other themes ("running" status is still regular green):
* tango light
![tango_light](https://user-images.githubusercontent.com/4850908/106126234-2e899f00-616e-11eb-822c-7ac51758e98c.png)
* tango dark 
![tango_dark](https://user-images.githubusercontent.com/4850908/106126243-321d2600-616e-11eb-941a-3a491d50b02d.png)
* solarized light
![solarized_light](https://user-images.githubusercontent.com/4850908/106126274-3ba68e00-616e-11eb-81b8-36d80b5cdb3b.png)
* solarized dark
![solarized_dark](https://user-images.githubusercontent.com/4850908/106126294-4103d880-616e-11eb-869f-8e3566a6cb92.png)
* gnome light
![gnome_light](https://user-images.githubusercontent.com/4850908/106126327-49f4aa00-616e-11eb-9820-87b016bd5c35.png)
* gnome dark
![gnome_dark](https://user-images.githubusercontent.com/4850908/106126343-4eb95e00-616e-11eb-852b-4c96b9559706.png)
* white on black
![white_on_black](https://user-images.githubusercontent.com/4850908/106126361-54af3f00-616e-11eb-9dbd-577fd1795cc5.png)
* gray on black
![gray_on_black](https://user-images.githubusercontent.com/4850908/106126381-5973f300-616e-11eb-9a45-bce76cb3e1a2.png)

**Comment by Nukesor** [comment]
Hmm. The bright colors are definitely better in terms of visibility...
Maybe we really can't get around using custom color configurations.

I'll still do a little bit of research, to check whether we can somehow work around this.

**Comment by Nukesor** [comment]
I'm still super reluctant to implement this feature.

Plus, in my honest opinion, this is still a non-issue.
If a user decides to pick a color-scheme that sets `green` to a non-green color, than that's a choice met by the user.
Luckily, most terminals support easy adjustments of colors, in case somebody doesn't like a specific behavior of their colorscheme.

Allowing custom user colors significantly bloats and also complicates the display/output code, since we have to pass the client configuration struct through multiple layers of functions.

**Comment by Nukesor** [comment]
I think a good compromise would be to allow a switch to dark colors, while bright colors will stay the default.
Anyhow, coding this will be quite annoying, I'm not sure if I'm in the mood to do this.

**Comment by Nukesor** [comment]
I'll hapilly review and also accept a PR, which adds a new configuration flag for the client (dark_mode: bool) and a logic wrapper to get the correct color brightness depending on the current settings
