### ISSUE TITLE
Create tldr page

### ISSUE THREAD

**Issue by jakevossen5** [Nukesor/pueue#172]
I am a big fan of tldr pages as an alternative to help/man when possible, and I feel like there is a good opportunity to add a page for pueue. I opened a issue on the tldr repository https://github.com/tldr-pages/tldr/issues/5195 and figured I would post it here in case anyone wanted to work on it.

**Comment by Nukesor** [comment]
I've actually never heard of tldr pages before :D Looks like a fun project!

**Comment by bl-ue** [comment]
@Nukesor I agree with you! I think it is.  As a maintainer of the project, I invite you to [add a page](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md) for `pueue`! 😄

**Comment by bl-ue** [comment]
But it's not like I don't love learning a new tool :D 

I'll take this one.

**Comment by bl-ue** [comment]
There we go.  @Nukesor @jakevossen5 - please take a look and tell me what you think.

**Comment by jakevossen5** [comment]
It's merged! Thanks for all your work on this everyone!
