### ISSUE TITLE
[BUG] Cannot handle file names that contain spaces"

### ISSUE THREAD

**Issue by shhong** [Nukesor/pueue#179]
**To Reproduce**
```
touch "My Test File.txt"
pueue add -- mv "My Test File.txt" "My Test File Updated.txt"
```
Then,
```
$ pueue status
...
54      Failed    64         mv My Test File.txt My Test File Updated.txt   /Users/shhong/Documents   14:39   14:39

$ pueue log 54
Command:  mv My Test File.txt My Test File Updated.txt
...
Start:    Wed, 10 Feb 2021 14:39:15 +0900
End:      Wed, 10 Feb 2021 14:39:15 +0900

stderr:
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
```
**Expected behavior**
`pueue add` should work when the command arguments have spaces.

I used macOS 11.2 and pueue version 0.11.1.

**Comment by Nukesor** [comment]
This is explained in here:
https://github.com/Nukesor/pueue/wiki/Get-started#adding-commands

**Comment by Nukesor** [comment]
Either do:
`pueue add -- "mv 'My Test File.txt' 'My Test File Updated.txt'"`
`pueue add -- "mv My\ Test\ File.txt My\ Test\ File\ Updated.txt"`
or `pueue add --escape -- mv "My Test File.txt" "My Test File Updated.txt"`

**Comment by Nukesor** [comment]
Closing for now
