### ISSUE TITLE
A suggestion on handling new/restarted task

### ISSUE THREAD

**Issue by MuhammedZakir** [Nukesor/pueue#180]
**Problem:**

1. Add 2 tasks and kill them.
2. Run `pueue clean`.
3. Add a new task.

On #_3_, new task's index will be `3`, even though task list is empty. What I expect, however, is for pueue to add new task to the beginning of the list, i.e. new task's index will be `1`.

**Suggestion:**

I understand this will be more complex to implement and also users will get random indices for tasks (which is not a good idea). So, what I propose is to add task to the beginning of the list if total number of tasks is less than 3-5. At the very least, do this if there is only 1 task in the list or if the list is empty.

**Comment by Nukesor** [comment]
That's what the `reset` command is for.
This will reset all indices and remove all tasks.

The `clean` command only removes finished commands.
Consider this scenario

1. You have 50 Tasks in your queue
2. Half of them are finished and you don't need them any longer
3. Run `clean` so only the active tasks will be shown.

**Comment by MuhammedZakir** [comment]
> That's what the `reset` command is for.
> This will reset all indices and remove all tasks.

Yes, that's what I do. But, I was hoping pueue will reset indices for me, at least, when there is only one task in the list or if it's empty. Feel free to close this if it's pointless.

**Comment by Nukesor** [comment]
Indices should always increase, unless a flat reset is triggered.
Re-using indices could lead to weird and unexpected behavior.

You also never want to use a smaller ID than any existing ID.
Tasks are supposed to be scheduled on after another, ordered by their ID.
Adding a new task with ID `1` while already having a task with ID `3` would result in premature execution of that task.
I think that there's nothing wrong with having a task with ID `3`, even if there are no tasks in the queue.

Does this lead to any bugs?

**Comment by MuhammedZakir** [comment]
You're right. I have not thought about those. Closing this.

Thanks for the app! It is helping me a lot! :-)
