### ISSUE TITLE
Allow for structured output, at peast for `pueue status`

### ISSUE THREAD

**Issue by jakevossen5** [Nukesor/pueue#181]
I think it would be nice to have a structured output of the `pueue status` command, which could possibly be extended to other commands as well. I looked through the help and I didn't find anything like this, but I could be missing something. I think the most obvious use case for this is status bars (in my case, I would use [SwiftBar](https://github.com/swiftbar/SwiftBar)). It would then be a lot easier to checkup on the status of the commands running!

Something like `pueue status --json` maybe? I am kinda busy at the moment, but if you want I can try and add this if this is something you are interested in.

**Comment by Nukesor** [comment]
```
[nuke:~] % pueue status -h
pueue-status
Display the current status of all tasks

USAGE:
    pueue status [FLAGS] [OPTIONS]

FLAGS:
    -h, --help       Prints help information
    -j, --json       Print the current state as json to stdout. This does not include stdout/stderr
                     of tasks. Use `log -j` if you want everything
    -V, --version    Prints version information

OPTIONS:
    -g, --group <group>    Only show tasks of a specific group
```

:D

**Comment by jakevossen5** [comment]
Ah, didn't realize that was an option! Thanks!
