### ISSUE TITLE
[BUG] Empty stdout/stderr in log --json

### ISSUE THREAD

**Issue by crabvk** [Nukesor/pueue#186]
**Describe the bug**
stdout and stderr values in `log --json` output are always `null`

**To Reproduce**
```shell
pueue add -- 'echo hello'
pueue add -- 'echo error >&2'
pueue log -j # outputs null in stdout and stderr
```

**Expected behavior**
Output of `pueue log -j` has stdout and stderr values set same as `pueue log` does.

**Additional context**
- ArchLinux 5.11.6
- Pueue client 0.12.1
- Pueue daemon 0.12.1

**Comment by Nukesor** [comment]
Jep...
Turns out that is an open todo, I completely forgot about.
https://github.com/Nukesor/pueue/blob/master/client/display/log.rs#L42

I'm still not exactly sure, how this should be handled.
Log output can be huge and should never be fully loaded into RAM.
Are there json serialization libraries that support streaming for individual fields?

**Comment by crabvk** [comment]
Maybe limit the number of lines in output with some default value, or the number of characters.
Idk about json streaming.

**Comment by Nukesor** [comment]
There are multiple things that need to be looked at and implemented:

**Local log output**
- [ ] For multiple processes
- [ ] For partial log output
- [ ] For full log output?
- [ ] Support streaming for full log output

**Remote log output**
- [ ] For multiple processes
- [ ] For partial log output
- [ ] For full log output? This needs decryption
- [ ] Support json streaming for full log output

If we don't want to support json output for full logs, we still need a flag indicating whether the daemon should send the log output compressed or raw.

Full json logs are probably a bad idea anyway.

**Comment by Nukesor** [comment]
@crabvk The fixed version and a lot more is located on the v0.13 branch :)
It would be awesome, if you could go ahead and help testing the new version!

**Comment by Nukesor** [comment]
The release candidate is now available.
`cargo install pueue --version 1.0.0-rc.1`
