### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ElectronicViking** [Nukesor/pueue#190]
No output when printing the status of the default group.

1. Add tasks to the default group.
2. Run status command "pueue status -g default".

**Expected behavior**
I expected the default group's status to be displayed. It shows up normally in "pueue status". I'm aware groups without tasks are omitted and this is not the case.

**Additional context**
Arch Linux, fully updated.
Pueue client 0.12.1, Pueue daemon 0.12.1.

**Comment by ElectronicViking** [comment]
I suspect the issue is in client/display/state.rs at line 71.

**Comment by Nukesor** [comment]
Thanks for the report :)
Fixed in b37532b
