### ISSUE TITLE
Dropping to an interactive shell

### ISSUE THREAD

**Issue by SuperSandro2000** [Nukesor/pueue#192]
**Is your feature request related to a problem? Please describe.**
I want to queue long running commands in the background that open an interactive shell in the background and attach to that shell when it is ready.

**Describe the solution you'd like**
pueue attach to attach to a running command.

**Describe alternatives you've considered**
Hacking something together with unbuffer and bash -i.

**Additional context**
The shell right now is closed immediately because it thinks it is not interactive.

**Comment by Nukesor** [comment]
I actually thought about something like this and this is something that doesn't fit into the scope of Pueue.

It would be super awesome to have some tool to manage interactive long running processes.
I'm managing a lot of game-servers and it's super annoying with tmux.

Already thought about taking Pueues code and reworking it to something alike, but I don't have time for that right now.


Anyway, It would be awesome to have a dedicated solution for this problem. Feel free to take Pueue's code-base as a base/inspiration. I would definitely be super interested in this :)
