### ISSUE TITLE
Version 1.0

### ISSUE THREAD

**Issue by Nukesor** [Nukesor/pueue#201]
This is the tracking Issue for v1.0

### Backward/forward compatibility

- [x] Default values can be used to ensure backward/forward compatibility.
- [x] State's shouldn't get dropped unless absolutely necessary.
    - [x] If new fields get added
    - [x] If existing fields get removed
- [x] Messages don't get dropped. In worst-case scenarios, errors get at least properly handled.
    - [x] If too many fields are sent.
    - [x] If too few fields are sent, but defaults exist
    - [x] Inform client on critical deserialization errors
    
### Stability

- [x] Screen code for possibly impossible states in datastructures. Refactor such code to use Enums.
- [x] Integration test setup. Until now, we only had unit tests
- [x] Test most important Daemon API calls using new integration test setup.
- [x] Move application-specific logic from `pueue-lib` into daemon or client.
    As `pueue-lib` has previously been integrated in the `pueue` crate and extracted around version 0.12, there are still some parts of the code-base that don't belong there.
    
### Error handling

- [x] Overall better error messages and more context on crashes.
    Users should always get a meaningful error message for better bug reporting.
- [x] Review log messages for clarity and meaningfulness of texts and appropriateness of their loglevel.
- [x] Properly test and improve graceful shutdown in `pueued`.

### Release-candidate -> Wait -> Improve -> Repeat cycle

- [x] Release v1.0.0-rc.1
- [x] Release v1.0.0-rc.2
- [x] Release v1.0.0-rc.3
- [x] Release v1.0.0-rc.4
- [x] Wait for a few weeks until no new ciritcal bugs or issues pop up.

**Release v1.0.0**

- [x] Release v1.0.0

**Comment by dovahcrow** [comment]
The README seems not correct here:
```
git clone git@github.com:Nukesor/pueue
cd pueue/pueue
cargo install --path .
```

I guess it should be `pueue/client`

**Comment by Nukesor** [comment]
Ah thanks :)
Seems I forgot to adjust this, when changing the directory structure a few versions ago.
Should be fixed now

**Comment by Nukesor** [comment]
You can install the first release candidate like this:
`cargo install pueue --version 1.0.0-rc.1`

**Comment by Nukesor** [comment]
Second release candidate is out:
`cargo install pueue --version 1.0.0-rc.2`

**Comment by dovahcrow** [comment]
@Nukesor Thanks! Will try it out.

**Comment by Nukesor** [comment]
Third release candidate is out:
cargo install pueue --version 1.0.0-rc.3

**Comment by Nukesor** [comment]
Forth release candidate is out:
```
cargo install pueue --version 1.0.0-rc.4
```

- You can no longer remove groups, if there are still tasks assigned to that group.
- Add a worker pool representation for groups to Pueue [#218](https://github.com/Nukesor/pueue/issues/218).
    The task's group name and the pool's worker id for a given task are then injected into the environment variables of the subprocess.
    This allows users to map Pueue's internal group and pool logic to external resources:
    ```
    ./run_on_gpu_pool --gpu $PUEUE_WORKER_ID --pool $PUEUE_GROUP`
    ```
- Rename `Index` to `Id` in `pueue status` to free up screen space.
- Remove `Exitcode` column in `pueue status` and include exitcode into `Failed` status to free up screen space.
- Many messages have been touched, as several new enums have been introduced to eliminate impossible states.
- A lot of new integration tests.

We're getting closer to a possible v1.0 release.

**Comment by Nukesor** [comment]
I'm planning to release v1.0 this week :)

Are there some people out there, that actually worked with the release candidates :D?
If yes, it would be awesome if you could leave a thumbs up or tell me about your experience :)

I'm still a little hesitant to push the v1.0 release button, since it's a pretty big thing to do (at least for me). Having some people actually test this, would definitely boost my confidence in the current release.

Thanks in advance :)

**Comment by dovahcrow** [comment]
@Nukesor I used the RC versions, no bugs were encountered :D

**Comment by Nukesor** [comment]
Thanks for the help :)

v1.0.0 is now finally out there :relaxed:
