### ISSUE TITLE
How can I start daemon? [BUG]

### ISSUE THREAD

**Issue by Fatpandac** [Nukesor/pueue#209]
**Screenshots**
![image](https://user-images.githubusercontent.com/30423976/119676740-acd22580-be70-11eb-8513-65aee17c5720.png)

![image](https://user-images.githubusercontent.com/30423976/119677767-95476c80-be71-11eb-8bf2-9381ca627741.png)

**Additional context**
- Windows 10
- 0.12.2

**Comment by Nukesor** [comment]
Dude. There's a whole wiki with a getting started guide linked in the Readme with a big fat heading saying: `How to use it`

Closed due to laziness
