### ISSUE TITLE
Restart improvements

### ISSUE THREAD

**Issue by CharlesGueunet** [Nukesor/pueue#211]
Hello and thanks again for this nice software,

I have some suggestion concerning the restart command.
First, would it be possible to restart a whole group using a `--group <name>` option ? It would be nice coupled with the `--in-place` mechanism :). Of course this option would replace the need to give tasks indices explicitly.

Also, to keep things clean it may be convenient if we had an easy way to make pueue recompute the indices. I don't like to have discontinuous indices due to task removal, but this is more aesthetic I agree.

Best,
Charles

**Comment by Nukesor** [comment]
The second proposal is already implemented for v1.0.
You can get the release candidate with `cargo install pueue --version 1.0.0-rc.1`

I agree that having a `--group` flag on `restart` only makes sense, since pretty much everything else has that flag as well :D

**Comment by Nukesor** [comment]
This should be a quick fix, I'll probably build this tomorrow

**Comment by Nukesor** [comment]
Resolved in #3d09b7e

**Comment by Nukesor** [comment]
Second release candidate is out and includes this feature:
`cargo install pueue --version 1.0.0-rc.2`

**Comment by CharlesGueunet** [comment]
Small sidenote here, what I meant was to have a:

`pueue restart --group test` to resart all tasks of the group without having to give them one by one. I have not managed to do that yet :)
