### ISSUE TITLE
[HELP WANTED] Backward Compatibility for Data Structures

### ISSUE THREAD

**Issue by Nukesor** [Nukesor/pueue#216]
Here's what happened.

Due to some internal refactorings in pueue-lib the enum TaskStatus changed from this:

``` 
#[derive(PartialEq, Clone, Debug, Display, Serialize, Deserialize)]
pub enum TaskStatus {
    ...
    /// The task has been manually stashed. It won't be executed until it's manually enqueued
    Stashed,
    ...
}
```
to this:
``` 
#[derive(PartialEq, Clone, Debug, Display, Serialize, Deserialize)]
pub enum TaskStatus {
    ...
    /// The task has been manually stashed. It won't be executed until it's manually enqueued
    Stashed { enqueue_at: Option<DateTime<Local>> },
    ...
}
```

Now this seems to be rather tricky.
Keeping backward compatibility is simple when adding or removing fields, as they can just be ignored or one specifies a default value.

However, when changing the actual structure of an existing struct/invariant, serde fails as it cannot deserialize old serialized data into the new format.

I guess the solution to this would be a custom deserializer, but this seems to be rather tricky:
- It has to support `json`, as well as `cbor`
- It should only handle this one error-case. Other errors should still fail as expected.

I'm not too familiar with serde's internals and haven't been in the mood to dig into this yet.
Any help on this topic is very much appreciated!

For now this isn't a blocker, but this might happen again in the future.
If that's the case, I want to know how to handle something like this.

**Comment by Nukesor** [comment]
The oldschool approach would probably be, to keep legacy data structures in the code-base.
If the newest datastructure fails, the old ones will be tried in chronological order and there will be migration paths between all structures up to the newest one.

I really don't like this approach to be honest, since it results in a lot of basically unused code whose sole purpose is backward  compatibility.

**Comment by noyez** [comment]
Do you have a test case where this fails, or a way to reproduce the errors from serde?

**Comment by Nukesor** [comment]
I just created a branch in pueue-lib. There's a new test case, which produces the issue explained above.
https://github.com/Nukesor/pueue-lib/tree/experiment

**Comment by Nukesor** [comment]
Closing for now :)
