### ISSUE TITLE
[BUG] Can't increase parallel job count 

### ISSUE THREAD

**Issue by yigitkonur** [Nukesor/pueue#221]
**Describe the bug**
I've started a job runs in 10 parallel jobs but I want to optimize my parallelism by monitoring resources. But it won't increase the running job count.

**To Reproduce**
1. I added a task with `pueue add -- this is the command`
2. Then I've used to count running jobs `pueue status -g s3 | grep Running | wc -l`
3. I've increased parallel job count `parallel 1000 -g s3`
4. I've re-test job count with grep: `pueue status -g s3 | grep Running | wc -l` - but it won't increase
5. I've increase `ulimit -n 99999` to see whether OS is blocker or not - but won't owrk
6. Then, changed my way to measure tasks to `ps aux | grep rsync` (but it won't increase)
7. Tried to lower parallel job count to 1 and it worked perfectly, but can't increase more than 10.

**Expected behavior**
I wish to use pueue like I use GNU parallel to use my resources effectively.

**Additional context**
- Ubuntu 20.04
- Pueue client 0.12.2

**Comment by Nukesor** [comment]
If these are the real commands you're using, you created a group `s3`, but don't add the tasks to that group, but rather the `default` group. If you want to use `s3`, you have to add to `pueue add -g s3 --` as well.

Could you try this:

```
pueue group -a testgroup
pueue parallel 100 -g testgroup

for i in $(seq 1 100); do
    pueue add -g testgroup -- sleep 60
done
sleep 5
pueue status | grep Running | wc -l
```
If this is working, this is probably some kind of user error.

Tasks don't spawn instantly, so this might take some time.
In my case (on the newest branch) Pueue took about 2 minutes to spawn 1000 tasks.

**Comment by yigitkonur** [comment]
Thank you for swift response! Actually, I've re-tried by the exactly same way as you clearly described. Should I set parallel first, then add task? Can I also increase the current groups' parallelism by increasing the value while queue is running?

<img width="657" alt="CleanShot 2021-07-26 at 17 47 09@2x" src="https://user-images.githubusercontent.com/9989650/127009136-0d4d7042-f64b-4687-9eb8-c56aa806a03d.png">
(the name of group was ibm-s3, not only s3 - please take my example name as placeholder)

**Comment by Nukesor** [comment]
Did you try my code, and did that work?

It doesn't matter, whether you add the tasks at the end or change the amount of parallel tasks after adding the tasks.
Did you ensure, that your tasks are in the correct group, when looking at `pueue status`?
Are there enough tasks to saturate the worker pool? (More than 5 tasks?)

There are obviously multiple tasks running. A full `pueue status` log would be much more helpful to debug you problem.

Please also check, whether my example code works or not.
Also make sure the groupnames work as expected

**Comment by Nukesor** [comment]
It would be awesome, if you could provide me with a minimal example of commands, which reproduce your behavior on a clean Pueue configuration (no groups, no active tasks).
