### ISSUE TITLE
output stdout and stderr bare

### ISSUE THREAD

**Issue by dmd** [Nukesor/pueue#222]
I'd like to be able to get stderr and stdout *exactly as recorded* without the pueue header on it - and separately from each other.

E.g., I'd like to be able to say `pueue stdout 123 > somefile` and have somefile contain **exactly** and **only** the stdout of job 123. 

Or this could be done as a flag to `pueue log`.

**Comment by Nukesor** [comment]
I see how this can be useful.
Right now there are two approaches to achieve this, but depending on your use-case they might be unfeasible.

1. If you're working with a local daemon, you can read the files directly, as they're actual files on your system. They're located in Pueue's working directory.
    For instance, `~/.local/share/pueue/task_logs`.
2. `pueue log -j` in combination with `jq`.
    `pueue log 0 -j | jq '.["0"]["stdout"]' > some_file`
    
It would be interesting to hear your exact use-case.

In case those two are unfeasible or too unergonomic, we would have to add a few styling flags for the client.

- `-e|--stderr` to only show stderr
- `-o|--stdout` to only show stdout 
- `--no-headers` to hide the tasks' headers and info texts

**Comment by dmd** [comment]
The log -j thing will work for me -- now that I  saw  #223 . Thanks.

**Comment by Nukesor** [comment]
Perfect :)
In that case, I'll close this issue.
