### ISSUE TITLE
[BUG] clap-related build error

### ISSUE THREAD

**Issue by sourcefrog** [Nukesor/pueue#224]
On Debian with `rustc 1.54.0 (a178d0322 2021-07-26)` building eb8d5c9c845a4e8ea064979e4d37ec092abca863 

I get some build failures:

```
nice cargo install --path ~/src/pueue

....

   Compiling pueue v1.0.0-rc.4 (/home/mbp/src/pueue)
error[E0277]: the trait bound `cli::Shell: ArgEnum` is not satisfied
   --> client/cli.rs:383:16
    |
383 |         shell: Shell,
    |                ^^^^^ the trait `ArgEnum` is not implemented for `cli::Shell`
    |
    = note: required by `clap::ArgEnum::from_str`

error[E0277]: the trait bound `cli::Shell: ArgEnum` is not satisfied
   --> client/cli.rs:383:16
    |
383 |         shell: Shell,
    |                ^^^^^ the trait `ArgEnum` is not implemented for `cli::Shell`
    |
    = note: required by `VARIANTS`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0277`.
error: could not compile `pueue`

```

I don't get this when just building the tree with `cargo build` or `cargo check` so I suspect some difference in how dependency versions are being resolved...

**Comment by Nukesor** [comment]
Daaaamn.

Everything looked perfectly fine and I decided to just release v1.0 before checking my issues again.
What a timing :D 

I'm investigating the issue

**Comment by Nukesor** [comment]
Ok. This isn't an issue with Pueue. The current locked file works perfectly fine.
It's rather an issue on how `cargo install --path` works.

https://github.com/rust-lang/cargo/issues/6983

It ignores the lockfile. You have to explicitely add `--locked` for everything to be perfectly identical to the current release.

**Comment by Nukesor** [comment]
Clap just released a new version `3.0.0-beta.4`, which introduces some breaking changes.
Thats why it's failing without the `--locked` parameter.

I'm going to close this issue, once the readme has been adjusted :)

**Comment by Nukesor** [comment]
Readme has been adjusted!

**Comment by sourcefrog** [comment]
OK I can confirm `--locked` fixes it.

Most crates don't need this so I wonder how many users will think to try it or look at the readme. Maybe Pueue should just be updated for the Clap change? (Also it goes to show how hard semver is in practice.)

**Comment by Nukesor** [comment]
I already pushed a fix to master, but didn't publish a new release yet.

I guess, I'll release the patch tomorrow or saturday. I got a lot to do right now and I want to take a closer look at the changes in the new clap release.

**Comment by sourcefrog** [comment]
Thanks - I didn't want to put any pressure on you to release it today, just wanted to make sure you knew, because it sounded from https://github.com/Nukesor/pueue/issues/224#issuecomment-901492515 like you'd only changed the readme.
