### ISSUE TITLE
[BUG] Picking up flags inconsistently

### ISSUE THREAD

**Issue by ShadowJonathan** [Nukesor/pueue#233]
**Describe the bug**
running something like `pueue add rsync -savPhz ...` produces the following;

```
jonathan@jon:/mnt/data$ pueue add rsync -savPhz ftb odroid.fritz.box:/data/video/
error: Invalid value for '--after <after>...': invalid digit found in string

For more information try --help
```

This is because pueue is picking up the `-a` flag inside the `rsync` command added.

**Expected behavior**
For pueue to copy-paste the entire command line after `add` and not to worry about flags any further.

**Additional context**
- Operating System; `PopOS 21.04`, Rust 1.54
- Pueue version; `Pueue client 1.0.1`

**Comment by Nukesor** [comment]
Please read the getting started guide:

https://github.com/Nukesor/pueue/wiki/Get-started#adding-commands
