### ISSUE TITLE
[BUG] Compilation error

### ISSUE THREAD

**Issue by happysalada** [Nukesor/pueue#235]
**Describe the bug**

compiling from src requires nightly right ?
I tried compiling from source with rust 1.54 and this is what I get
```
pueue> error[E0658]: arbitrary expressions in key-value attributes are unstable
pueue>  --> /private/tmp/nix-build-pueue-1.0.1.drv-0/pueue-1.0.1-vendor.tar.gz/clap/src/lib.rs:8:10
pueue>   |
pueue> 8 | #![doc = include_str!("../README.md")]
pueue>   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pueue>   |
pueue>   = note: see issue #78835 <https://github.com/rust-lang/rust/issues/78835> for more information
pueue> error: aborting due to previous error
pueue> For more information about this error, try `rustc --explain E0658`.
pueue> error: could not compile `clap`
pueue> To learn more, run the command again with --verbose.
pueue> warning: build failed, waiting for other jobs to finish...
pueue> error: build failed
```

**Additional context**
- darwin
- Pueue version. 1.01

**Comment by Nukesor** [comment]
Pueue is designed to compile on the current stable release, which is 1.54 at the current time.

Sadly I cannot reproduce your issue, as I don't have a darwin machine.
However, this looks a little like a machine-specific problem, as there are already build artefacts for the 1.0.1 release, which are build on Github CI's MacOsX build systems.

**Comment by happysalada** [comment]
In the issue referenced, there are a couple of links to repos pinning the clap to version beta-2
https://github.com/rust-lang/rust/issues/78835
I'm updating this package for nixos and the ci running on linux encountered the exact same problem.
The ci logs are quite sparse, but it seems to be the same issue https://github.com/NixOS/nixpkgs/pull/135845/checks?check_run_id=3438993289

If you are not encountering this issue, I wonder what could be different on your settings to make this pass.
I'm going to ask in clap directly, since this does not seem to be a pueue issue.

**Comment by happysalada** [comment]
After more checking, the compilation was using rust 1.53 and not 1.54.
Upstream answered that they updated the minimum rust version specifically for that problem which gets stabilized on 1.54.
Sorry for the bother, and thank you for having a look!
