### ISSUE TITLE
Is nomad considered as Similar Projects?

### ISSUE THREAD

**Issue by amfern** [Nukesor/pueue#237]
https://github.com/hashicorp/nomad is a task runner, i think it should be added to the similar projects list

**Comment by Nukesor** [comment]
Nomad is a production-ready workload balancer for commercial applications, including things like distributed cloud deployments.
Pueue is a designed to be a simple commandline helper tool for working with the shell.

I don't think these we should mention Nomad. Nomad solves completely different problems than Pueue, while introducing a lot of complexity. It's like comparing a normal hammer with a wrecking ball.

**Comment by amfern** [comment]
Thanks for clarifying
