### ISSUE TITLE
Implementation of Profiles

### ISSUE THREAD

**Issue by JP-Ellis** [Nukesor/pueue#244]
Currently, pueue allows users to switch between different configuration using the `--config` flag.  I suggested in #243 that it might be worth considering implementing profiles within the configuration so that one configuration file is used and the users can switch between different sockets/configs with `--profile`.

I have quoted a few of the relevant bits from the other conversation below

<details>
<summary>JP-Ellis: Initial suggestion</summary>

> And perfectly good point regarding the command line flags. They may not be the best way, and pointing to different configs might be best. In fact, as an alternative to switching between configs, could it be worth having separate profiles within the one configuration file? This could be done in a way that is backwards compatible if the schema for the config was changed from:
> 
> ```yaml
> client:
>   # ...
> daemon:
>   # ...
> shared:
>   # ...
> ```
> 
> to:
> 
> ```yaml
> client:
>   # ...
> daemon:
>   # ...
> shared:
>   # ...
> 
> remote:
>   client:
>     # ...
>   daemon:
>     # ...
>   shared:
>     # ...
> 
> other_profile:
>   # as above
> ```
> 
> The `default` profile we refer to the one that isn't named, and users could specify as many profiles as they want as long as it was not called `client`, `daemon` or `shared`. A command line flag `--profile x` would allow one to easily switch between each.

</details>

<details>
<summary>Nukesor reply</summary>

> Regarding the structure of different profiles. The profiles should probably be located in one parent key:
> 
>   ```
> client:
>     # ...
> daemon:
>     # ...
> shared:
>     # ...
> profiles:
>    remote:
>         client:
>             # ...
>         daemon:
>             # ...
>         shared:
>             # ...
>     other_remote:
>         client:
>             # ...
>         daemon:
>             # ...
>         shared:
>             # ...
>   ```
> 
>   That way implementing and verifying the config is much easier.

</details>

**Comment by Nukesor** [comment]
This feature has been implemented in #281  :)

Could you go ahead and check if this suits your needs?
