### ISSUE TITLE
[Minor BUG] Panic When Pueue Stdout/Stderr closed

### ISSUE THREAD

**Issue by JP-Ellis** [Nukesor/pueue#253]
Firstly, this is an extremely minor bug and does not affect the running of tasks, at least not that I've seen.

It appears that when `pueue` is outputting information to `stdout` or `stderr` and the output pipes are closed before `pueue` is done, `pueue` then panics with:

```
thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', library/std/src/io/stdio.rs:1193:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I encounted this issue when checking the status of a large number of tasks and piping it in [`bat`](https://github.com/sharkdp/bat), but it can be more reliably replicated with 

```
pueue status | head -c0 > /dev/zero
```

The issue also arrises with `pueue log` and I suspect anything else that outputs to `stdout`/`stderr` will reproduce this.

**Comment by Nukesor** [comment]
The thing is, that I/O errors can happen everywhere. We would have to rewrite all `println!` or any log macros in functions, whose std ioerrors would then be bubbled to the top with a custom error message.

IMO, I/O errors are one of those errors that are nearly impossible to catch everywhere without bloating your codebase by 30%.

**Comment by JP-Ellis** [comment]
I wouldn't say that it is unexpected behaviour as it is pretty common to pipe output and truncate the piped output; having said that, I am perfectly happy with you marking this as a "Won't Fix" as I understand it is a completely minor issue :smile: 

I'm curious how programs like [`bat`](https://github.com/sharkdp/bat) avoid this as truncating the output works fine.

**Comment by Nukesor** [comment]
To be honest, I just can't be bothered to fix this issue :D 

I'll close this until somebody comes up with this issue once more or until somebody volunteers to implement this themselves.
