### ISSUE TITLE
[BUG] switching tasks with itself crashes the daemon

### ISSUE THREAD

**Issue by jbedo** [Nukesor/pueue#262]
**Describe the bug**

I accidentally tried to switch a task with itself and the daemon crashed:

```
$ pueue switch 639 639
Error: Io Error: unexpected end of file
  
Caused by:
    unexpected end of file
```

**To Reproduce**
1. pueue switch 123 123

**Expected behavior**

No-op.

**Additional context**
- Centos
- Pueue 1.0.3

**Comment by Nukesor** [comment]
Wow :D

Thanks for reporting that one. It seems I overlooked that possibility.

Fixed in #507027a
`v1.0.4` will be released momentarily.
