### ISSUE TITLE
[BUG] Task locked on `pueue edit` if `EDITOR` environment variable not set

### ISSUE THREAD

**Issue by drewkett** [Nukesor/pueue#267]
**Describe the bug**
If $EDITOR isn't set when running `pueue edit`, you get an error suggesting that EDITOR isn't set which is nice. However, the task then is locked presumably because the error early returns. This would ideally be handled such that the task is not locked.

Also I'm not sure what the right way to unlock a task, but it seems stash works. I'm not sure if this is documented anywhere.

**To Reproduce**
```
unset EDITOR
pueue edit <N>
```

**Expected behavior**
Ideally the locked state would be cleared if the editor failed to launch

**Additional context**
- Linux
- Pueue version 1.0.4

Also, thanks for the software. Super helpful

**Comment by Nukesor** [comment]
Good point.
I guess it makes sense to unlock the task if either the variable doesn't exist or the editor exits with a non-zero exit code?

For a temporary work-around, you can manually `enqueue` the task. That way it doesn't stay in that locked state.
