### ISSUE TITLE
Follow both stdout and stderr

### ISSUE THREAD

**Issue by kpcyrd** [Nukesor/pueue#268]
**Is your feature request related to a problem? Please describe.**

I'm trying to run `cargo build` with pueue and queue a few commands I'd like to run afterwards, while having one terminal open with `pueue follow` to monitor the output while compiling

**Describe the solution you'd like**

`pueue follow --tbd-both-stdio` could print both stdout and stderr.

**Describe alternatives you've considered**

I've tried `pueue follow -e` but that way I only get stderr, not both.

**Comment by Nukesor** [comment]
Hey :)

This is actually a duplicate of #239, as this will inherently lead to both streams being displayed in the default `follow` command.

**Comment by kpcyrd** [comment]
Cool, closing this issue in favor of #239 then! :)
