### ISSUE TITLE
More succinct stats about the queue

### ISSUE THREAD

**Issue by VaguelyUseful** [Nukesor/pueue#274]
#### Describe the solution you'd like
Have `pueue status ` return, at the bottom, more succinct statistics. For example, about how many tasks there are in total, how many are running, and how many are queued. Bonus points if I can awk the stats for use in a shell script.

**Comment by Nukesor** [comment]
What's your exact use-case? It would be great to have an idea of ​​what you need this feature for.

I suppose in your case it's for automation, mainly because you mentioned `awk`. But I'm curious nonetheless, and it's always good to have more information before deciding whether to add a feature and what it should look like.

**Comment by VaguelyUseful** [comment]
One of my uses of pueue is for making contact sheets for large batches of video files, so it'll batch maybe 100 commands to pueue at a time. If the intake script is run again before pueue is done with the queue, it'll add duplicate entries to pueue. If, at the bottom of the `pueue status` contains something like "Done: 13, Processing: 4, Queued:20" then it would be trivial to implement in a script something like "if queue isn't empty, don't add anything"

Plus, sometimes the output of `pueue status` is so long, it is actually longer than the scrollback buffer in my terminal, so it'd just be nice to see at a glance how many jobs there are vs how many are done.

**Comment by Nukesor** [comment]
For more complex logic like this, `pueue status` exposes all data via a json output with the `-j` flag.
The structure of that data is basically the full internal pueue state: https://docs.rs/pueue-lib/0.18.1/pueue_lib/state/struct.State.html

Could this solve your problems?

**Comment by VaguelyUseful** [comment]
Actually, yes. I had no idea this flag existed. I'm now pulling exactly what I need. Thank you for the info!

**Comment by Nukesor** [comment]
Perfect :)
Sorry for the late response, the last few weeks were a little packed.
