### ISSUE TITLE
Non-file inputs for TLS certificates and shared secret

### ISSUE THREAD

**Issue by Nukesor** [Nukesor/pueue#276]
This issue originates from the old pueue-lib repository:  https://github.com/Nukesor/pueue-lib/issues/10

Original text:

**Is your feature request related to a problem? Please describe.**
I'm trying to write a custom remote client for pueue, but I'm running into the issue that I don't want to have to distribute the certificate or shared key as a file beside, if at all inside, the binary itself as I would like to be able to pull in those values at runtime and handle them purely in memory.

**Describe the solution you'd like**
Implementation of String/similar inputs for certificates and the shared secret so that they can be specified programmatically as Strings or buffers or other, meaning that it should be possible to deal with inconsistencies in underlying platforms and without the security implications of having to distribute the shared secret and certificates as files to those who need access.

**Describe alternatives you've considered**
- SSH: Not an option for our environment unfortunately
- Creating the relevent files at runtime: Since it's supposed to be a self-contained program, ideally I would strongly prefer minimising direct fs interaction

**Additional context**
None

---
I'd be more than happy to take a shot at developing the feature myself, and I have a few ideas of how it could be made feasible with minimal disruption to the library's existing API.

**Comment by Nukesor** [comment]
Old issue conversation:

# 1. Anwer by @Nukesor  

First of all, sorry for taking so long. The last months were quite busy.

I see how this can be useful when building your own tools :).
However, I also see how this can be tricky to achieve without disturbing the API too much, as the configuration, certificate handling and socket handling are super intertwined.

I would be ok with a few breaking changes, as there are already some breaking changes lined up for the next version.
The pueue project would of course have to be adjusted as well.

I guess the cleanest way would be to refactor this whole part into several parts?
Something like this:

- Get certificates from blob
- Get certificates by path via Settings
- Create listener/connectors from certs + Settings

Before you continue exploring this issue.
I'm in the process of moving the whole tls logic to rustls v0.20, while migrating to tokio and tokio_rustls at the same time.

Once this is finished and merged, you can go back to tinkering :)

# Second Answer by @WolfSkin0

Sure, that works fine by me!
I don't expect it to be a particularly painful switch, so for now I can just continue working in parallel to the main branch as it updates, and then once that's done (assuming I'm then ready too), I can submit a PR and we can look at how well it works.

In terms of my idea for what to do (idk if you looked at my fork or not), but I'm trying out a method based on using an enum for differentiating between path and memory, and then abstracting the logic for that away in the helper functions that already exist.
The only design issue I've been running into is the functions that natively deal with creating local files for certs, etc. But I'm tempted to just ignore them because I feel like anyone who's using pueue-lib with certs from memory, is likely to also be using their own storage mechanism for everything, which means that the path-based stuff is just mainly there for the main binary and whoever else may want to use it.
On that note, might it be worth (and this is a completely breaking change ofc), splitting off fs-based stuff into its own smaller convenience crate, or, at this tbh a module, since that should open up to future flexibility for even the main binary itself?

# Third answer by @Nukesor 

Adding a new crate for a few helper functions would be overkill. A separate module would definitely be fine though.

Depending on how annoying the code branching based on that enum is, I would be totally fine with splitting the logic into multiple functions :) As I said, there already are breaking changes in the upcoming release.

The upgrade to rustls 0.20 and tokio is done and merged on master :)
Quite a lot of stuff changed, as rustls introduced a lot of breaking changes in v0.20 in order of stabilizing their own API for a possibile future 1.0 release.

**Comment by Nukesor** [comment]
@WolfSkin0 are you still actively working on this?

**Comment by WolfSkin0** [comment]
Hi, sorry for the late reply. Work's been swamping me lately, new year and all that. I've got some code lying around though, so I'll see if I can scratch something together over the weekend

**Comment by Nukesor** [comment]
Don't stress yourself :)
I'm just doing some spring cleaning and checking the status of all of my project's issues ;D

**Comment by Nukesor** [comment]
I'm going to close this for now ;)
If you're making some progres, just open a PR and I'll re-open the issue!
