### ISSUE TITLE
[BUG] -a flag processed incorrectly

### ISSUE THREAD

**Issue by farid-fari** [Nukesor/pueue#277]
Since version 1.0.5, the `-a` flag only uses the first argument instead of several. For example, if tasks 0 and 1 are finished, the following command used to behave as expected:

    pueue add -a 0 1 -- sleep 10

Whereas now, it will incorrectly be interpreted as executing `1 sleep 10` after task 0.

**Comment by Nukesor** [comment]
Looks like clap introduced changed their API in the final 3.0 release

6c438f1 fixes this and further bumps clap to fix a few other potential bugs.
I'll release a new patch momentarily
