### ISSUE TITLE
Add completion scripts to the Arch package

### ISSUE THREAD

**Issue by Yamakaky** [Nukesor/pueue#28]

**Comment by Nukesor** [comment]
At first i need to adjust the completion script... The commandline interface got a bit more complex in the last view weeks and the zsh completion syntax is really confusing.
I'll probably need some help for this or it'll take some time.

**Comment by Yamakaky** [comment]
https://github.com/Infinidat/infi.docopt_completion

**Comment by Nukesor** [comment]
I'm not yet sold on the idea of using docopt. It has 160 open issues and the last master commit was on 16. April 2016.
The validation methods for docopt are kind of inconvenient. Docopt looks like a nice solution for simple commandline interfaces in its current state.

**Comment by Nukesor** [comment]
The zsh completion file is now installed with `pueue-git` and `pueue`, but it's still not up to date.
I'll do this as soon as I'm finished with the `key` refactoring.
