### ISSUE TITLE
[BUG] how to build completions on development branch?

### ISSUE THREAD

**Issue by Mephistophiles** [Nukesor/pueue#288]
#### Describe the bug

The `development` branch is missing the `build_completions.sh` file. Because of this, it was not possible to build the package from the AUR https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=pueue-git ((it still using this script)

**Comment by Nukesor** [comment]
Thanks for the report, it seems that I forgot to adjust the AUR PKGBUILD.

The script was only a small wrapper around a few completion calls.
```
    mkdir -p ./utils/completions
    ./target/release/pueue completions bash ./utils/completions
    ./target/release/pueue completions fish ./utils/completions
    ./target/release/pueue completions zsh ./utils/completions
```

Aur script is now working again

**Comment by Mephistophiles** [comment]
Thanks!
