### ISSUE TITLE
[BUG] Where is config file? More clarity in error msg

### ISSUE THREAD

**Issue by noyez** [Nukesor/pueue#298]
#### Describe the bug

Need more clarity in error message. I just upgraded from 1.x to 2.x, started the daemon. 

    16:57:06 [ERROR] Please delete the 'daemon.groups' section from your config file

But where is the config file? I did eventually find it, and it can be found via `pueue -vv`. But it wasn't at all obvious where my config file was. 

Thanks!

**Comment by Nukesor** [comment]
This is a good compromise. I like it :+1:

**Comment by Nukesor** [comment]
Closed via f09f21df7eaeb3dbffd1c37df48085d8852e9a6b
