### ISSUE TITLE
pueued exits when terminal is closed on Windows

### ISSUE THREAD

**Issue by CheneyWong** [Nukesor/pueue#300]
Pueue daemon 2.0.1
os ：Microsoft Windows 10

#### Describe the bug
1. 
open terminal
run `pueued -d`
return `Pueued is now running in the background`

2.
open another  terminal
run `pueue status`
it works

3.
close the first terminal,run in the second terminal
run `pueue status`
return 
```
Error: Failed to initialize client.
Caused by:
    0: Failed to initialize stream.
    1: Failed to connect to the daemon on 127.0.0.1:6924. Did you start it?
```

**Comment by Nukesor** [comment]
I will probably need some help with this, as I no longer own a Windows machine.

In Linux `pueued -d` simply starts a new process and forks into the background.
This works also when closing the terminal.

I assume that in Windows, that process is spawned as a subprocess, which is still attached to your current terminal.

I'll add the `help wanted` tag, as this is something I'm unable to do myself.

**Comment by Nukesor** [comment]
@CheneyWong Would you be willing to start working on this?
