### ISSUE TITLE
Suggestion: Add option to peueue follow to follow both stdout and stdin at the same time

### ISSUE THREAD

**Issue by sbrl** [Nukesor/pueue#306]
#### Is your feature request related to a problem?

When  task is running, I often want to follow both stdout *and* stderr at the same time to check on it's progress.

#### Describe the solution you'd like

I suggest a new argument to `pueue follow` is added that includes stderr in the output generated, rather than displays stderr instead of stdout.

#### Describe alternatives you've considered

I can do `pueue follow & pueue follow -e`, but this is more to type and leaves a background process behind you have to kill.

**Comment by Nukesor** [comment]
Which version are you using?

Pueue v2 merged both stdout and stderr into a single stream.

**Comment by Nukesor** [comment]
ping @sbrl

**Comment by sbrl** [comment]
Ahhhh I see - I'm still  using `Pueue client 1.0.4`.  Oops! I didn't even realise there was an update available haha - sorry about that :sweat_smile:
