### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by roland-rollo** [Nukesor/pueue#307]
#### Is your feature request related to a problem?

I am a visual learner and a large one makes it easier for me to look at an appropriately colored result. I have different colorings for the app set up, and Pueue shows everything as white text. Would it be possible for Pueue to respect the coloring of the text, that specific app use for them?

#### Describe the solution you'd like

Pueue used the coloring that the app uses, just as it shows up in the console without using Pueue.

#### Describe alternatives you've considered

O my God. Umm. If Pueue could not color the results / processes as it is in the terminal, then have some of his ability to color the syntax?

**Comment by Nukesor** [comment]
I'm not quite sure that I understand what you mean.

Which part of the app do you talk about?
The `status` output? `log` output?

Which setup do you use and what's this `app` you're referencing?

**Comment by Nukesor** [comment]
Closed due to inactivity.
