### ISSUE TITLE
[BUG] pueued fails to start after unclean shutdown

### ISSUE THREAD

**Issue by sbrl** [Nukesor/pueue#311]
#### Describe the bug

If my system suffers an unclean shutdown, upon reboot pueued fails to start.

#### Steps to reproduce the bug

1. Force reset the system pueued is running on
2. Power it on again
3. Observe that pueued does not start

#### Expected behavior

pueued checks the PID file and sees that either 1 of three things is true:

1. Another pueued instance is already running
2. A different process is running with the same PID
3. No process is running with the PID in question

In case 1, then I expect it to crash, but in cases  and 3 I do not expect pueued to crash here.

#### Logs/Output

```
May 31 01:34:11 pueued[833]: Error: Failed to create pid file.
May 31 01:34:11 pueued[833]: Caused by:
May 31 01:34:11 pueued[833]:     Pid file already exists and another daemon seems to be running.
May 31 01:34:11 pueued[833]:     Please stop the daemon beforehand or delete the file manually: "/home/sbrl/.local/share/pueue/pueue.pid"
May 31 01:34:11 systemd[1]: pueued.service: Main process exited, code=exited, status=1/FAILURE
May 31 01:34:11 systemd[1]: pueued.service: Failed with result 'exit-code'.
```

#### Additional context

- Operating System: Ubuntu Server 21.10; amd64
- Pueue version: `2.0.2`

**Comment by Nukesor** [comment]
This is the same issue as https://github.com/Nukesor/pueue/issues/302

Upon restart, another long running process, snatched the process id, that was saved in the `pueue.pid`.

For this reason, the pid file is now located in the XDG runtime directory. As the runtime directory doesn't survive restarts (as it's a tmpfs), pueue won't find an existing pid on startup.

However, in your case, the runtime directory probably falls back to the shared directory (`~/.local/share/pueue`), as there's probably no $XDG_RUNTIME_DIR set.

**Comment by sbrl** [comment]
Thanks for fixing this!

> In your case however, pueue doesn't seem to detect the $XDG_RUNTIME_DIR variable

Ah, that may be because it isn't set haha
