### ISSUE TITLE
ABAQUS / PUEUE CONFIGURATION

### ISSUE THREAD

**Issue by Proteor** [Nukesor/pueue#314]
#### Is your feature request related to a problem?

How to configure Pueue / Abaqus to have a remote batch job queue in a windows 10 environment ?
See https://classes.engineering.wustl.edu/2009/spring/mase5513/abaqus/docs/v6.6/books/usi/default.htm?startat=pt03ch18s06hlb04.html

#### Describe the solution you'd like

A step by step guide to configure Pueue and Abaqus batch job queue

#### Additional context

Add any other context, log output or screenshots about the feature request here.

**Comment by Nukesor** [comment]
I'm not exactly sure what you expect me to do here?

Docs on how to configure Pueue are available in the wiki and the readme. Abaqus is another project that isn't related to Pueue.

I'm closing as `unrelated`.
