### ISSUE TITLE
Add --color switch to control use of colours

### ISSUE THREAD

**Issue by mjpieters** [Nukesor/pueue#318]
#### Is your feature request related to a problem?

Currently, pueue uses `stdout().istty()` to determine when to use colours in the output. However, there are use-cases for outputting colour even if not connected directly to a TTY; e.g. when using `less` with the `-R / --RAW-CONTROL-CHARS` switch, or `watch` with the `-c/--color` switch, which usually then pass on the output to a TTY.

#### Describe the solution you'd like

Many CLI programs let you control when they use colours with a `--color` switch; e.g. `ls` has `--color=never`, `--color=always` and `--color=auto`; the current behaviour of `pueue` is akin to `--color=auto` (with a few exceptions that are always using colours, probably a bug).

Please add such a switch to pueue too!

#### Describe alternatives you've considered

Not using `watch` and baking up my own `while :; do pueue status; sleep 2; printf "\033[2J\033[1;1H"; done` loop, which has an annoying flicker as the screen is redrawn entirely (`watch --color pueue` is much, much smoother).

**Comment by Nukesor** [comment]
Closed via #320
