### ISSUE TITLE
Better fuzzy integration

### ISSUE THREAD

**Issue by avently** [Nukesor/pueue#329]
#### Describe the solution you'd like

Hello. I wrote a code that uses `fzf` with your application. From my point of view it's better than in the wiki here: https://github.com/Nukesor/pueue/wiki/Miscellaneous#interactive-fuzzy-finder

The advantages of using it is:
- it uses fzf keybindings feature (ctrl+k to kill, ctrl+s to start, ctrl+r to restart, ctrl+p to pause, ctrl+l to view log in `less`)
- autoupdates the list when keybindings were invoked (so after start/restart/pause/kill called the view refreshes with actual data)
- it is shorter
- no need to create and import additional files
- it uses dividers that are more understandable to humans
- it makes a substring from the end of command or file if they are too long
- it pads `id` of a task < 10 with one more space. For example, the task id was `0` will become ` _0` (space instead of `_`). Makes displaying line consistent up to 99. I don't need more than that, but if somebody needs he can make this padding `__0` to up to 999
- it uses `bat` with colors, with lines, with `log` file format specified. Can be easily replaced with `head -n 200`, for example.

Dependencies: jq, fzf, bat (optional)

So if you want this to be added to the wiki as an alternative (or maybe as a replacement) to the previous code I can do that.

The code is:
```bash
pf() {
  set -f
  local PUEUE_TASKS="pueue status --json | jq -c '.tasks' | jq -r '.[] | \"\(.id | tostring | (\" \" * (2 - length)) + .) | \(.group) | \(.path[-15:]) | \(.status) | \(.command[-15:]) | \(.start[:19])\"'"
  local header="p:pause | s:start | r:restart | k:kill | l:log | f:reload"

local bind="\
ctrl-p:execute-silent(echo {} | cut -d'|' -f1 | xargs pueue pause > /dev/null)+reload^$PUEUE_TASKS^,\
ctrl-s:execute-silent(echo {} | cut -d'|' -f1 | xargs pueue start > /dev/null)+reload^$PUEUE_TASKS^,\
ctrl-r:execute-silent(echo {} | cut -d'|' -f1 | xargs pueue restart -ik > /dev/null)+reload^$PUEUE_TASKS^,\
ctrl-k:execute-silent(echo {} | cut -d'|' -f1 | xargs pueue kill > /dev/null)+reload^$PUEUE_TASKS^,\
ctrl-l:execute-silent(echo {} | cut -d'|' -f1 | xargs pueue log | less > /dev/tty),\
ctrl-f:reload^$PUEUE_TASKS^\
"

  echo $PUEUE_TASKS | sh | fzf --header "${header}" -m \
    --preview="echo {} | cut -d'|' -f1 | xargs pueue log | bat -l log --style=rule,numbers --color=always -r ':200'" \
    --bind="$bind"
  set +f
}
```

**Comment by Nukesor** [comment]
To be honest, I didn't write the fuzzy integration and I'm not even using it (yet) :D

This was a contribution by @nothingnesses so he's probably most qualitified to review and discuss your proposal :)

**Comment by Nukesor** [comment]
If @nothingnesses isn't available, I'll try to go through both solutions soon :) 

We're currently having some great weather in Germany, so this might take a bit of time ;D

**Comment by Nukesor** [comment]
I like it!

It has colors, a better structure and the code is significantly shorter/easier to understand :) 
Feel free replace the solution in the wiki with your implementation!

Thanks again for your contribution :+1:

**Comment by avently** [comment]
oh, sorry, will do ASAP

**Comment by Nukesor** [comment]
Don't worry :D
I just walked through my projects and did a bit of project management, so I have a better overview of what needs to be done ;)

**Comment by avently** [comment]
Ok, found that in bash it didn't work. Fixed the issue, tested with dash, bash, zsh. Works good. Let me know if there are any problems with it now or in the future, I'll look.

**Comment by Nukesor** [comment]
Awesome! Thanks for your contribution :)

I'll probably go ahead and integrate this into my workflow as well. It looks much more polished than the old wrapper :)
