### ISSUE TITLE
[BUG] `pueue log` is incomplete: missing lines from start

### ISSUE THREAD

**Issue by chipbuster** [Nukesor/pueue#338]
#### Describe the bug

The output of `pueue log` is missing several lines from the beginning. As of right now, I can only  reproduce this with julia-based commands, which I've noticed often exhibit heavy compilation delays and unusual stream behaviors.

#### Steps to reproduce the bug

1. `pueue add -- julia non_existent_file.jl`
2. Run `pueue log` to see the log: a few lines will be missing from the top.

Missing lines are also missing from `pueue log <n> --json`.

#### Expected behavior

Should capture all the contents of stderr.

#### Logs/Output

Running a non-existent test file with julia:

```
$ julia test.jl
ERROR: SystemError: opening file "/home/chipbuster/tmp/test.jl": No such file or directory
Stacktrace:
  [1] systemerror(p::String, errno::Int32; extrainfo::Nothing)
    @ Base ./error.jl:174
  [2] #systemerror#68
    @ ./error.jl:173 [inlined]
  [3] systemerror
    @ ./error.jl:173 [inlined]
  [4] open(fname::String; lock::Bool, read::Nothing, write::Nothing, create::Nothing, truncate::Nothing, append::Nothing)
    @ Base ./iostream.jl:293
  [5] open
    @ ./iostream.jl:282 [inlined]
  [6] open(f::Base.var"#364#365"{String}, args::String; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Base ./io.jl:328
  [7] open
    @ ./io.jl:328 [inlined]
  [8] read
    @ ./io.jl:436 [inlined]
  [9] _include(mapexpr::Function, mod::Module, _path::String)
    @ Base ./loading.jl:1249
 [10] include(mod::Module, _path::String)
    @ Base ./Base.jl:418
 [11] exec_options(opts::Base.JLOptions)
    @ Base ./client.jl:292
 [12] _start()
    @ Base ./client.jl:495
```

Output of `pueue log` for the same command in pueue:

```
┌─────────────────────────────────────┐
│ Task 25:    failed with exit code 1 │
└─────────────────────────────────────┘
Command: julia test.jl
   Path: /home/chipbuster/tmp
  Start: Wed, 27 Jul 2022 21:37:15 -0500
    End: Wed, 27 Jul 2022 21:37:17 -0500

output:
    @ ./iostream.jl:282 [inlined]
  [6] open(f::Base.var"#364#365"{String}, args::String; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Base ./io.jl:328
  [7] open
    @ ./io.jl:328 [inlined]
  [8] read
    @ ./io.jl:436 [inlined]
  [9] _include(mapexpr::Function, mod::Module, _path::String)
    @ Base ./loading.jl:1249
 [10] include(mod::Module, _path::String)
    @ Base ./Base.jl:418
 [11] exec_options(opts::Base.JLOptions)
    @ Base ./client.jl:292
 [12] _start()
    @ Base ./client.jl:495
```

The output is the same, but it's missing the first ~10 lines.

#### Additional context

- Operating System: Arch Linux
- Pueue version: 2.1.0

Unfortunately, I don't have the time to grab more information at the moment, but if you're unable to repro, I may have time this weekend to dig further.

**Comment by Nukesor** [comment]
```
[nuke:~] 130! pueue log -h
pueue-log
Display the log output of finished tasks. Only the last few lines will be shown by default. If you
want to "follow" the output of a task, please use the "follow" subcommand

USAGE:
    pueue log [OPTIONS] [TASK_IDS]...

ARGS:
    <TASK_IDS>...    View the task output of these specific tasks

OPTIONS:
    -f, --full             Show the whole output. This is the default if only a single task is being
                           looked at
    -h, --help             Print help information
    -j, --json             Print the resulting tasks and output as json. By default only the last
                           lines will be returned unless --full is provided. Take care, as the json
                           cannot be streamed! If your logs are really huge, using --full can use
                           all of your machine's RAM
    -l, --lines <LINES>    Only print the last X lines of each task's output. This is done by
                           default if you're looking at multiple tasks
```

**Comment by Nukesor** [comment]
You should always see all lines, if you look at one specific task via `pueue log 25` or if you run `pueue log -f`

**Comment by Nukesor** [comment]
You're actually right though. The behavior of `pueue log` for looking at a single task has been streamlined.
I have to update the docs for the `--full` flag, as this isn't the default for single tasks any longer.

The reasoning behind this:

1. When looking at tasks, showing the full log is simply too much. In most cases, the user wants to see multiple tasks and additional task info, so it's a bad UX decision to have them scrolling around like crazy. That's the 99% usecase. If they want to see everything, just add `-f` for the full log.
2. There were several reports of users crashing their machines when using `--json`, as the logs they loaded were simply too big.
    JSON cannot be streamed, so users have to make sure that they have enough RAM for their log output themselves.

**Comment by Nukesor** [comment]
Ping  @chipbuster

**Comment by chipbuster** [comment]
@Nukesor Thanks, this makes sense.

I think something that might have helped me is if the log indicated that it had been truncated, e.g "Output (hiding N earlier lines)" or something of that nature. I understand if adding it right now would be too much hassle.

**Comment by Nukesor** [comment]
True. That would probably be a good idea :)

I would only do this for the the "normal" output though. I don't think it should be included in the json output.

**Comment by chipbuster** [comment]
Agreed, JSON should probably be faithful to the original.

**Comment by Nukesor** [comment]
An alternative would be to have a different (buffered) streaming mechanism when showing the last `N` lines, but this would result in quite a bit of additional coding work and complexity.

It would be good if we could keep the complexity on this low, as it the whole log streaming logic already is pretty complex.

**Comment by chipbuster** [comment]
> It would be good if we could keep the complexity low, as it the whole log streaming logic already is pretty complex.

Yeah, I don't think adding a new streaming mechanism just for this would be a good use of effort.

One incredibly hacky technique would be to have the daemon emit a <start-of-stream> marker if if tracks to the start of the stream while doing the truncation, then have the client look for that marker before deciding whether to omit the truncation message. Of course, if the program is putting binary nonsense into stdout, this may give false positives.

Perhaps a simple solution would just be to say something like "output may have been truncated"? It doesn't feel like great UX, but if the client doesn't know whether that's happened or not, maybe that's the best message you can give.

**Comment by Nukesor** [comment]
That was a great idea! I indeed already had a branch where I tracked whether we started to the start of the file, all I had to do was return a boolean and fast-forward that to the client.

The client uses the same seeking logic when reading local logs, so this wasn't hard to do either.

This feature is now implemented and integration-tested in https://github.com/Nukesor/pueue/pull/341
It would be great if you could go ahead and give this a spin :)  

```sh
cd /tmp
git clone git@github.com:Nukesor/pueue
cd pueue
git switch platform_specific_module_cleanup
cargo install --path . --locked
```

**Comment by chipbuster** [comment]
Looks great on my machine. Thanks so much!
