### ISSUE TITLE
[BUG] Windows path for pueue_aliases.yml differs from Wiki entry

### ISSUE THREAD

**Issue by jonasw234** [Nukesor/pueue#339]
#### Describe the bug

According to the [Wiki](https://github.com/Nukesor/pueue/wiki/Miscellaneous#aliases) to use aliases you need to

>  put a `pueue_aliases.yml` besides your `pueue.yml`

which, again, according to the [Wiki](https://github.com/Nukesor/pueue/wiki/Configuration) should be

> Windows: `%APPDATA%\Local\pueue\pueue.yml`

(small mistake here: On modern Windows systems `%APPDATA%` refers to the `AppData\Roaming` directory directly, the path to `AppData\Local` is stored in `%LOCALAPPDATA%`)  
so the expected file path would be `%LOCALAPPDATA%\pueue\pueue_aliases.yml`. However, the correct path from where the file is loaded is `%APPDATA%\pueue\pueue_aliases.yml` (i.e. `C:\Users\User\AppData\Roaming` instead of `C:\Users\User\AppData\Local`).

#### Steps to reproduce the bug

1. Create the file `%LOCALAPPDATA%\pueue\pueue_aliases.yml` with aliases
2. Try to use your alias
3. It doesn’t work

#### Expected behavior

The aliases should be loaded and used.

#### Additional context

- Operating System: `Microsoft Windows [Version 10.0.19042.1826]`
- Pueue version. Can be seen at the top of `pueue -h` output: `Pueue client 2.1.0`

**Comment by Nukesor** [comment]
This changed in v2, but It seems like I forgot to update the wiki to the new paths!

Pueue now uses the `dirs` crate for this stuff:
https://docs.rs/dirs/latest/dirs/fn.config_dir.html

The windows config path seems to now be `C:\Users\Alice\AppData\Roaming\pueue`
The windows cache folder is `C:\Users\Alice\AppData\Local\pueue`

Could you go ahead and update the wiki :)
I don't own a Windows machine myself, so I really depend on my Windows community to find and fix these issues :sweat_smile:

**Comment by jonasw234** [comment]
Got it, thanks :) I was unsure if this was an intended change, thanks for clearing this up!
I just updated the wiki.
