### ISSUE TITLE
Idea: add a switch to specify signal for pueue kill

### ISSUE THREAD

**Issue by mgoral** [Nukesor/pueue#34]
It's not always desirable to kill via SIGKILL (-9). Some listen for different signals which communicate them different things (think e.g. about dnsmasq, for which `pkill -HUP dnsmasq` would clear DNS cache).

So I'd say to add `-s` switch to specify a signal and that switch should accept both numeral and literal signal names, just like a regular kill command:

```
$ pueue kill -k 1 -s 2
$ pueue kill -k 1 -s INT
$ pueue kill -k 1 -s SIGINT
$ pueue kill -k 1 -s int
$ pueue kill -k 1 -s sigint
```

In my opinion by default it should be set to `TERM`, just like for a kill command.

**Comment by Nukesor** [comment]
Good Idea. :+1: 
I'll take a further look into the default behaviour of `kill` and make the `pueue kill` command more intuitive.
There will probably a full rewrite of the commandline interface anyway. This feature will probably be implemented afterwards.
There's a lot of stuff for me to look at and read right now.

**Comment by Nukesor** [comment]
I started working on this in #40

**Comment by Nukesor** [comment]
Hey @mgoral,
I'm nearly finished with this feature, but as I don't really use different singals with `kill` that often, it would be great to know which signals should be supported by pueue in your opinion.
There are quite a few of them and I don't want to support every single one by now.
