### ISSUE TITLE
idea/feature-request: cost/weighting for tasks for better parallelism control

### ISSUE THREAD

**Issue by colemickens** [Nukesor/pueue#340]
#### Is your feature request related to a problem?

I have a build process and I'd like to start using pueue to queue up parallelizable jobs. However, due to the nature of what I'm doing, many of these builds wind up occurring remotely.

#### Describe the solution you'd like

I'd like to be able to add jobs to pueue with a "weight" and then a "max capacity" option to specify how aggressively to parallelize jobs. This would allow me to queue up remote builds with a weight of "0" and local builds with some other value.

#### Describe alternatives you've considered

Alternatives:
- a binary toggle might be simpler, and would probably be sufficient for this specific use-case anyway.

#### Additional context

Questions:
- does/should pueue execute jobs out of order to utilize the max capacity? (since they *can* run in parallel, it seems the user must already be somewhat cautious around ordering assumptions)

**Comment by Nukesor** [comment]
> does/should pueue execute jobs out of order to utilize the max capacity? (since they can run in parallel, it seems the user must already be somewhat cautious around ordering assumptions)
Right now, there's no weighting at all. All jobs are equally weighted and take one slot in the current group's pool.
Tasks are processed sequentially, unless they have a dependency or are stashed for later execution.

There is a separate feature request for weighted tasks that wasn't created too long ago:
https://github.com/Nukesor/pueue/issues/325

This is a feature that would need to be, but we have to be careful about this, as this comes with its own scheduling problems. As you already pointed out, sequentiality might no longer be guaranteed, unless the user explicitly builds a dependency tree.

> I'd like to be able to add jobs to pueue with a "weight" and then a "max capacity" option to specify how aggressively to parallelize jobs. This would allow me to queue up remote builds with a weight of "0" and local builds with some other value.
However, if I understand your requirements correctly, this is something that shouldn't be modeled via weighting.
This is a scenario that can easily be solved via groups:
- Create a new group, e.g. `remote`
- Give the `remote` group a appropriate task pool ( or a very large if you don't care how many should run in parallel)
- Add local tasks to your default group
- Add all remote task to that group. If you have any dependencies between those tasks, just add those tasks as a dependency. Dependencies can span across several groups.


You would be able to model the `remote` and `local` representation of tasks with that approach.
The weighting for local tasks however might be implemented in the other referenced issue.

**Comment by colemickens** [comment]
Ah, I did look but didn't see #325. Between that and your very comprehensive answer (teaching me about groups!), I think we can close this. I appreciate the detailed, fantastic answer, and am excited that my use-case is seemingly already accommodated. 

Thanks very much for the help and working on `pueue`!
