### ISSUE TITLE
[Feature] Support windows service setup for `pueued`

### ISSUE THREAD

**Issue by simonsan** [Nukesor/pueue#344]
**First, I was unsure if this would be a bug report or a feature request.**

But as pueued says in the help text:
>     -d, --daemonize           If this flag is set, the daemon will start and fork itself into the
>                               background. Closing the terminal won't kill the daemon any longer.
>                               This should be avoided and rather be properly done using a service
>                               manager

It should be easy to set up a service.

## Describe the bug

Created Windows services time out, because (this is what I assume) `pueued` misses handling of Windows service events.

## Steps to reproduce the bug

1. Trying to create a service on Windows 10. I did this the following way, which I found most easy within Powershell:

```pwsh
$params = @{
    Name = "pueued"
    BinaryPathName = "C:\Users\dailyuse\scoop\apps\pueue\current\pueued.exe"
    DisplayName = "Pueue Service"
    StartupType = "Automatic"
    Description = "Service to manage pueue task management tool"
}

New-Service @params
```

Et voilà, this should be it.

2. But when starting the service with `Start-Service pueued` it times out.
3. I assume that is because `pueued` doesn't handle the Windows service events.

## Expected behaviour

`pueued` should be easy to set up as a service.

## Logs/Output

```pwsh
Start-Service: Service 'Pueue Service (pueued)' cannot be started due to the following error: Cannot start service 'pueued' on computer '.'.
```

Which is most likely a related error to
```pwsh
Error 1053: The Service did not respond to the start or control request in a timely fashion
```

Because I see it timing out in `services.msc`.

## Additional context

- Windows 10 Pro 21H2 19044.1865
- pueue 2.1.0

___

## Useful crates

- [Handling service events](https://crates.io/crates/windows-service)
- [Interface towards working with service management platforms (for e.g., installing a service on first run)](https://crates.io/crates/service-manager)

**Comment by Nukesor** [comment]
This is most definitely because running pueued as a service in Windows environments hasn't been built yet!

As I'm only owning a Linux machine, I rely on the community to implement Windows/Mac specific logic and find such issues :)

It would be great, if you could take a look on how to implement this! Especially since you seem to be quite knowleadable about this topic and already did some research on how to do this :).

**Comment by AntoniosBarotsis** [comment]
I'm not sure if this is something different but I've been using `pueued &` to make this work on powershell. Does that work for you?

**Comment by Nukesor** [comment]
I think the idea is to, for instance, start pueued on startup as a windows system service.

The same is achieved via the [systemd user service](https://github.com/Nukesor/pueue/blob/main/utils/pueued.service) on linux systems that run systemd.

**Comment by AntoniosBarotsis** [comment]
I'm not too sure if this fits your needs but could you for instance use something like [Task scheduler](https://learn.microsoft.com/en-us/windows/win32/taskschd/starting-an-executable-on-system-boot)? 

There's a way for you to define a task to run on-boot by making a simple XML file (see [here](https://learn.microsoft.com/en-us/windows/win32/taskschd/boot-trigger-example--xml-)). There's  a few other ways listed but this seems to be the easiest.

**Comment by kitzbergerg** [comment]
You can do the following on Windows:

Press Windows+R and type `shell:startup`. Create `pueue-service.vbs` with content

```
Set WshShell = CreateObject("WScript.Shell")
WshShell.Run chr(34) & "pueued" & Chr(34), 0
Set WshShell = Nothing
```

Disclaimer: I have no idea about vbs, the script is just something I copied from somewhere.

**Comment by papanito** [comment]
You can also add a shortcut into `%AppData%\Roaming\Microsoft\Windows\Start Menu\Programs\Startup`  and `target`= `path-to-pueued -vv`

Sure this will open a command line window in the foreground, but you can start it minimized.

Not ideal but works for me.

**Comment by papanito** [comment]
> I'm not sure if this is something different but I've been using `pueued &` to make this work on powershell. Does that work for you?

adding `&` just immediately returns `The service did not respond to the start or control request in a timely fashion.`

**Comment by YDX-2147483647** [comment]
Hi! As this issue has been opened for a while, I add a section in https://github.com/Nukesor/pueue/wiki/Common-Pitfalls-and-Debugging. If anyone resolves #344 or #442, please consider update the wiki.

> ## Windows quirks
>
> Due design differences between Windows and Linux, `pueued --daemonize` may not work as expected on Windows, including but not limited to the following quirks.
>
> - The daemon may still exit if you close the terminal.
> - If `pueue follow` in the same shell where `pueued` is spawned, then <kbd>Ctrl</kbd>+<kbd>C</kbd> may also shut down the daemon.
>
> There are discussions / workarounds in [#344](https://github.com/Nukesor/pueue/issues/344), and implementation is welcomed.

**Comment by melMass** [comment]
I was about to open a similar issue to add this info to the quickstart guide. 

This is the path I tried (mostly to give more info to Nukesor):

# NONE OF THESE ARE WORKING

## Using a windows service

- Create a service:
  ```sh
  gsudo sc.exe create "Pueue Daemon" binPath= "C:/Users/User/.cargo/bin/pueued.exe"
  ```
  *(instead of `gsudo` you can just open a terminal with admin rights)*

- Setup the service start option:
  ```sh
  gsudo sc config "Pueue Daemon" start= auto
  gsudo sc start "Pueue Daemon" 
  ```
- Upon start you will get a service timeout (1053), you can try to pass `-d` to the flag which will still error out but actually spawn the daemon, BUT the client will fail to connect because of TLS:
  ```sh
  Error: Failed to initialize client.

  Caused by:
      0: Failed to initialize stream.
      1: Failed to initialize tls invalid peer certificate: BadSignature.
  ```
  **more info here:** https://github.com/denoland/deno/issues/21169 & https://github.com/rustls/rustls/issues/1367
  
 ## Using [Shawl](https://github.com/mtkennerly/shawl)
 
 - Install shawl and the service and run it:
   ```sh
   cargo install --locked shawl
   gsudo shawl add --name pueue_daemon -- C:/Users/User/.cargo/bin/pueued.exe
   gsudo sc start pueue_daemon
   ```
   This removes the timeout error and the service now run fine but we have the same TLS issue on the client.
   
---

If I get this right the solution would be to have a custom `main` on windows following this signature: `fn(argc: u32, argv: *mut *mut u16)` for instance using [windows-service-rs](https://github.com/mullvad/windows-service-rs)

**Comment by graphixillusion** [comment]
Is there any news about this?

**Comment by Nukesor** [comment]
Nope, to my knowledge, nobody started working on this.

**Comment by MolotovCherry** [comment]
I don't have time to implement this right now, but I just wanted to drop in for others and say that this is fairly trivial to do using the [`windows-service`](https://crates.io/crates/windows-service) crate

**Comment by Nukesor** [comment]
Hmm.

In general, I would like Pueue to be integrated into the native OS's service system.
Changing the `-d` behavior would:
- force all windows users to always use windows' native system service
- Be a pretty hefty breaking change, as it would break currently existing "daemon" setups.

So I would go for the `--service` flag. This would allow for a clean introduction of this feature without any backwards incompatible changes :) 

Thanks for the research, much appreciated. Maybe we'll finally be able to close this ticket after a few years :D

**Comment by MolotovCherry** [comment]
> Hmm.
> 
> In general, I would like Pueue to be integrated into the native OS's service system. Changing the `-d` behavior would:
> 
> * force all windows users to always use windows' native system service
> * Be a pretty hefty breaking change, as it would break currently existing "daemon" setups.
> 

> Thanks for the research, much appreciated. Maybe we'll finally be able to close this ticket after a few years :D

Actually, this will be pretty easy for me to knock out in a few hours 😄 

> > So I would go for the `--service` flag. This would allow for a clean introduction of this feature without any backwards incompatible changes :)

Got it. I'll do it this way then. Would you like the flag hidden or shown in the help with appropriate description? It's internal anyways, so hiding it has no downsides.

**Comment by Nukesor** [comment]
I would go ahead and show the flag with a appropriate description. As long as it's clear from the description that it shouldn't be consumed by the user, I'm fine with it being visible :)

**Comment by MolotovCherry** [comment]
@Nukesor Do you have a discord or something I can talk to you more easily while I make this?

**Comment by MolotovCherry** [comment]
The windows service is done now and works great (see #567). I would appreciate it if others would do some testing however, just as a final check.

**Comment by Nukesor** [comment]
Will review soonish :) Currently on holiday for the next two weeks ^^

**Comment by simonsan** [comment]
Wow, @MolotovCherry thank you so much for taking care of this. And have a great, enjoyable and recovering holiday @Nukesor! :)

**Comment by Nukesor** [comment]
Implemented by @MolotovCherry in #567  :)

**Comment by vulns-are-features-too** [comment]
Big thanks you @MolotovCherry  and @Nukesor for getting this to work on Windows :D

Can you please also update the wiki with instructions for using this? I'd love to not have to manually start the daemon.

https://github.com/Nukesor/pueue/wiki/Get-started#start-the-daemon
https://github.com/Nukesor/pueue/wiki/Common-Pitfalls-and-Debugging

**Comment by Nukesor** [comment]
@vulns-are-features-too Feel free to update the wiki yourself :) 

I have no idea how that stuff works and the wiki is editable by everyone :D

**Comment by MolotovCherry** [comment]
@vulns-are-features-too I'll update it soon

**Comment by MolotovCherry** [comment]
@vulns-are-features-too 
The service section now exists here. Enjoy pueued!
https://github.com/Nukesor/pueue/wiki/Get-started#windows

**Comment by papanito** [comment]
U even made it in the German IT news ;-)
https://www.heise.de/news/pueue-4-0-0-ist-da-Task-Management-Tool-verwaltet-Aufgaben-ohne-Verzoegerungen-10310804.html
