### ISSUE TITLE
Status query syntax

### ISSUE THREAD

**Issue by Nukesor** [Nukesor/pueue#350]
I started implementing the `pueue status` query on this branch: https://github.com/Nukesor/pueue/tree/filter-status
It's still very much work-in-progress, but it's starting to shape into something usable.
The main reason why I'm writing this ticket is that I want some feedback on the current syntax.

**A small upfront disclaimer:**
The first draft of the syntax will be experimantal. If it get's released, there'll be a big note on top of it that the syntax might become subject to change and that it shouldn't be considered stable!

Furthermore, I don't plan to make the syntax feature-complete from the get-go. The idea is to implement the basic features and continue working on it with real-world feedback and usecases.

Okay, now that that's out of the way here's the current syntax.

There're currently three sections:

## Column selection:
This is a basic filter on which columns should be visible
- [x] `columns=id,status,start,end`

## Filters
This is where it get's a bit more complex.
For now a few filters are planned:

- [x] `label [=|!=] string`: Filter for a specific label
- [x] `[start|end|enqueue_at] [=|!=|<|>] [YYYY-MM-DD | YYYY-MM-DD hh:mm | hh:mm]` Filter any of the three date related fields.
- [x] `status [=|!=] [queued|stashed|running|paused|done|failed]` Filter tasks based on their status

## Ordering

- [x] `order_by [any_column] = [asc|desc]` A simple ordering depending on a column and a direction.

## Limit

- [x] `[first|last] [count]` Only show the `count` first or last tasks.

# Complete query
A complete query has this structure:
`[column_selection]? [filter]*? [order]? [limit]?`

Examples:
- `columns=id,status,command,end label=special start>2022-09-01 order_by status desc`
- `label=special`
- `start>10:30 end<18:00 status=success first 10`

# Questions:
- What do you think of this syntax?
- Is there any fundamental missing feature?
- Would this cover your 80% usecase?

# Further Additions to the syntax

- [ ] A "contains" filter for labels. The operator could be a `%=`

**Comment by Nukesor** [comment]
Ping @codekoala @d33tah @kjhoerr @stranger-danger-zamu

**Comment by Nukesor** [comment]
I just finished the implementation of all features I deemed "essential".

It would be great if you guys could give it a test run based on your common scenarios :)


```
cd /tmp
git clone git@github.com:Nukesor/pueue
cd pueue
git checkout filter-status
cargo install --path . --locked
```

**Comment by codekoala** [comment]
@Nukesor this looks fantastic! Thank you for implementing this feature. I will give it a spin this coming week and report back with any feedback.

**Comment by Nukesor** [comment]
Ah damn. I forgot about pest needing a bit of special handling.

The branch currently uses the latest `pest` master as I had to upstream a patch to get pest working with alternative project directory layouts. That patch hasn't been released yet though.

Your first compile will fail with something like this:
```
error: failed to run custom build command for `pest_meta v2.3.0 (https://github.com/pest-parser/pest#4fde90e5)`

Caused by:
  process didn't exit successfully: `/home/nuke/repos/tools/pueue/target/debug/build/pest_meta-78fd31208345b0f2/build-script-build` (exit status: 101)
  --- stdout
  rerun-if-changed=src/grammar.pest
  Bootstrapping `meta/src/grammar.rs`

  --- stderr
  thread 'main' panicked at 'Bootstrap failed because no bootstrap executable was found. Please run `cargo build --package pest_bootstrap` or `cargo bootstrap` and then try again.', /home/nuke/.cache/cargo/git/checkouts/pest-25f0f91498b61172/4fde90e/meta/build.rs:52:21
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  ```
  
Go to the `checkouts/pest-SOMEID/SOMEID/meta` path in that message and run `cargo boostrap`.

In my case:
```
cd /home/nuke/.cache/cargo/git/checkouts/pest-25f0f91498b61172/4fde90e/meta
cargo boostrap
```

Building/installing pueue should work just fine now :)

**Comment by mjpieters** [comment]
I like this idea! I'd try to keep this simple; the `--json` output gives scripters enough power to implement more complex behaviour.

I do wonder if there is a good use-case for substring matching, at least for labels. E.g. for my current needs I have `[name]/[identifier]-[isodate]` strings that echo the destination of the download, and I use that information in my `jq` scripts to group by year or by name. A simple 'contains' test would do there, or if you want to go really fancy, support regex matching?

Another queue is labelled with the number of items to process (as the log only shows me what numbered files have been processed, so I can compare label and current file number to see how far along the job is), so a stretch goal would be for `<`, `<=`, `>`, and `>=` to work with labels too. If need be, just make that use lexicographical ordering, and I'll just zero-pad the labels (`images: 123` is more than `images: 042`). This does feel a little bit like it would push the syntax into becoming complex however.

**Comment by Nukesor** [comment]
I agree that the syntax should be kept rather simple :) This is also the reason why I didn't introduce the `OR` keyword yet, as this make things so much more complex. Let's decide whether something is feasible per use case.

Adding `>|=>|<|<=` for lexical ordering in labels shouldn't be too much of a problem as this the hard comparison stuff is included in Rust.

I'm also not against a `contains` operator. Do you know of any intuitive symbols for this kind of operation? I found `~`, but I also associate this with the `NOT` operator :D.

Regarding regex support, I'm not generally against it, but I would like to keep it simple for the first iteration of the syntax.

**Comment by mjpieters** [comment]
> I'm also not against a `contains` operator. Do you know of any intuitive symbols for this kind of operation? I found `~`, but I also associate this with the `NOT` operator :D.

How shell friendly does it need to remain; more friendly than `find` operators, presumably ;-) `~` is, in my mind, also more of a REGEX operator (notably, AWK, but [also PostgreSQL](https://www.postgresql.org/docs/current/functions-matching.html#FUNCTIONS-POSIX-TABLE)). And in C and the many languages derived from it, `~` is a *bitwise* NOT operator. 

Looking at other contexts for similar use-cases I peeked at [CSS attribute selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors); `~=` there is reserved for matching a whole word in a white-space separated sequence of words, and `*=` is for substring matches. I was hoping for the latter here. Of course, `*` is a shell meta-character, so that's a downside.

I do like the idea of combining a symbol with `=` here`[symbol]=` or `=[symbol]`. PERL introduced `=~` for regexes, and that has been adopted widely (Ruby, Groovy, CSS uses the inverted combo, etc.).  And since you are emulating SQL here with the expression ordering, perhaps `%`, `%=` or `=%` would be a good spelling for a `contains` operator?

E.g.:

```
label%=2022-01-
```

would filter the output to only show items with January 2022 in the label.

**Comment by Nukesor** [comment]
> How shell friendly does it need to remain; more friendly than find operators, presumably ;-) 

The current operators `>` and `!` already aren't shell friendly at all :D.
Queries should pretty much always be enclosed in a quotes.

> I'd lean towards %= for intuitive reasons, I'll have to come up with better reasoning for why I like that better than =% or %..

I like `%=` quite a bit. A standalone `%` is rather confusing as it reminds of the modulo operator. `%=` however should be rather intuitive for people that know SQL and the `=` makes it clear that there's at least some kind of similarity check going on.

> *= is for substring matches. I was hoping for the latter here. Of course, * is a shell meta-character, so that's a downside.
`*` being a meta-character isn't much of a problem, as there already are a few of those in the current draft of the syntax.
But, to be honest, I don't really have any association with `*=`... Guess I don't do enough stuff CSS

**Comment by Nukesor** [comment]
I'll try to keep the base syntax as it is for now, further operators and filters will be added in follow-up PRs to keep the scope small.
The current PR already has 1500+ added lines regarding filters.

Everything should be rather well tested now, but I'll keep the PR open for another 1-2 weeks for people to test :)
