### ISSUE TITLE
FR: Edit labels

### ISSUE THREAD

**Issue by mjpieters** [Nukesor/pueue#354]
#### Is your feature request related to a problem?

My jobs are given labels, but, sometimes, I get the label wrong. I have scripts track items based on the label, so I do need to correct wrong labels, which currently means removing and recreating the job.

#### Describe the solution you'd like

Add a `-l, --label` option to `pueue edit`, to let you alter labels.

#### Describe alternatives you've considered

I currently use `pueue rm [TASK_ID]` to remove jobs with incorrect labels and recreate the task from scratch.

**Comment by Nukesor** [comment]
Sounds good to me :)

I would really like to refactor the `EditResponseMessage` while at it.
The code handling would be much cleaner, if more verbose, when using options:

```
#[derive(PartialEq, Eq, Clone, Debug, Deserialize, Serialize)]
pub struct EditResponseMessage {
    pub task_id: usize,
    pub command: String,
    pub path: PathBuf,
}
```

-> 

```
#[derive(PartialEq, Eq, Clone, Debug, Deserialize, Serialize)]
pub struct EditResponseMessage {
    pub task_id: usize,
    pub command: Option<String>,
    pub path: Option<PathBuf>,
    pub label: Option<String>
}
```

We might have to add this functionality to the `restart` subcommand as well, as this allows to edit stuff when restarting tasks as well. (I already refactored the `EditResponseMessage` to use `Option`s a few weeks back)

**Comment by Nukesor** [comment]
I think I'll tackle this task today

**Comment by Nukesor** [comment]
@mjpieters What do you think of the behavior that passing an empty string after editing removes the label?

This could be handled on the client-side after reading the file from the editor. The Daemon would then receive an `Option<Option<String>>` to indicate whether this is actually a change (first option) and whether the label has been removed or changed (second option)

**Comment by mjpieters** [comment]
Ohh, hadn't thought about removing the label. Yes, I'd say that leaving the label empty (after whitespace stripping?) means the label is being removed.

**Comment by Nukesor** [comment]
Perfect :)

I finished the refactoring + the new feature in the linked MR.
I took the time to streamline the `edit` subcommand and make it behave the same way as the `restart` editing.
-> You can now edit multiple properties without having to invoke the command multiple times.

**Comment by Nukesor** [comment]
FYI

I wrote another test for the deletion of labels and it turns out that `serde_cbor` doesn't properly encode `Option<Option<T>>`.
It condenses a `Some(None)` into a `None`.

While investigating this issue, I foud out that `serde_cbor` has been archived by its owner.
Current course of action:
- Checkout other libraries
- Investigate whether they have the needed feature set.
- Check whether they can be used as a drop-in replacement without breaking old versions
- In case this isn't possible, look for a hacky workaround. Maybe a `delete_label` flag.

**Comment by Nukesor** [comment]
`ciborium`, which seems like a good alternative, isn't capable of encoding `Option<Option<T>>` either.

Seems like we have to hack around via a `delete_label` flag :<
I might check whether `cbor` is supposed to support stuff like this or not. We might be able to patch it in case it is.
