### ISSUE TITLE
Inconsistency in passing a key

### ISSUE THREAD

**Issue by avernan** [Nukesor/pueue#36]
Hi,
I've noticed that some of the subcommands require the key to be passed as an argument, while others require a -k/--key option to specify a key. I suppose this is because some commands have a meaning even without a key?
Do you think it is a good idea to make them more uniform? I personally find this way to be slightly confusing.

**Comment by Nukesor** [comment]
Some keys are optional and optional keys should always be preceded by `--` or `-`.
Another possibility would be to create a dedicated `startall` command and require a key for `start`.
This would result in a lot of new commands `stopall`, `killall`, `pauseall` etc.
Generally this isn't a bad idea, especially as I'm thinking about rewriting the whole argparse stuff in docopts anway.
What do you think about the `all`-commands?

**Comment by avernan** [comment]
After a couple of days of usage this is much less of a problem for me.
I would still argue for a different way. I'm not really familiar with the python argument parser, but would it be possible to access the two possibilities without a flag?
Something like
    pueue kill
to kill all jobs, while
    pueue kill key
would kill the specified key.

Also, I find there is a conceptual difference between not giving a key to kill (i.e., kill all running) and not giving it to start/pause, which means start/pause the processing of the queue. So in a sense, one is a queue command, the other a "collective" command.

**Comment by Nukesor** [comment]
I'm currently implementing another approach, which will hopefully be even more convenient:
`pueue kill` will still kill everything.
`pueue kill $keys` Which kills specific processes, but keys can be a list of keys (` pueue kill 1 3 4 5`)
This behaviour will be changed for pretty much every command (`log`, `start`, `pause`, `restart`, etc.)
