### ISSUE TITLE
[BUG] client::wait::multiple_tasks is flakey

### ISSUE THREAD

**Issue by mjpieters** [Nukesor/pueue#377]
The output tested for by tests/client/wait.rs:multiple_tasks is not stable, but the different outputs are not an indication of failure.

#### Steps to reproduce the bug

Run the test in a loop with:

```sh
while cargo test --quiet \
    --test client_tests client::wait::multiple_tasks
do :; done
```

Left running long enough the test eventually fails. E.g. the log may have captured the brief state where the task was queued before being started:

```
Differences (-expected|+actual):
 New task 1 with status Queued
-Task 0 changed from Stashed to Running                                                                                  
+Task 0 changed from Stashed to Queued                                                                                   
+Task 0 changed from Queued to Running                                                                                   
 Task 0 succeeded with 0                                                                                                 
 Task 1 changed from Queued to Running                                                                                   
 Task 1 succeeded with 0
```

#### Expected behavior

Tests should be not fail intermittently without the system-under-test changing. The test should either account for the possible variations of the log lines or should be fixed to ensure that there is no chance of flaking.

**Comment by mjpieters** [comment]
FWIW, when I check out #376 and try to reproduce this I no longer can. I strongly suspect that my solution for #379 that fixed this specific issue too.

**Comment by Nukesor** [comment]
Awesome :D

Thanks for pushing all those MRs! I'm currently in the middle of a job/client transition and pretty occupied. Sorry if these reviews will take a little longer as usual. I'm planning to review your changes as soon as I'm back to having a few calm moments :sweat_smile: .

Thanks again for your contributions! I already skimmed through the MRs and I'm curious about nextest. I planned to test it at some point, but didn't get to it yet.

**Comment by mjpieters** [comment]
No worries! This is your project, take your time! :-)

I'll probably add one more PR, then leave it be for you to catch up.

**Comment by mjpieters** [comment]
With my PR merged, let's close this as I can no longer reproduce it.
