### ISSUE TITLE
[BUG] Some Vulnerability exist due to old dependent packages 

### ISSUE THREAD

**Issue by amiyamandal-dev** [Nukesor/pueue#383]
Hello, 
I've used this code in one of my projects, however an inspector-identified vulnerability is causing me problems. Older dependence is present on a number of the crates used in this project.

**Critical Vulnerability**
Impact In the affected version of this crate, the result of the race condition is that one or more tasks in the worker queue can be popped twice instead of other tasks that are forgotten and never popped. If tasks are allocated on the heap, this can cause double free and a memory leak. If not, this still can cause a logical bug. Crates using `Stealer::steal`, `Stealer::steal_batch`, or `Stealer::steal_batch_and_pop` are affected by this issue. ### Patches This has been fixed in crossbeam-deque 0.8.1 and 0.7.4. ### Credits This issue was reported and fixed by Maor Kleinberger. ### License This advisory is in the public domain.

[thread_local](https://crates.io/crates/thread_local) is a library which allow a separate copy of an object to be used for each thread. This allows for per-object thread-local storage, unlike the standard library's thread_local! macro which only allows static thread-local storage. Affected versions of this package are vulnerable to Memory Corruption via `{Iter, IterMut}::next` which uses a weaker memory ordering when loading values than what was required, exposing a potential data race when iterating over `ThreadLocal`'s values.

Impact The affected version of this crate incorrectly assumed that the alignment of `{i,u}64` was always the same as `Atomic{I,U}64`. However, the alignment of `{i,u}64` on a 32-bit target can be smaller than `Atomic{I,U}64`. This can cause the following problems: - Unaligned memory accesses - Data race Crates using `fetch_*` methods with `AtomicCell<{i,u}64>` are affected by this issue. 32-bit targets without `Atomic{I,U}64` and 64-bit targets are not affected by this issue. 32-bit targets with `Atomic{I,U}64` and `{i,u}64` have the same alignment are also not affected by this issue. The following is a complete list of the builtin targets that may be affected. (last update: nightly-2022-02-11) - armv7-apple-ios (tier 3) - armv7s-apple-ios (tier 3) - i386-apple-ios (tier 3) - i586-unknown-linux-gnu - i586-unknown-linux-musl - i686-apple-darwin (tier 3) - i686-linux-android - i686-unknown-freebsd - i686-unknown-haiku (tier 3) - i686-unknown-linux-gnu - i686-unknown-linux-musl - i686-unknown-netbsd

In Rust time crate from version 0.2.7 and before version 0.2.23, unix-like operating systems may segfault due to dereferencing a dangling pointer in specific circumstances. This requires the user to set any environment variable in a different thread than the affected functions. The affected functions are time::UtcOffset::local_offset_at, time::UtcOffset::try_local_offset_at, time::UtcOffset::current_local_offset, time::UtcOffset::try_current_local_offset, time::OffsetDateTime::now_local and time::OffsetDateTime::try_now_local. Non-Unix targets are unaffected. This includes Windows and wasm. The issue was introduced in version 0.2.7 and fixed in version 0.2.23.

**Comment by Nukesor** [comment]
As a workaround, you can just take the latest main/developmant branch as a patch for now.

We're currently in the last stretches of the next release, but it's a big one and took quite some time to build.

All dependencies are up-to-date over there and this shouldn't be a problem.

**Comment by Nukesor** [comment]
Closing, as I'll release the v3.0.0-rc.1 very soon.
