### ISSUE TITLE
Add option to start & follow a task in a single command

### ISSUE THREAD

**Issue by ChocolateOverflow** [Nukesor/pueue#388]
#### Is your feature request related to a problem?

I sometimes want to start a job and follow its output, both at the same time

#### Describe the solution you'd like

1. Add a `--follow` flag to the `start` command
2. Add a `--start` flag to the `follow` command

Doing either would allow be to start a task (queued or stashed) and follow its output at the same time, so I don't miss any of the output after starting it.

#### Describe alternatives you've considered

Just running the 2 commands separately works, but I'd have to either (1) run the 2 commands in 2 separate shells/terminals or (2) risk missing some of the starting output.

**Comment by Nukesor** [comment]
I see how this can be convenient, but what keeps you from doing a `pueue start 0 && pueue follow 0`.
Why do you need two different terminals for this task?

**Comment by ChocolateOverflow** [comment]
I was thinking the output might come out so fast that even `&&` might miss some of it, in which case I'd need to run `follow` before `start`.

**Comment by Nukesor** [comment]
pueue follow actually prints all of the output since the beginning of the log output, unless the `--lines` flag is provided.

**Comment by Nukesor** [comment]
Can this be closed :)?
