### ISSUE TITLE
Allow task naming

### ISSUE THREAD

**Issue by ClementNerma** [Nukesor/pueue#395]
#### Is your feature request related to a problem?

I currently have to manage some background jobs which must always be running. I frequently need to fetch some infos on it like its status (is it running or did it fail), and restart it if needed.

#### Describe the solution you'd like

Be able to give a name to each task (like a label, but which you could query when showing the status of the tasks).

#### Describe alternatives you've considered

Using labels, but this is tricky, kind of a hack, and you cannot perform a search "by label" in the tasks list.

**Comment by Nukesor** [comment]
Could you check out the v3.0.0 release candidate?

V3 has a simple query logic, which allows filtering by labels

**Comment by ClementNerma** [comment]
This seems to fix the problem! Thanks.
