### ISSUE TITLE
Enqueue all stashed tasks (in a group)

### ISSUE THREAD

**Issue by ChocolateOverflow** [Nukesor/pueue#396]
#### Is your feature request related to a problem?

I often stash tasks in a whole group to be started later. However, `enqueue` only takes individual task IDs which I need to manually specify or use something like `seq 0 10`. If there are multiple groups and the task IDs aren't grouped by group, it'd be a huge pain to parse the `status` output.

#### Describe the solution you'd like

Just add the `--group` and `--all` flags to `enqueue`, allowing the user to enqueue all stashed tasks, or just those in a group.

#### Describe alternatives you've considered

I'm currently using `pueue enqueue $(seq 0 10)` for this, but it only easily works if there's only 1 running group.

**Comment by Nukesor** [comment]
I'm curious, could you give a short explanation of your use-cases?
I.e. what are you using Pueue for and how are you using it (mostly manual, scripting, etc.)

I usually like to get a good understanding of a use-case before implementing a new feature.

**Comment by ChocolateOverflow** [comment]
In my case, I'm using `pueue` to download files, some large, some small. I have a `yt` group for `youtube-dl` downloads with some `parallel` setting.

Most of the time, I just enqueue as I browse, but I want to stash the downloads if I'm gonna turn my PC off soon, then start/enqueue the whole group when I'm back.

Basically, this is mostly for tasks that are most likely gonna take a long time but shouldn't or can't be continued after stopping.

**Comment by Nukesor** [comment]
This should actually not be necessary.

The pueue daemon automatically pauses groups that have "Queued" entries in it, when it starts up.

-> Just skip the step of stashing the tasks and start the group via `pueue start`

Alternatively, you can also simply pause the group via `pueue pause -g your_group`. You can also add the `--wait` option, if you want the current download to finish before rebooting.

**Comment by ChocolateOverflow** [comment]
The issue here is that `start` will force-start the tasks, but I just want to `enqueue` those tasks.

Stashing & pausing aren't the main issue here, it's wanting to resume queueing stashed tasks.

**Comment by Nukesor** [comment]
`pueue start --group your_group` doesn't force-start all tasks of a group, it just resumes the group. I.e. tasks in a paused group won't be started, even if they're `Queued`. 

They'll only be started as soon as the group is marked as `running`.

![image](https://user-images.githubusercontent.com/3322822/205021883-fbeb9424-cded-445d-823c-162e13ffc09a.png)

**Comment by ChocolateOverflow** [comment]
In my case, the group isn't pause. I just add & stash tasks with `add -s -g mygroup ...` and `enqueue` them later.

**Comment by Nukesor** [comment]
You could just do a `pueue pause` and skip the `-s` flag on `add` lateron.

Wouldn't this work for you? If so, whats your exact usecase?

**Comment by Nukesor** [comment]
To give you an example:

```sh
pueue pause --group your_group
pueue add --group your_group 'some_command'
pueue add --group your_group 'some_other_command'
pueue add --group your_group 'some_other_command_2'

# Reboot the pc and restart pueued
pueue status
# This should show that `your_group` is paused
pueue start --group your_group
# Pueue should now process the group as usual
```

**Comment by ChocolateOverflow** [comment]
Oh I guess I misunderstood `pause` and `start`.

```
    pause            Either pause running tasks or specific groups of tasks.
                         By default, pauses the default group and all its tasks.
                         A paused queue (group) won't start any new tasks.
```

My understanding of `pause` was: this will also pause running tasks like with `ctrl+Z` and `start` would later use something like `fg` to resume them.

```
    start            Resume operation of specific tasks or groups of tasks.
                         By default, this resumes the default group and all its tasks.
                         Can also be used force-start specific tasks.
```

My understanding of `start` was: this will put **all** the tasks in the group in the `running` state, even if the number of tasks is larger than the `parallel` setting.

If `pause` stashes all tasks added after it's called, and `start` later `enqueue`s all those tasks, that sounds exactly like what I wanted.

**Comment by Nukesor** [comment]
>    For instance, pueue pause -g cpu will pause all tasks in the cpu group.
> "Pause all tasks" sounded like "ctrl-Z all tasks" to me.

This is true, `pueue pause` will indeed send a SIGSTOP to all running tasks, except you when you add the `--wait` flag, as described in an earlier message :)

> Alternatively, you can also explicitly pause the group via `pueue pause -g your_group`. You can also add the `--wait` option, if you want the current download to finish before rebooting.

`pueue start` will then continue all "Paused" tasks as well as normal operation for that group.

The `pueue pause` call doesn't stash any tasks. It will just pause the Group, preventing any tasks being automatically started.

**Comment by ChocolateOverflow** [comment]
Sounds like `pause --wait` and `start` are exactly what I wanted - defer all added tasks and manually resume queueing later.
