### ISSUE TITLE
Missing assets

### ISSUE THREAD

**Issue by fgtham** [Nukesor/pueue#399]
Could you please provide the pre-built `pueue-linux-x86_64` asset as you did until v2.1.0? Unfortunately it's not always possible to build from source :(

Best regards and thanks for this awedome piece of software!

**Comment by fgtham** [comment]
Thanks, very much appreciated!

**Comment by Nukesor** [comment]
Binaries for linux x86 are uploaded :)

Could you close the issue once you verified that they're working?

**Comment by fgtham** [comment]
Thank you, works :)
