### ISSUE TITLE
[Feature Request] Add `--state [STATE]` to `pueue wait`

### ISSUE THREAD

**Issue by nickalcock** [Nukesor/pueue#400]
#### Describe the bug

I don't know if this is a bug or a feature request. I'm using pueue in a video transcoder to throttle multiple simultaneous jobs to vaguely the capacity of the machine. Much of the pipeline is annoyingly singlethreaded, so I kick off multiple instances of the transcoding script (each of which transcodes multiple things) via "pueue add" at the console. The problem lies inside the script itself, where it fires off the multithreaded part of the job via pueue add itself, on a group with parallel set to 1 so they'll wait for each other, then waits for it (via pueue follow so the users can see the output).

And this frequently (more-or-less randomly) fails:

Failed to get log file handles: I/O error at path "/home/nix/.local/share/pueue/task_logs/73.log" while getting log file handle:
No such file or directory (os error 2)

as if the log isn't even there, even though the task might have been running for days by this point.

#### Steps to reproduce the bug

The script does

```
TASK="$(pueue add --label "Transcoding $finalname" --group handbrake --immediate --print-task-id --escape -- "lazy-handbrake /* horribly complicated command line */ || touch $TMPDIR/$TRACK.fail)"
pueue follow $TASK
if [[ "$(pueue status -g handbrake -j 'columns=id,status' | jq '.tasks["'$TASK'"].status.Done != "Success"')" == "true" ]] || [[ ! -f $TMPDIR/$TRACK.mkv ]]; then
 /* error */
```
Allas, the pueue follow has a tendency to fail with

Failed to get log file handles: I/O error at path "/home/nix/.local/share/pueue/task_logs/73.log" while getting log file handle:
No such file or directory (os error 2)

as does the pueue status (you can tell the pueue follow worked because the error comes up after the *end* of all the pueue follow output: the pueue follow was running for days).

which then thoroughly screws the rest of the script, which was *expecting* to block until the job was done. (The || touch above is a desperate attempt to get the exitcode of the script without needing 'pueue status' to work, but that's no good if even pueue follow terminates immediately and pueue status then gets a status back that's not done at all. It does help when pueue follow worked, and after it terminated pueue status failed this way, which also happens about 40% of the time. Put these two errors together and about 75% of my runs are failing...)

#### Expected behavior

I thought pueue follow would wait until a task started and follow its output until it completed. Instead, I'd guess that what's happening is that we're racing on the daemon: the task hasn't quite started yet and pueue follow fails, and then the pueue status jq invocation fails because the task status isn't Done (I could make it more robust but jq's syntax is so horrific and ill-documented that I can't face it). Stranger yet, sometimes it works fine, but pueue status then complains that it can't find the logfile *which pueue follow was just happily following for days*.

The latter looks like a bug, but I'm not sure how to close the former race. There appears to be no way to wait until a task has started, and pueue add --immediate doesn't seem to do it (aside: I'm not sure what the distinction is between --immediate and nothing. Does --immediate push other running tasks out of the way, or does it start them stopped until pueue start is run?). I could loop until pueue follow doesn't fail, but that sounds awful and is prone to an infloop. It would be nice if pueue follow, or *something*, could be told to wait until task initiation, some state where pueue follow and pueue log would work if invoked. I could wait for task *completion* via pueue wait, but at the cost of not letting me see its output if pueue follow raced and failed, which is not really ideal since I'd have to dig up the id by hand out of dozens of concurrent ones, etc.

Suggestions?

#### Additional context

Linux, kernel 5.16.19 (I know, I know), pueue 3.0.0 built with Rust 1.65.0. Daemon started by hand, via pueued -d.

- Pueue version. Can be seen at the top of `pueue -h` output

(no it can't, it's in pueue --version)

**Comment by Nukesor** [comment]
Thanks for reaching out!

> I thought pueue follow would wait until a task started and follow its output until it completed. Instead, I'd guess that what's happening is that we're racing on the daemon: the task hasn't quite started yet and pueue follow fails, and then the pueue status jq invocation fails because the task status isn't Done (I could make it more robust but jq's syntax is so horrific and ill-documented that I can't face it). Stranger yet, sometimes it works fine, but pueue status then complains that it can't find the logfile which pueue follow was just happily following for days.

I think you're right about `follow` failing because the task hasn't started yet.

The daemon is running asynchronously, as it needs to manage tasks and check if there're any free slots. Tasks are enqueued every ~200ms, which is why this sometimes works and sometimes fails.

However, there's an easy fix for this. Pueue has never been designed to be scrictable, it just received a few convenience commands and helpers which allow it.
One of those helpers is the `pueue wait` command, which waits for either all tasks, a group, or a set of tasks to finish.

In your case, you could replace the `pueue follow` with `pueue wait` and you should be good to go.

**Comment by nickalcock** [comment]
Yeah, that'll fix it. The ideal would be a bit different though.

I'm also trying to display the output of the command as I go (since it's handbrake: it takes hours and does display useful progress output). Something like pueue wait --follow or (more generally) pueue wait --until STATE (which waits until the task switches state to STATE) or just pueue wait --until-changed (which returns whenever the task changes state at all) would be ideal: I could follow that with a pueue follow in the certainty that it would actually work.

(I'm surprised how useful it is in scripts actually -- mostly for squashing serial things running in high-parallelism queues down into parallel things in low-parallelism queues :) )

**Comment by Nukesor** [comment]
I think `pueue wait --state $STATE` seems like the best solution for this.
That's basically the same thing the integration test suite does.

**Comment by nickalcock** [comment]
Oh if the test suite is already doing something just like this, so much the better! Proof it's useful :)

**Comment by nickalcock** [comment]
Confirmed that a wait does stop this going wrong (it just means I don't get to see the output whenever the race hits).

**Comment by Nukesor** [comment]
Hey @nickalcock

I implemented the feature in the linked pull request.
Could you check out, if this works for you :)?

```
git clone git@github.com:Nukesor/pueue
cd pueue
cargo install --path ./pueue
```

**Comment by Nukesor** [comment]
I'm confused what do you mean by your last sentence?

**Comment by nickalcock** [comment]
Oh yes, that works fine -- what's odd is that you can't say `pueue wait --status Running`, even though the status is given with a capitalized first letter in the status output. (Probably both should be accepted?)

**Comment by Nukesor** [comment]
Ahh.

Fixed :). Pueue will allow capitalized stati with the next release.
