### ISSUE TITLE
Rerun tasks in group

### ISSUE THREAD

**Issue by Lucien0** [Nukesor/pueue#401]
#### Is your feature request related to a problem?

I want to rerun some tasks in different groups.
For example:
![image](https://user-images.githubusercontent.com/16538059/208614199-aa18b426-e8f6-4b5a-bf4e-e039e4b8bda9.png)

I have two gruops which have some finished tasks in it.
I want to rerun all tasks in a group without add any new task.

#### Describe the solution you'd like

I tried `pueue restart` but the group parameter is not currently supported.
So I have to use `pueue restart 0 1`, but it will enqueue new tasks like:
![image](https://user-images.githubusercontent.com/16538059/208615332-d3ecb576-cfef-4f94-a5b7-ede7213e9dd7.png)

I may need to repeat many times for my use case, so I don't want to keep adding new tasks to the group.

**Comment by Nukesor** [comment]
https://github.com/Nukesor/pueue/wiki/Configuration#client

`pueue restart -h`

**Comment by Lucien0** [comment]
Thanks for your kindly reply.
