### ISSUE TITLE
[Feature Request] Proper FreeBSD build support

### ISSUE THREAD

**Issue by yurivict** [Nukesor/pueue#403]
```
[procfs 0.14.2] Building procfs on an for a unsupported platform. Currently only linux and android are supported
[procfs 0.14.2] (Your current target_os is freebsd)
error: failed to run custom build command for `procfs v0.14.2`
```

Is there a way to disable procfs?

**Comment by Nukesor** [comment]
There's no way to disable it, as it's needed to interact with the /proc filesystem.

If you want to add support for freebsd, feel free to open a PR with the required changes :)

**Comment by yurivict** [comment]
So far I've created the FreeBSD port with these [patches](https://cgit.freebsd.org/ports/tree/deskutils/pueue/files).

**Comment by yurivict** [comment]
There should be a way to limit Rust library dependencies to systems where they are supported in Cargo.* files.

**Comment by Nukesor** [comment]
I'm going to continue this in a general pur.pose FreeBSD support ticket over here https://github.com/Nukesor/pueue/issues/406.

If we do any fixes, this should be done in a proper way, so things don't break again if anything changes!
