### ISSUE TITLE
[Debt] Darwin-Libproc is unmaintained

### ISSUE THREAD

**Issue by Nukesor** [Nukesor/pueue#409]
Well, it looks like the dev dependency repository https://github.com/jamwaffles/darwin-libproc for apple has just been deleted.

The repository no longer exists or has been made private. In any way this is a problem.

**Comment by Nukesor** [comment]
I created my own fork for the time being, but it would be great to get rid of that darwin-libproc library.

Any progress on that matter?

**Comment by mjpieters** [comment]
Please do assign this one to me, yes. I have a [PR outstanding with libproc-rs](https://github.com/andrewdavidmackenzie/libproc-rs/pull/86) that would replace let us replace darwin-libproc. I'll poke the maintainer for a review.

**Comment by mjpieters** [comment]
I found another project in the same bind having switched their dependency to [another existing fork](https://github.com/jeremy-prater/simple-process-stats/commit/fdaee1eabfdfc0a24d05085cd59cf5270a4c3839). Still, this is a real sore that needs to be removed one way or another.

**Comment by mjpieters** [comment]
Looking at the repo, it seems as if development now takes place against main? The development branch is significantly behind.

I'll create my PR agains main for now, I can always rebase and retarget later.

**Comment by Nukesor** [comment]
Ah. Yes, since most of the changes that were done in the meantime aren't related to new features that would require a minor version bump, I just pushed everything to development :sweat_smile:  

Still, I should definitely keep `development` up-to-date to main.

Anyhow, I would consider this a point-release change anyway, so feel free to merge this against `main` :)

**Comment by Nukesor** [comment]
Nevermind, I just saw that I accidentally pushed a new feature to `main` -.-

Shame on me
