### ISSUE TITLE
Improve backend performance and scalability

### ISSUE THREAD

**Issue by jpambrun** [Nukesor/pueue#412]
#### Is your feature request related to a problem?

This software is very neat and the interface very usable. So such so that it invites usage for orchestrating 1000s of task, but does not in fact scale to that level. I think the main performance issue is with the single state yaml. I think the best option is to replace it with append only embeded database such as sqlite or https://github.com/Rustixir/darkbird.

For example:
``` shell
> time seq 1 100 | xargs -I _ pueue add -- sleep 500
real    0m0.441s
> seq 1 1000 | xargs -I _ pueue add -- sleep 500
[...]
> time seq 1 100 | xargs -I _ pueue add -- sleep 500
real    0m1.310s 
```

As you can see, adding the first 100 tasks took 450ms, but adding task 1100 to 1200 took 1300ms. I know it's a string ask, but I would like to add 10,000s of tasks and let it run for days.

#### Describe the solution you'd like

I would like to able to manage 10,000s of tasks.

**Comment by jpambrun** [comment]
I started looking at integrating [darkbird](https://github.com/Rustixir/darkbird) thinking that the state interface is a good api match, but then noticed it is shared with the client. Not knowing how best to proceed I resorted to opening a request.

**Comment by Nukesor** [comment]
In general, I'm all about performance. But the whole reason for the state being json is that it's an easy to debug and a relatively human-readable format that's supported practically everywhere.

Your use-case isn't what Pueue has been built for and it's not what Pueue aims to be.
The design goals can be found over here: https://github.com/Nukesor/pueue#design-goals

You're trying to use it as a heavy duty process scheduler, which it simply isn't.
Adding a whole storage engine + a new format would add a gigantic amount of complexity in combination with new questions such as atomicity when working with the new state format. The current mutex system would have to be completely rewritten and adjusted to the new approach.

-> If you find a way to improve the current way it works, feel free to create a pull request :)
In case you have to change logic in a back /forwardincompatible way though, I'll have to deny this feature request as it doesn't fit into the scope of Pueue's design goals.

**Comment by Nukesor** [comment]
-> Pueue doesn't have to be scalable.

It's designed to be a commandline helper for a single user.
For example, server admins that schedule a few long running tasks on their machines and log off.
Hundreds of tasks are actually already out of scope.


As stated in the design goals, there's actually the need for another solution. A modern heavy-duty, distributed and scalable process scheduler. But this isn't Pueue's job.

In case you're going to write something like this, please create a Pull request to link to that project in the README :)

**Comment by jpambrun** [comment]
I understand. Looking at the interface I thought it would be a great fit. For what it's worth the intended use was single user. I need to copy files across thousands of GCS bucket and wanted a way to manage concurrency and log failed tasks.

Anyway, thanks for getting back to me so quickly, feel free to close this request or keep it around as documentation. I won't be offended either way.

**Comment by Nukesor** [comment]
gnu parallel should be the right tool for this job, it's speciality is running thousands of different tasks with retry logic and proper parallelization :)
