### ISSUE TITLE
[BUG] errors with non-UTF-8 task logs

### ISSUE THREAD

**Issue by yuma140902** [Nukesor/pueue#417]
#### Describe the bug

In a task that outputs multibyte characters on Windows, `pueue log` command throws an error.

#### Steps to reproduce the bug

1. Create a Python script `a.py` with the contents `print('abcあdef')`.
2. Add a task with `pueue add python a.py`. The task will complete successfully.
3. Run `pueue log 0` to view the log, and it shows only `abc` not `abcあdef`.

#### Expected behavior

Complete logs are displayed without errors.

#### Logs/Output

`pueue log` outputs the following:

```
┌───────────────────────────────────┐
│ Task 0:    completed successfully │
└───────────────────────────────────┘
Command: python a.py
   Path: C:\***
  Start: Fri, 17 Feb 2023 22:30:48 +0900
    End: Fri, 17 Feb 2023 22:30:49 +0900

output:
abcFailed reading local log file: Windows stdio in console mode does not support writing non-UTF-8 byte sequences
```

I am using python 3.9.13 but I think it is not a python-related problem.

#### Additional context

- Operating System: Windows 11 Home 64bit
- Pueue: 3.1.1

I think the problem is [here](https://github.com/Nukesor/pueue/blob/main/pueue/src/client/display/log/local.rs#L28). 
As stated in this doc https://doc.rust-lang.org/std/io/fn.stdout.html#note-windows-portability-considerations, `std::io::stdout` does not support non-UTF-8 byte sequences, so it cause errors with outputs encoded in a character code other than UTF-8.

**Comment by Nukesor** [comment]
Interesting.
Could I assign you this bug? I no longer have a machine with a Windows OS, so I won't be able to fix this myself.

**Comment by yuma140902** [comment]
Of course! In fact, I have already worked on this issue.

**Comment by Nukesor** [comment]
Closed as wont-do for the time being :)
