### ISSUE TITLE
Feature request - edit

### ISSUE THREAD

**Issue by awigg** [Nukesor/pueue#42]
I'm missing the option edit - something like 
`pueue edit 1` to edit the command in $EDITOR for example

**Comment by Nukesor** [comment]
Actually a good idea!
I'll take a look on how to implement this behaviour.

**Comment by Nukesor** [comment]
I just implemented and tested it and it's a really nice feature!
I'll investigate another possible bug, before releasing 0.9.

**Comment by awigg** [comment]
nice one, thanks.
