### ISSUE TITLE
"pip3 install" gives us v1.0.2

### ISSUE THREAD

**Issue by tf0054** [Nukesor/pueue#43]
I'm not sure bc am not an experienced pueue user (Thank you so much for developing the aewesome app!), but it seems our system stacked because out app cannot get result of `pueue status`.

https://pypi.python.org/pypi/pueue

I am guessing this might have been solved with v1.0.3, so would you update the package on pip repository, please?

https://github.com/Nukesor/pueue/commit/807df063cf4603bfe4fe568b31c251eb930fba96

**Comment by Nukesor** [comment]
New version is online. I really forgot to upload the new version ...
Sorry for any inconveniences :)
