### ISSUE TITLE
[Feature] Add `pueue group --json` flag

### ISSUE THREAD

**Issue by Nukesor** [Nukesor/pueue#430]
The idea is to add a `--json` flag to the pueue group subcommand, so it's easier to do scripting with groups.

The usecase in #428 seems to make extensive use of the group feature to sort tasks.
Groups that no longer have any active tasks should then be removed.

Since there's currently no easy way to get a list of all groups, this should be exposed via an `--json` command.

**Comment by Nukesor** [comment]
Ping @allencho1222

Could you take a look whether the linked MR works for you :) 

```
git clone git@github.com:Nukesor/pueue
cd pueue
cargo run --bin pueue -- group --json
```

**Comment by allencho1222** [comment]
Hi, @Nukesor

It works correctly.

I appreciate it.
