### ISSUE TITLE
Disable auto-pause on kill

### ISSUE THREAD

**Issue by Crissante** [Nukesor/pueue#452]
### A detailed description of the feature you would like to see added.

It would be useful if a flag could be added like `pueue kill --no-pause` to disable automatic pausing of tasks

### Explain your usecase of the requested feature

I want the task added after `pueue kill` to start as expected instead of having to run `pueue start`

**Comment by Nukesor** [comment]
To be honest, I would be ok if a queue is not paused by default, as long as there're no further scheduled tasks.

This seems like a good UX improvement.
