### ISSUE TITLE
Machine friendly output

### ISSUE THREAD

**Issue by vitalybe** [Nukesor/pueue#46]
I want to write some tooling for pueue (specifically integration with [bitbar](https://getbitbar.com/)) but currently the output of all commands is only human friendly.

It'd be nice if all commands (but mainly status) had a JSON output flag.

**Comment by Nukesor** [comment]
The best way to implement this would probably be to refactor the communication protocol from pickled python objects to json.
This shouldn't be too hard :) Feel free to hack around a little and open a PR.
I'll happily review it!

**Comment by Nukesor** [comment]
Hey there.
The first version of the rewrite is on master. A release will follow shortly.
The rewrite supports a `-j` flag for `status` and `log`. I hope this helps you realising such tooling!
