### ISSUE TITLE
Support config location "~/.config/pueue/pueue.yml" also for macOS

### ISSUE THREAD

**Issue by meseck** [Nukesor/pueue#464]
### A detailed description of the feature you would like to see added.

Also on macOS, the "\~/.config" folder is essentially the "home folder" for config files for most CLI tools available today.

### Explain your usecase of the requested feature

The "~/.config" folder is a very convenient place to manage and then back up your personal dotfiles.

### Alternatives

I could symlink "\~/Library/Application Support/pueue/pueue.yml" directory to "\~/.config/pueue/pueue.yml".
But then I lose the portability of this config file to other Unix systems. :/

**Comment by Nukesor** [comment]
Sadly, the `.config` location is no standard in the MacOS environment, hence I would like to not support it.

However, you can easily achieve this, by just using an alias and setting the configuration directory manually.

`alias pueue='pueue -c ~/.config/pueue/pueue.yml'`

**Comment by QuantumGhost** [comment]
Maybe add an environment variable `PUEUE_CONFIG` ?

**Comment by Nukesor** [comment]
That sounds reasonable to me :)

Could you check out the linked MR? I went ahead and implemented the feature as requested.

**Comment by Nukesor** [comment]
Ping @meseck

**Comment by meseck** [comment]
I really appreciate this solution. Thank you for your effort!

Just like how `ripgrep` handles this:
https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md#configuration-file

Just one small thing: to be super explicit that the environment variable expects a path (and not already config properties), what do you think of naming it `PUEUE_CONFIG_PATH`? This is also how `ripgrep` does it. :)

**Comment by Nukesor** [comment]
I like that proposal. `PUEUE_CONFIG` has been renamed to `PUEUE_CONFIG_PATH` :)

**Comment by texastoland** [comment]
Didn't make it into the README 🫣

**Comment by Nukesor** [comment]
Feel free to update the wiki :). Everybody can edit it!

I'll take care of the readme
