### ISSUE TITLE
[Bug] Failed to create pid file

### ISSUE THREAD

**Issue by makorne** [Nukesor/pueue#466]
### Describe the bug

Installed package `pueue v3.2.0` (executables `pueue`, `pueued`)
 pueued -d
Pueued is now running in the background
~/rs/$ Error: Failed to create pid file.

Caused by:
    I/O error while creating pid file:
    Permission denied (os error 13)

### Steps to reproduce

1. cargo install --locked pueue
2. pueued -d

### Operating system

Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux

### Pueue version

3.2

**Comment by Nukesor** [comment]
Please check your $XDG_RUNTIME_DIR variable and whether the path it points to actually exists and whether you're allowed to write into your runtime directory.

This looks like a misconfigured user environment.

**Comment by Nukesor** [comment]
I'll go ahead and improve the error messages for this case as well.

I thought I already did this for all path related I/O errors, but looks like I missed a few places.

**Comment by Nukesor** [comment]
Ping @makorne

**Comment by Nukesor** [comment]
Ping @makorne

**Comment by Nukesor** [comment]
Closing for now as solved :)
Feel free to comment if you have any additional information.
