### ISSUE TITLE
A process queue and pueue allocates them to several groups as soon as the group's running processes is lower than parallel number.

### ISSUE THREAD

**Issue by crazyn2** [Nukesor/pueue#476]
### A detailed description of the feature you would like to see added.

A process queue and pueue allocates them from queue to several groups as soon as the group's running processes is lower than parallel number.

### Explain your usecase of the requested feature

I have three gpu, but the processes running in them didn't finished at the same time. I want a function that pueue could allocate process in the free gpu or lower usage gpu and I can add process into queue at any time.

**Comment by Nukesor** [comment]
Hey @crazyn2 

Something probably got lost in translation and I'm not 100% sure what your requested feature would look like.

From what I've gathered, this sounds a lot like the feature requested in https://github.com/Nukesor/pueue/issues/218.
This has been implemented, even though it really isn't documented anywhere. Somebody should probably write a Wiki page for this :sweat_smile: .

This feature allows tasks to be called like this: `command --gpu $PUEUE_WORKER_ID some_other_parameters`.
If multiple jobs should run per GPU, this would need to be handled by the `command`.

Pueue is no high-performance scheduler with complex logic and it's not planned to make it one. There're other tools out there that specificaly tackle complex cluster job management.

In case I completely misunderstood your feature request:
Could you write a more detailed explanation, for instance with a proper example and the exact way it would work, including a step-by-step description of the behavior?

**Comment by crazyn2** [comment]
I apologize for not expressing myself clearly. I want to have a queue where I can add processes freely and then set a limit on the number of processes running on the cluster, for example, 2. Whenever the number of running processes in any group is less than 2, it will extract one from the queue to that underutilized group. I've read the #218 and wiki. However, It doesn't meet my expectations. This is my bash shell which has the function I expected:

**Comment by Nukesor** [comment]
I thought a lot about this and I this is nothing that'll be added to Pueue.
Pueue is not designed to be a complex task scheduler, but rather a small scheduler for server maintainer and hobbyists.

I still think that it's possible to write a wrapper script with the current functionality to map a given command to a given pool, but this is no logic that'll be added to pueue.


You might want to look at professional cluster management systems. I think our University used [slurm](https://slurm.schedmd.com/squeue.html) for such tasks.

Anyhow, thanks for the detailed feature request :)
Have a nice day!
