### ISSUE TITLE
show --watch incompatible with --key

### ISSUE THREAD

**Issue by JP-Ellis** [Nukesor/pueue#48]
It appears that whenever using the watch option in `pueue show`, the output of the same process is always shown, irrespective of the value of `--key`.

**Comment by Nukesor** [comment]
I'll look into this in the next few days. Haven't looked into this code base since quite a while and I probably need some time to refactor and fix this stuff :D

**Comment by Nukesor** [comment]
Actually I just tested this and it works perfectly fine.
I also don't see how something like this could possibly happen in the code base. Could you provide more information please?
