### ISSUE TITLE
Reset specific group

### ISSUE THREAD

**Issue by amiroslaw** [Nukesor/pueue#482]
### A detailed description of the feature you would like to see added.

I was surprised that I can't reset or remove all tasks from a specific group. I'm not sure if it wasn't implemented in this [issue](https://github.com/Nukesor/pueue/issues/153), but there is no parameter `--group` in the reset option. 
I use pueue 3.3.2

### Explain your usecase of the requested feature

I want to clean up jobs in a group with one command. It would be nice to have `pueue reset --group` or  ` pueue remove --group`

**Comment by Nukesor** [comment]
With https://github.com/Nukesor/pueue/pull/547 landing, this change should now become significantly easier.
The whole process handling logic has been streamlined a lot.

PRs welcome.
