### ISSUE TITLE
Allow to disable parallel taks limit

### ISSUE THREAD

**Issue by ClementNerma** [Nukesor/pueue#500]
### A detailed description of the feature you would like to see added.

Allow to disable the limits of parallel running tasks. Idea of implementation: `pueue parallel 0` would disable any limit (like many othe rtools do).

### Explain your usecase of the requested feature

Not needing to worry about the parallel tasks limit undependently of the usage of pueue.

**Comment by Nukesor** [comment]
Implemented the behavior in the linked MR.
Also tested it properly on my local setup and it works as expected :)

**Comment by ClementNerma** [comment]
Ha, I was about to submit my own PR for this but you beat me to it xD
Thanks for the feature!
