### ISSUE TITLE
Make 'pueue add -g Group' add the Group if it doesn't exist

### ISSUE THREAD

**Issue by Schweber** [Nukesor/pueue#507]
### A detailed description of the feature you would like to see added.

I would like `pueue add -g Group -- Task` not to fail when `Group` does not exist but instead add the group. This should be behind a flag so as not to change the current default behaviour.

### Explain your usecase of the requested feature

It would make it easier to use `pueue` as the current state of `pueue` and its groups would not matter anymore and i could always send the commands as if the group did exist already.

### Alternatives

I could write a script that checks if the group already exists and remove it if this is the case, before running the command for adding the task. The new feature would just be a QoL improvement.

**Comment by Nukesor** [comment]
Could you elaborate your use case? Why exactly do you want to be able to quickly create arbitrary groups?

Could you give me a scenario or an example of how you're using pueue and what you exactly want this feature for?

As to how such a feature would look like:
- You're correct, there must be a feature flag, as this behavior is pretty unsafe.
  Groups exist to allow running multiple queues in parallel. The idea behind groups is to schedule various queues of commands that consume different parts of the system (I/O, Ram, CPU).
  So just creating new groups whenever a group doesn't exist will lead to problems if users have a typo in their group name while adding a task. Additional tasks would be executed on top of already running tasks, without the user knowing..
  
  So **if** this would be added, a warning would have to be added on top of the configuration flag.
- Those groups would always be created with a parallel limit of `1`. So you would just a new default queue.

**Comment by Nukesor** [comment]
Thinking about it, you can already easily achieve this via a simple shell function/alias  with anonymous function

**Comment by Nukesor** [comment]
To be honest, this indeed sounds like a pretty specific usecase and a script is probably a neat solution for this problem, especially since it sounds like you're already scripting most of the stuff anyway.

I will close this issue for now as "wont do", but if more people have the need for such a feature, it's always possible to reconsider :)
