### ISSUE TITLE
feat: use S3 to save std output and error

### ISSUE THREAD

**Issue by linux-china** [Nukesor/pueue#515]
### A detailed description of the feature you would like to see added.

Now I use pueue to run different scripts to generate CSV files, and these files will be used by DuckDB and ClickHouse. Is possible to ask pueue to write stdout as object in S3 bucket.  

object name:  pueue_instance/task_id-status.txt
object metadata: Task id, Status, Command, Path, Start, End 

### Explain your usecase of the requested feature

Why this features?

1. Easy to backup output with S3
2. Scripts are datasources for data process
3. Local disk cleanup and some I/O problem
4. Most data tools use S3 as data storage by default.
5. Easy to trigger with S3 object creation notification

**Comment by Nukesor** [comment]
Nope, this most definitely doesn't fit into the scope of this project.
It's designed for single user on-system usage. There's no need for any cloud service integration.

See https://github.com/Nukesor/pueue?tab=readme-ov-file#design-goals

It seems to be possible to mount S3 buckets to the local file system, so it should be somewhat feasible to do anyway. There won't be official support for it though.
