### ISSUE TITLE
[Bug] Pre built binary doesn't work on macOS

### ISSUE THREAD

**Issue by suzuki-shunsuke** [Nukesor/pueue#522]
### Describe the bug

I downloaded the pre built binary and tried to execute it on macOS, but it didn't work.

### Steps to reproduce

1. Download a latest pre built binary [pueue-macos-x86_64](https://github.com/Nukesor/pueue/releases/download/v3.4.0/pueue-macos-x86_64) or [pueue-darwin-aarch64](https://github.com/Nukesor/pueue/releases/download/v3.4.0/pueue-darwin-aarch64) from GitHub Releases.
1. Execute the binary.

```console
$ pueue --help
```

### Debug logs (if relevant)

I tried with several laptops.

1. macOS Ventura Intel Core i5 (darwin/amd64)

```console
$ pueue --help
zsh: segmentation fault  pueue --help
```

2. Apple M1, Apple M1 Pro, Apple M3 Pro (darwin/arm64)

```console
$ pueue --help
zsh: killed    pueue --help
```

### Operating system

macOS

### Pueue version

v3.4.0

**Comment by Nukesor** [comment]
Well, I rely on my community to help me build and test builds for other architectures.

I have neither a windows nor a Mac at my disposal, so somebody would need to help me out with this :)
-> Something seems to be broken in the build process CI pipeline. Somebody would need to clone the repo, run a few builds and check what's wrong.

PRs very much welcome!

**Comment by Nukesor** [comment]
Any progress on this @suzuki-shunsuke

**Comment by Nukesor** [comment]
I'm going to close this for now.
The Github build system has been completely rewritten and the issue should probably be fixed. If not now, at least once  v4.0.0 has been released.

If the issue still persist after the v4.0.0 release, please re-open this issue :)

In the meantime, you could go ahead and test the release logic on a local branch if you like.
