### ISSUE TITLE
Filter by `command %=`

### ISSUE THREAD

**Issue by max-sixty** [Nukesor/pueue#524]
### A detailed description of the feature you would like to see added.

Currently `pueue status label %= foo` works. It would be great to have the same thing for `command`.

### Explain your usecase of the requested feature

.

### Alternatives

`--json`, but it's much heavier when wanting to quickly check something from the CLI

### Additional context

`pueue` is awesome, thank you for making it!

**Comment by Nukesor** [comment]
Seems reasonable, feel free to add this :)

**Comment by Nukesor** [comment]
@max-sixty Do you still need this and would you be willing to implement this?

Just curious as you didn't answer on my last message.

**Comment by max-sixty** [comment]
It would still be a nice feature, but I don't have plans to add it at the moment.

Still using pueue, still a big fan!

**Comment by Nukesor** [comment]
Implemented #560 :) 
Thanks to  @magicwenli
