### ISSUE TITLE
OK to rename `Miscellaenous`?

### ISSUE THREAD

**Issue by max-sixty** [Nukesor/pueue#525]
### A detailed description of the feature you would like to see added.

Is it OK to rename https://github.com/Nukesor/pueue/wiki/Miscellaneous to something that suggests it's for advanced users? Say "Power tips" or "Advanced tips"?

I managed to write my own `fzf` tool before realizing you'd already made one...

FWIW I just renamed it and then reverted — there's no PR for wikis — so checking here.

### Explain your usecase of the requested feature

.

**Comment by Nukesor** [comment]
Sounds like a reasonable rename :)
Advanced tips or advanced usages seem like a good name.

The `fzf` tool was actually written by a community member :D They're doing quite a lot of cool stuff with Pueue.

**Comment by max-sixty** [comment]
Done! #526 for the link rename
