### ISSUE TITLE
Able to remove queued tasks from a group or clean/reset a specific group

### ISSUE THREAD

**Issue by daviddwlee84** [Nukesor/pueue#530]
### A detailed description of the feature you would like to see added.

Currently,
- `pueue group remove` cannot remove group with (any status) tasks in it.
- `pueue remove` only takes task id as input.
- `pueue kill` supports group option but only remove tasks that are running.
- `pueue clean` supports group option but only remove tasks that are finished.
- `pueue reset` will clean up everything regardless any running task.

Currently, I can't find a good way to either clean/reset the group or simply remove the group and recreate. 

Maybe we can have `pueue group remove` to support force remove even it has tasks in it.
Or we can have `pueue clean` to accept flag that can clean up queued tasks.
Or `pueue reset` on a specific group.

### Explain your usecase of the requested feature

Assume that I am running something in other groups. And I accidently `pueue add` some tasks (submit plenty of tasks within a shell script) to a group that I don't want to execute and I `pueue kill -g group_name` will get a pause group with lots of queued tasks.

Now I want to use the *same group name* to run a new set of tasks.

As the "queued tasks" are many, so removing the task one by one by ids is not possible. And there are tasks running in other groups so `pueue reset` can't be used.

### Alternatives

I can simply use a new group name to run the tasks. But this will leaves a paused group never used until everything done to `pueue reset` to get a "clean status".

**Comment by Nukesor** [comment]
This sounds pretty much like this would be solved by #482 ?

**Comment by daviddwlee84** [comment]
Ah yes 😂. Didn't find that one.

**Comment by Nukesor** [comment]
Perfect, will close in favor of that one :)
