### ISSUE TITLE
[Bug] chrono-english breaks with latest chrono version

### ISSUE THREAD

**Issue by Nukesor** [Nukesor/pueue#534]
### Describe the bug

So, chrono released a new version where they introduced breaking changes in a minor release.

This broke some trivial things in chrono-english, however chrono-english seems to be unmaintained and the author is unresponsive. See https://github.com/stevedonovan/chrono-english/issues/29 and https://github.com/stevedonovan/chrono-english/pull/30

Due to a missing alternative, I decided to contact the maintainer of `dateparser`, which was open to add such functionality upstream in their crate.

I started work on this over in https://github.com/Nukesor/dateparser/tree/natural-language for https://github.com/waltzofpearls/dateparser/issues/48, but I'm getting side-tracked by work and other projects.

**Comment by conradludgate** [comment]
For the record, I am maintaining a fork of chrono-english. https://docs.rs/interim/latest/interim/index.html

Complete rewrite but the same tests pass and it supports time as well as chrono. Let me know if I can help at all

**Comment by Nukesor** [comment]
Uh nice!
Your overhaul definitely looks a lot cleaner than the old chrono-english codebase :D. It was a bit of a mess, not gonna lie.
I might just switch to your fork!

I was personally really interested in seeing an implementation that utilizies a proper parser library (`pest` in this case), but I really don't have the time to follow up on this right now :sweat_smile: 

Thanks for your work! I'll take a closer look in the next few days :)

**Comment by Nukesor** [comment]
Thanks again @conradludgate, this saved me a lot of time and work  :grin:

**Comment by astraw** [comment]
I think, but I'm not certain, that the original `chrono` issue seems to be https://github.com/chronotope/chrono/issues/1571 .
