### ISSUE TITLE
[Bug] Early EOF during remote socket connection

### ISSUE THREAD

**Issue by KitchenTable99** [Nukesor/pueue#543]
### Describe the bug

When I socket forward from a linux remote to a mac local, I'm unable to launch the pueue client even though it finds the socket appropriately due to an early EOF while reading the request size header.

### Steps to reproduce

1. Start `pueued -d` on remote linux server.
2. Issue the socket forwarding command on local mac `ssh -L /tmp/local.socket:/run/user/25800188/pueue_<usr>.socket <remoteHostName> -N`
3. Set the shared.unix_socket_path in the`pueue.yml` file to /tmp/local.socket
4. Run pueue

### Debug logs (if relevant)

08:41:48 [INFO] Parsing config files
08:41:48 [INFO] Checking path: "/Users/<username>/Library/Application Support/pueue/pueue.yml"
08:41:48 [INFO] Found config file at: "/Users/<username>/Library/Application Support/pueue/pueue.yml"
Error: Failed to initialize client.

Caused by:
    0: Failed to receive version during handshake with daemon.
    1: I/O error while reading request size header:
       early eof

### Operating system

Remote: Amazon Linux 2 || Local: macOS 13.6.7

### Pueue version

v. 3.3.3

**Comment by Nukesor** [comment]
Phew. Did you try whether this also happens when setting up unix socket forwarding from linux to linux?

**Comment by Nukesor** [comment]
Ping @KitchenTable99

**Comment by Nukesor** [comment]
Closed due to non-responsiveness
