### ISSUE TITLE
Not able to install via cargo

### ISSUE THREAD

**Issue by misterunknown** [Nukesor/pueue#55]
I'm not able to install pueue with cargo, neither with
```
cargo install pueue
```
nor with
```
git clone https://github.com/Nukesor/pueue.git
cd pueue
cargo install --path .
```
Both methods result in build errors. I put the output of the last command (local install) [here](https://termbin.com/c2yp).

Edit: I tried to install it in a fresh debian buster installation (with Rust 1.34).

**Comment by misterunknown** [comment]
Do I need a specific rust version?

**Comment by Nukesor** [comment]
Pueue relies heavily on the new stable async/await language feature.
This feature has been introduced with rust 1.39.
As long as you use the Rust stable channel, everything should be fine (stable is 1.40 right now).

**Comment by misterunknown** [comment]
Ok, thanks. I just installed the current rust version manually in debian:buster and it compiles. Thanks for the clarification!
