### ISSUE TITLE
Upload to conda-forge

### ISSUE THREAD

**Issue by roaldarbol** [Nukesor/pueue#552]
### A detailed description of the feature you would like to see added.

It would be great to have pueue available on [conda-forge](https://conda-forge.org). The reason behind this is that it would then be possible to install it with [pixi](https://pixi.sh), an environment manager that is centered on conda packages. This setup could then work more or less as a fully contained "Docker-like" environment, where it is possible to start background tasks as in Docker with a fully controlled environment.

### Explain your usecase of the requested feature

With Docker moving to paid services, people are looking for other toolschains that can achieve the same. A user had the use-case of running 5 Docker instances for a hobby open-source project (one of them was this https://grafieken.energieadvieszeeland.nl/), which now costs them £25 per month. That same fully contained environment could be achieved by combining the powers of pixi and pueue.

### Alternatives

It could be possible to install pueue from another source, but it breaks the reproducible, self-contained environment.

### Additional context

I appreciate that it might not be high on the priority list, but it is common that the conda community can help packaging for conda repositories, so even it might not be a task you'd want to undertake you could leave it open for community contributions.

**Comment by Nukesor** [comment]
Well, this is the upstream repository of Pueue.
It provides stand-alone, statically-linked binaries that run on all common architectures and uploads the code to <crates.io> for people to download and build it themselves.

Any custom builds or setups need to be done by packagers in their respective downstream distros. It doesn't make sense to maintain this stuff upstream, as there's myriad of various ways to install programs.

So if you think that this is important, go ahead and package Pueue for `pixi`  :)

**Comment by roaldarbol** [comment]
Ah, sorry about that - packaging is somewhat new to me! :-) I'll let you know if it gets uploaded so it can be added to the packaging table in the README.

**Comment by Nukesor** [comment]
Don't worry, the packaging table is also automatically updated, which is pretty nice :)

Check out repology, the guy maintaining this is a real boon for the open source community:
https://repology.org/project/pueue/versions

**Comment by roaldarbol** [comment]
Oh, that's cool! Thanks for making this project by the way - really stoked to have come across it!
