### ISSUE TITLE
Stashed tasks functionality

### ISSUE THREAD

**Issue by Squirreljetpack** [Nukesor/pueue#558]
### A detailed description of the feature you would like to see added.

Not sure if undocumented, but I couldn't find any options for handling stashed tasks in the cli.
Like maybe you want to enqueue a task without removing it from stashed
Or you want to remove all stashed tasks

### Explain your usecase of the requested feature

This came up because I didn't find any better way to remove all stashed tasks without starting them than by parsing for their id's. Since kill only kills running tasks?

### Additional context

If this fits the project's scope, I'd be interested in submitting a pull request.

**Comment by Nukesor** [comment]
So. There's either the `remove` command for removing tasks without starting them.

How exactly would "enqueue a task without removing from stash" look like? Enqueueing means to put it inside of the queue. Why should it stay stashed?

**Comment by Squirreljetpack** [comment]
well for common pueue commands, you could stash them,
and activate them from there.
But actually I have a fzf script from this that just reads from a file.
So maybe it's not such a good idea.
And I guess you can remove stashed commands by modifying the fzf script in the docs to have a remove task keybind.
But I just thought it was a bit strange that there is no group-level remove.
As there is group-level reset and clean.

**Comment by Nukesor** [comment]
What do you mean with "common pueue commands"? Could you explain your usecase in a bit more detail?
And what fzf script are you talking about and what is it reading from a file?

If you're talking about the fzf scripts in the wiki, those aren't part of the official project and rather snippets provided by the community. 

Regarding the first point:
How would a `pueue remove -g group_name`  differ from a `pueue reset -g group_name`?

**Comment by Squirreljetpack** [comment]
I use this script to help me select. The input method is kinda scuffed but its convenient.
Some commands I run are to use pueue to run rclone or set alarm
pueue remove -g would not kill tasks, just remove finished/stashed ones. That is those not considered for execution.

```
#!/bin/zsh

FILENAME=$ZSHDIR/ancillary/pujobs
INPUT="$1"

# useful for adding a recurring task
# Specifying the command via arg adds it to ps group

if [[ "$INPUT" == "-e" ]]; then
    echo "Enter the command to add and execute:"
    read -r NEW_COMMAND
    echo "$NEW_COMMAND" >>"$FILENAME"
    OUTPUT=$(pueue add --print-task-id -- "$NEW_COMMAND")
elif [[ "$INPUT" =~ ^[0-9]+$ ]]; then
    LINE_CONTENT=$(sed "${INPUT}q;d" "$FILENAME")
    if [[ -z $LINE_CONTENT ]]; then
        exit 1
    fi
    OUTPUT=$(pueue add -g ps "$LINE_CONTENT")
elif [[ -n "$INPUT" ]]; then # input with single quotes
    OUTPUT=$(pueue add -g ps --print-task-id -- "$INPUT")
else
    LINE_CONTENT=$(cat $FILENAME | fzf --header "$FILENAME" --bind "ctrl-o:become($EDITOR $FILENAME)")
    if [[ -z $LINE_CONTENT ]]; then exit 1; fi
    OUTPUT=$(pueue add --print-task-id -- "$LINE_CONTENT")
fi

# TASK_ID=$(echo "$OUTPUT" | $GREP_COMMAND -oP '(?<=id )\d+')

echo "$OUTPUT"
```

**Comment by Nukesor** [comment]
I'm still very much confused.
What do you mean by "stash+queue in one go"

When you do a `pueue add "some command"`, the task is immediately queued **unless** it's called with the `--stashed` flag, which stashes the task away for sometime later.

Tasks only ever get stashed when the user explicitly decides to do so, which can also be done at any time via the `pueue stash` command, which takes a queued task and stashes it away.

Stashed tasks can then be enqueued via the `pueue enqueue` command, which puts them into the `Queued` state where they'll be processed as usual.

I feel like you're confusing `pueue stash` with the behavior of `git stash`, which behaves like a stack of changes. However, even in git, you can apply stashed entries from anywhere inside of that stack. The stack is just a convenience layer on top of the set of changesets, to make it more convenient to use.
In pueue, there's no stack. `Stashed` is a state that is part of the Pueue's state machine for tasks.

**Comment by Nukesor** [comment]
I made a simplistic diagram of the rough states and their transitions for you to better visualize how this works:

![Pueue State Diagram](https://github.com/user-attachments/assets/bdb69b60-952d-4a93-bbfe-7b5bb8aa7541)

**Comment by Squirreljetpack** [comment]
Thx for the diagram, I was a little curious about which states there were.
Do you have an example of when stashing a task might be useful?
I can only think of maybe you use pueue to a batch of some long run processes like media conversion, and u change ur mind/want to manually save some tasks for later.
Or in my case, have a notification script, and stash + queue that script to act as an alarm.
I feel like that case is the more common usage of pueue add --stashed (not sure if correct), and in that case, it makes a lot of sense to have pueue add --enqueue "datestring" -- 'command'.
In the first case, you may want to unstash or cancel those tasks in batch.
So it could be a small change but possibly sensible change to have batch enqueue/remove for stashed tasks?

**Comment by Nukesor** [comment]
Correct. Stashing is mostly for when you add a task and notice that now is not the time to run it.
Or when you have a command that you want to run at some point, but not right now.

Your proposed usecase is already implemented with the `--delay` flag on `pueue add`.
However, it actually is missing on the `pueue stash` command, which seems like a reasonable addition.

A `--group` flag for enqueue also seems reasonable, as it mirrors the behavior of most other commands.

For `remove` i'm not too much of a fan to be honest as there're multiple problems when designing that interface.
- Two new flags would need to be added `--group` and `--stashed`
- `--group` on its own wouldn't work in most usecases as the remove command cannot remove running/paused commands
- `--stashed` on its own wouldn't work, as it's unclear what's selected.
-  You would need to combine `--stashed` with `--group` and `--stashed`.

That just isn't a good ui design.

**Comment by Squirreljetpack** [comment]
1. Oh ty, somehow missed that flag ha.
2. Yeah okay I agree. I think without the fzf script on the wiki it could maybe be a bit annoying to manage the tasks if for some reason someone (ha) stashed them without enqueuing them and later wanted to get rid of them, but with it the extra functionality is completely superfluous.
