### ISSUE TITLE
Add how to start daemon in macOS

### ISSUE THREAD

**Issue by alextooter** [Nukesor/pueue#56]
The README doesn't mention how to start pueue daemon in macOS, and '--daemon' is not working.
Please add how to start daemon in macOS in README.

**Comment by Nukesor** [comment]
Adding `pueue &` doesn't seem like a good way to start the daemon.

Usually the best way to do this is starting pueue with the service manager of your OS.
I don't own a device running macOS, thereby I don't really know what's the proper way to automatically start services in macOS.

If you provide me with a proper configuration file or a simple tutorial on how to do this in macOS, I'll happily add it to the README. PR's are of course welcome as well :)

**Comment by Nukesor** [comment]
After some consideration, I'll add the old --daemon functionaility again.
I'll probably get to this around Friday/Saturday. I'll also create a new release after finishing this feature

**Comment by Nukesor** [comment]
Just released v0.1.1 with the new feature set:
`pueued -d` for daemonization
`pueue shutdown` to shutdown the daemon
