### ISSUE TITLE
Token substitution in pueue config files

### ISSUE THREAD

**Issue by j-xella** [Nukesor/pueue#563]
### A detailed description of the feature you would like to see added.

It would be great to have token substitution in pueue config files.  For example, in

```yaml
pueue_directory: /common/path/prefix.%HOST%
```

the `%HOST%` token would get replaced with actual host name of the machine, before the pueue_directory value is used.

First tokens that come to my mind: `%USER%`, `%HOST%`, `%HOME%`

### Explain your usecase of the requested feature

We have a cluster of Linux boxes to which we log in with the same account, and our home partition is stored on a network share and mounted in the same location on each box. This makes it difficult to use the same pueue configuration on all boxes. The same configuration means the same `pueue_directory`. If that directory is somewhere under home folder and the home folder is shared, `pueued` servers on different machines effectively use the same files and conflict with each other.

Another (potential) use of this feature could be where one common config would be created on a machine that would work differently for different users.

### Alternatives

It is possible to use separate configs for each box, or have one config with separate profiles. However, there are certain drawbacks:

* Maintenance overhead - you need to maintain multiple copies of configs, where the only difference is `pueue_directory`. Maybe that could be reduced if profiles **inherit** the values in main client/daemon/shared sections - but this is not the case at the moment, correct?
* Invocation overhead - now each pueue call will have additional params. This can be mitigated with setting environment variables or command aliases, but makes shell configs more complex.

Another approach could be to point pueue_directory to a location that is not shared between multiple machines. But that would mean storing a lot of sensitive data outside the home folder in my case, which I would rather avoid.

**Comment by Nukesor** [comment]
Phew. To be honest, I would really like not to. Your setup sounds pretty wild.

Do I understand correctly that you're re-using a home directory in different locations accross multiple linux systems?
And each box runs its own pueued? How do you prevent from the different daemons to interfere with each other if they all share the same state dir?

Maybe I misunderstood something, but your setup sounds a bit janky and like a pretty rough edge-case. Pueue has generally been designed for single users only, so I'm unsure whether this is a usecase that would improve the single-user UX.

The most common convenience char `~`  has already been covered and extends to `$HOME`, as it makes the configuration a lot easier to read.

**Comment by Nukesor** [comment]
Thanks for the thourough explanation, I now understand your usecase a lot better.

Let me think about it for a bit :)

**Comment by Nukesor** [comment]
So, I thought about it quite a bit.

I see where you're coming from and that this would really help your usecase. However, this feature would only be built to support a usecase that I really don't want to support.

Instead of adjusting Pueue, you should maybe try to fix the setup that's enforced by your company. Having a single home directory mounted into multiple live systems at the same time is a bad idea for many reasons. 

I'm sorry, but I really don't feel comfortable to add this to Pueue, as it would add new complexity without giving a benefit to users in normal environments.
