### ISSUE TITLE
pueue send enhancement

### ISSUE THREAD

**Issue by Madhu-mohan86** [Nukesor/pueue#571]
### A detailed description of the feature you would like to see added.

Currently the `pueue send $processno` is useful for in any of the y/n scenario but I personally need the option something like `pueue exec $processno` in case of commands that requires enter key to be pressed

### Explain your usecase of the requested feature

Some of the commands or process requires more than just `y/n` confirmations . Here I came across the scenario where I had some customized script that requires some IP's to be entered and to confirm or move next after that `read ` function , I want to press enter but I cant find feasible options for this as I tried with `yes ` command and it is not helping because the script takes this command as the input to the `read ` function , So i would really like if i had a option something `pueue exec $processno` so that it can execute the ongoing process after i gave some inputs to the process like `pueue send $processno`

**Comment by Nukesor** [comment]
Did you try sending a newline? Enter just sends a newline

**Comment by Nukesor** [comment]
`pueue send 0 "\n"`

**Comment by mbhutton** [comment]
> `pueue send 0 "\n"`

This works, where `\n` above is the user typing an actual newline rather than the characters `\` and `n`. 

E.g. in my shell it looks like 
```
pueue send 0 "
"
```

**Comment by Nukesor** [comment]
Closing as solved :)
