### ISSUE TITLE
Windows service supports only 1 currently daemon per user

### ISSUE THREAD

**Issue by MolotovCherry** [Nukesor/pueue#574]
### Describe the bug

Strictly speaking it is possible on Windows to have a user running in the background and log into another user. In such an instance what would currently happen is that the daemon would only run for the first logged in user, but do nothing for the new user (even if they have a config).

It is not clear to me yet how (if) this should be handled. Also, what should happen if the new user that logs in doesn't even use or want pueued to run? Since this is a system service, it impacts all users on the system

It is possible to refactor it to track multiple session logons and run multiple pueued processes as different users.
_Edit: This also would require installing the service with pueued in a place globally accessible by all users_

The current method was done because from a single administrator user POV, it is obvious they want pueued to run every time, otherwise they wouldn't have installed the service. Most people use their systems as a single user anyways. But from a multi user point of view, what should be done is less clear.

This issue is filed for discussion purposes, and also as a preventative measure in case someone decides to file an issue down the line about this.

**Comment by Nukesor** [comment]
In Linux environments, it's pretty trivial to setup services for individual users, especially due to the usage of Unix sockets.

I generally don't see an issue with supporting this, but it's also something that might not even be needed by anybody :D It's a pretty special usecase.

**Comment by Nukesor** [comment]
Let's close this for now until somebody actually needs it and comes up with a proper usecase :)
