### ISSUE TITLE
Set global allowed parallel tasks and distribute them amongst groups

### ISSUE THREAD

**Issue by jbd** [Nukesor/pueue#575]
### A detailed description of the feature you would like to see added.

I'd like to be able to set a global allowed parallel tasks and distribute them amongst the defined groups.

For exemple, I define 16 global parallel tasks, and 4 groups: default, g0, g1, g2. It would first assign 4 parallel tasks to each group. If one group has less than 4 tasks pending, the remaining free tasks would be assign to other groups in a round robin fashion. 

### Explain your usecase of the requested feature

I'm using pueue to manage data transfer. This data transfer is happening between the same source and multiple destination. I known that the source can handle X parallel copy at the same time. Each destination has its own pueue group. If one or more destination is not used at some point or use less than its configure number of parallel tasks, some other group with pending tasks could use the free slots.

**Comment by Nukesor** [comment]
Hey :)

Saldy, this is one of those features that would [blow up the scope of pueue](https://github.com/Nukesor/pueue?tab=readme-ov-file#design-goals) as this falls in `Sophisticated task scheduling for optimal load balancing.`. You're theoretically still able to do this by calling pueue's api and distributing the tasks by yourself, but at this point it's probably easier to write your own scheduler :)

**Comment by Nukesor** [comment]
https://github.com/Nukesor/pueue?tab=readme-ov-file#gnu-parallel 
Gnu parallel might be the right tool for your use case.
