### ISSUE TITLE
(Web) GUI of it?

### ISSUE THREAD

**Issue by fzyzcjy** [Nukesor/pueue#577]
### A detailed description of the feature you would like to see added.

Hi, thanks for the great library! It would be great if it could have a (web) GUI, then it is even easier to have a look at what is going on.

### Explain your usecase of the requested feature

(see above)

**Comment by Nukesor** [comment]
See https://github.com/Nukesor/pueue/issues/49

Feel free to create a gui or ncurses interface.
Such a project won't be built by me anytime soon and should thereby be not be developed in this project :).

However, if you manage to built a good and well tested client that establishes itself, we could talk about upstreaming it and giving you co-maintainership :)

Regarding  web interface, something like that won't ever be upstreamed, as it simply doesn't fit into the scope of this project (which is designed to be a minimalistic **commandline scheduler**). Also I don't want to come into contact with the JS/Web ecosystem in my spare time if it can be avoided :D.

**Comment by fzyzcjy** [comment]
I see, thank you!
