### ISSUE TITLE
Run an extra command whenever the queue is empty

### ISSUE THREAD

**Issue by fzyzcjy** [Nukesor/pueue#578]
### A detailed description of the feature you would like to see added.

Hi thanks for the tool! My (summarized) use case is like this: Submit a few deep learning jobs to my workstation, and when all are done (i.e. GPU is finally idle), send me a Slack message such that I can come and use the idle GPU. For example, I will need the idle GPU to tentatively run some new commands, debug them, and when they look good, submit it to the queue.

Thus, it would be great to have a feature that, when the job is empty, run an extra command to notify users.

EDIT: Looks like I can use the "Callback" feature to handle it. Seems need to query `pueue` to know whether the queue is empty now, thus it would be great if this information could be provided as a variable.

EDIT: Looks like it can be done by e.g. https://github.com/Nukesor/pueue/blob/9a402d5f895fdf489e7b8006375946080ea5950c/pueue/src/daemon/callbacks.rs#L62 add a line here, giving `state.tasks.len()`.

### Explain your usecase of the requested feature

(see above)

**Comment by fzyzcjy** [comment]
(The content in the root post is edited for more details)

**Comment by Nukesor** [comment]
I see how that can be useful.

How about, we add a simple boolean to the template variables. Something like `group_finished`?
I'm against just using `state.tasks.len()` as users will probably be interested in which group just finished. This will give one more control on what should happen on different groups.

The `group` is already part of the variables that're available.

**Comment by Nukesor** [comment]
You could then do stuff like

```sh
if [[ "true" = "{{ group_finished }}" ]]; then
  if [[ "default" = "{{ group }}" ]]; then
    # Do your stuff
  fi
fi
```

**Comment by fzyzcjy** [comment]
> we add a simple boolean to the template variables. Something like group_finished

Looks pretty reasonable!

**Comment by Nukesor** [comment]
One more question.

When should a queue be considered finished?
I feel at least when there're no more `queued` entries. But what about stashed entries with a delay?

**Comment by fzyzcjy** [comment]
Hmm, then maybe provide fine-grained details, such as `{{ num_queued }}`, `{{ num_stashed }}`, etc?
