### ISSUE TITLE
Allow listening on unix domain sockets and systemd socket activation

### ISSUE THREAD

**Issue by XenonPK** [Nukesor/pueue#58]
Hello,
Any reason not to use unix domain sockets?
It would also be nice to have systemd socket activation to control the daemon lifecycle.
Basically having the background daemon automatically start by simply running the client. It would then stop after a set timeout if no jobs are pending.

The only challenge I see would be in how you would prevent systemd from terminating the service after the timeout has expired.

Look into this: https://gist.github.com/kylemanna/d193aaa6b33a89f649524ad27ce47c4b
For a small self-contained example.

Anyway, the goal would be to have the background daemon active only when strictly required, without affecting user experience.

**Comment by Nukesor** [comment]
The systemd socket activation feature sounds pretty awesome. I'll take a look at it!

The reason for not using unix sockets is, that I want this project to be cross-platform and I'm planning to support remote connections.
Using two different socket types seemed unnecessary, if one type of socket has to be supported in any case.

**Comment by Nukesor** [comment]
The main problem I see with systemd socket units is, that the current service file is designed to run as a user service. Each user has to use a different port. If there is a way to specify the port when enabling a socket unit, this could indeed work.

Feel free to create a PR with such a unit file :)

**Comment by forbesmyester** [comment]
Having a TCP socket seems like a bit of scary potential security thing to me. The README at least does not make it clear how to make sure it's only listening on the loopback. If it were only a unix socket I'd just use without worrying.

**Comment by Nukesor** [comment]
It's on loopback by default and cannot be changed right now.
Thereby there is no security information, since loopback devices are widely regarded as safe (of course root can potentially read sockets, but if root attacks, you already lost anyway).

As soon as you are able to change the IP you're listening on, there will be a very detailed guide on how to make it safe. Loopback will however stay the default.

**Comment by Nukesor** [comment]
@forbesmyester

If you are serious about unix socket support, please create a pull request :)
As long as this feature is completely optional, I'll happily include this into the project.

**Comment by Nukesor** [comment]
Unix Socket support will be added in #90

**Comment by tmccombs** [comment]
> The main problem I see with systemd socket units is, that the current service file is designed to run as a user service. Each user has to use a different port.

If it uses a unix socket, then the socket could use `ListenStream=%t/pueue_%u.socket` to use a user-specific file.
