### ISSUE TITLE
[Question] Does pueue work with process substitution?

### ISSUE THREAD

**Issue by whatbh** [Nukesor/pueue#585]
My job deals with programmatically editing a template and scheduling the edited files. I can achieve this by combining `sed` and process substitution, for example:
```bash
bash <(sed -e "s/\$placeholder/word/g" template.sh)
# basically replace the variable $placeholder in the file template.sh with the word "word" and execute the created pipe.
```
In the past, I have successfully get this done in Slurm/Torque and `tsp`, something like:
```bash
for i in {0..99}; do
       #slurm
       qsub < <(sed -e "s/\$placeholder/$i/g" template.sh)
       #tsp
       tsp bash <(sed -e "s/\$placeholder/$i/g" template.sh)
done
```
Basically I need to massively and programmatically edit and schedule numerous files. However, I cannot achieve this in `pueue`. When I schedule a command containing process substitution in `pueue`, it always return an error, something like `/dev/fd/63 not found` (I don't remember exactly the error and currently not on production machine, but it's essentially like that).

Of course, I can actually create the file, and this is what I am currently doing. Something like:
```bash
for i in {0..99}; do
       tempFile=$(mktemp -u)
       sed -e "s/\$placeholder/$i/g" template.sh > tempFile
       pueue add bash tempFile
done
```
But I wonder is there any way to deal with process substitution in `pueue`? I just use `pueue` recently so I don't know much about its internal.

**Comment by Nukesor** [comment]
Sadly that's not how pueue's internals work.

Pueue saves the binary/script that should be executed as the internal command. That command can then later be edited to fix mistakes like typos.

With process substitution, a temporary file is created (at `/dev/fd/$id`), which is then available for the current process runtime. So it's removed as soon as `pueue add` has finished.
pueue than tries to call that script file lateron even though it has already been removed.

I assume slurm simply copies the whole script into its internal queue when it detects a process substitution? Not sure how that works though.

As a simple workaround, just pass the output of your template into pueue as a whole string. This will result in a huge command, but it should work without problems and mimicks how I assume slurm works.

The other way around that is to
1. Parameterize your script, which is probably cleaner than to template it via sed.
2. Do it like you do already via a temporary file

**Comment by whatbh** [comment]
Ah, I see how it works. Thank you for your explanations and suggestions. I'm closing the issue now.
