### ISSUE TITLE
Build error using cargo.

### ISSUE THREAD

**Issue by Abhinav1217** [Nukesor/pueue#60]
Hi, 
I am trying to install this using cargo. I made sure rust and cargo are updated. I am running solus os, 
I am getting following build error.
```
   Compiling walkdir v2.3.1
   Compiling lock_api v0.3.3
error: `core::slice::<impl [T]>::len` is not yet stable as a const fn
   --> /home/abhinav/.cargo/registry/src/github.com-1ecc6299db9ec823/bytes-0.5.4/src/bytes.rs:130:18
    |
130 |             len: bytes.len(),
    |                  ^^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `bytes`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `pueue v0.1.4`, intermediate artifacts can be found at `/tmp/cargo-installJwWzHH`

Caused by:
  build failed
```
Any suggestion on how do I move forward.

**Comment by Nukesor** [comment]
Pueue only builds with Rust >v1.39. You have to update your rust version `rustup update`.
Both nightly and stable channels should work.

**Comment by Nukesor** [comment]
I'll add a hard check for v1.39 to build.rs in the next version

**Comment by Abhinav1217** [comment]
Yikes, It was there in Readme. How did I miss that. I switched from rustc from package manager to using rustup which updated it to 1.41, earlier it was 1.38. Thanks.
