### ISSUE TITLE
stdout log filling whole home directory

### ISSUE THREAD

**Issue by muralikodali** [Nukesor/pueue#61]
i am using ubuntu mate 18.04.03 . when i passed a command 'yes sudo apt upgrade' ,  stdout.log started to increase in size filling the my home directory with 64GB log file consuming 95% of my 8GB RAM and high cpu. when i tested stdout.log with 'tail -n 100', it is showing the input command 'sudo apt ugrade'. i have to forcefully stop the computer and restart it again and remove the log file.

**Comment by Nukesor** [comment]
Ok :D. This is most likely a problem with unproper piping.
Could you verify that `yes` didn't run in the background? I suspect that yes didn't pipe into `sudo apt upgrade`, but rather to `stdout`?
As far as i know you have to do `yes | sudo apt update`.

`yes` is a utility that prints `y` as fast as it can to `stdout`. You most likely spammed your log file with 64GB of `y`

**Comment by Nukesor** [comment]
Update: If you print `yes "sudo apt upgrade"` it spams `sudo apt upgrade` rather than `y` :D.
So you probably spammed your log with `sudo apt upgrade`

**Comment by Nukesor** [comment]
Btw. `apt upgrade` allows a `-y` flag for this exact purpose.

**Comment by muralikodali** [comment]
thanks for your suggestion .

running **sudo apt upgrade -y or yes  | sudo apt upgrade** completed the task **successfully** with : 
Std_err:
 
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
 
debconf: unable to initialize frontend: Dialog
debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin: 

it looks piping in task is a  problem.when i tried to run task '**ls ~/Downloads | xsel** ' , log output is : 

Task 15 with exit code 1
Command: ls ~/Downloads | xsel
Path: /home/murali/Downloads
Start: Sun, 02 Feb 2020 11:08:20 +0530
End: Sun, 02 Feb 2020 11:08:20 +0530
Std_err: 
xsel: Can't open display: (null)
: Inappropriate ioctl for device

can you please give suggestions _for piping in tasks and running two commands sequentially in a single task._

**Comment by Nukesor** [comment]
Well, all things that require some kinde of display/window manager won't work, since the tasks are executed in the background.
As your error messages stated, they cannot open any displays or frontends. (The second command probably requires a X-session)

Don't use Pueue for commands that won't work on a non-visual environment.

The pipe works quite fine when starting commands:
```
pueue add -- 'echo "this is a test
for grep" | grep grep'
```

```
Task 0 with exit code 0
Command: echo "this is a test
for grep" | grep grep
Path: /home/nuke/repos/pueue
Start: Sun, 02 Feb 2020 16:31:34 +0100
End: Sun, 02 Feb 2020 16:31:34 +0100
Std_out:
for grep
```

**Comment by Nukesor** [comment]
I added a extensive FAQ section on how to use Pueue :)
Closing for now
