### ISSUE TITLE
Pause Single Running Process instead of all Process

### ISSUE THREAD

**Issue by gotbletu** [Nukesor/pueue#65]
**Is your feature request related to a problem? Please describe.**

- Good to have feature, not the end of the world tho

**Describe the solution you'd like**

- Pause A Single Running Process instead of all Process/Parallel Process/Queue.

**Describe alternatives you've considered**

- Dont think this exist on any other similar programs e.g nq, task-spooler

**Additional context**

- Lets say i already started a conversion process of a video file, then suddenly i need the pc to do other things that requires resources. I can't really pause it because then i wont be able to use this program for other queue task. Would be nice to choose which process you want to pause and still use the program for other queue, then at the end of the day resume the conversion process without having to restart the whole video conversion all over again.

**Comment by Nukesor** [comment]
You can specify specific task ids for pretty much every command in pueue.

```
⌁ [nuke:~] % pueue pause -h
pueue-pause 0.1.4
Pause the daemon and all running tasks. A paused daemon won't start any new tasks. Daemon and tasks can be continued
with `start`

USAGE:
    pueue pause [FLAGS] [task-ids]...

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information
    -w, --wait       Pause the daemon, but let any running tasks finish by themselves

ARGS:
    <task-ids>...    Enforce starting these tasks. Doesn't affect the daemon or any other tasks
```

**Comment by Nukesor** [comment]
The help text is wrong though. Copy paste from `start` command.

**Comment by gotbletu** [comment]
oh i see, didn't know there was a sub help page for each command thanks =)

is it possible to make this pause option work with shellscripts that creates child processes?

e.g
I have a bash script with ffmpeg commands inside to convert videos.
The pause option doesn't pause the ffmpeg child process. So it will say pause on the script but the ffmpeg commands will still run in the background.

**Comment by Nukesor** [comment]
Just did some research. It's possible, but we need to do some work. I'm creating a new issue.

**Comment by Nukesor** [comment]
https://github.com/Nukesor/pueue/issues/68

**Comment by Nukesor** [comment]
@gotbletu The feature just got added in v0.5.1 :)

**Comment by gotbletu** [comment]
Thanks, i just gave it a try, works great, this gonna save me tons of time, now i gotta tell everyone about this program =)

**Comment by gotbletu** [comment]
can you add a way to kill the child process also?
e.g `$ pueue kill -c 0`

currently this does not work for killing my ffmpeg bash script
`$ pueue kill 0`

**Comment by Nukesor** [comment]
True, that shouldn't be a problem :)

I'll probably do this today or tomorrow.
A new version will be dropped, when I'm done with another planned feature. (A file for specifying your own aliases, since reading `.*rc` files for headless shells is a pain in the ass)

**Comment by Nukesor** [comment]
I didn't add a `-c` flag, but rather always send a `SIGTERM` to all child processes.

This should be the default. I cannot think of any scenario, where a user wants detached child processes to continue running when killing a Task.

**Comment by Nukesor** [comment]
Processes should determine on their own, how to handle a `SIGSTOP`.
For instance, a process that spawns and manages sub-processes itself.
This process should decide themselves, whether it should pause their processes or wait for them to pause gracefully. 
For instance, forcing those sub-processes to `SIGSTOP` could lead to unexpected states or simply errors when working with IO/network stuff.

`SIGSTOP` should only be sent to the actual parent process. Everything else could lead to weird problems.

**Comment by Nukesor** [comment]
Hm.. While reading my own message, I noticed, that it's probably not the best idea to send a SIGTERM to child processes by default either.

This could lead to non-graceful shutdowns and errors as well....

**Comment by Nukesor** [comment]
Ok. I added the `-c` flag to `reset` and `kill` as well.

**Comment by gotbletu** [comment]
alright thanks, ill give it a try in the next release
