### ISSUE TITLE
[BUG] pueued fails when ~/.config directory does not exist

### ISSUE THREAD

**Issue by bddap** [Nukesor/pueue#67]
Both `pueued` and `pueued --help` exit nonzero when no `~/.config` directory is present.

**To Reproduce**

1. Move `~/.config` elsewhere.
2. run `pueued --help` or `pueued` or `pueue -V`

**Expected behavior**

Help Text

**Actual Behavior**

```
~$ pueued --help
Error: Failed saving the config file

Caused by:
    No such file or directory (os error 2)
```

**Additional context**

- Ubuntu 18
- Pueue version 0.1.3

**Possible fixes**

a) create a `~/.config` directory if it does not already exist
b) return descriptive error message suggesting the user `mkdir ~/.config`

**Related suggestion**

In both the [client](https://github.com/Nukesor/pueue/blob/38e2720/client/main.rs) and the [daemon](https://github.com/Nukesor/pueue/blob/38e2720/daemon/main.rs), move `let opt = Opt::from_args();` to before config parsing. This would ensure `pueued --help` doesn't attempt to perform any file IO.

**Comment by Nukesor** [comment]
Thanks for reporting!

This should be an easy fix. It'll be added to the next release :)
