### ISSUE TITLE
What is powershell?

### ISSUE THREAD

**Issue by forbesmyester** [Nukesor/pueue#69]
The README.md says:

Pueue uses `powershell` to execute commands, keep this in mind when writing commands.

However the code does not seem to reference powershell and the install instructions don't say anything about powershell. I thought maybe it was a dependency and not Microsoft's PowerShell but it's not listed in the cargo file.

Unsure on what it means...

**Comment by Nukesor** [comment]
Well, pueue executes your commands on a shell in the background (otherwise stuff like `|` or `&&` wouldn't work).
Microsoft seem to be usally shipped with `cmd` and `powershell`.
Pueue uses `powershell` to execute your commands.
