### ISSUE TITLE
Funky "Used by" displayed by GitHub

### ISSUE THREAD

**Issue by forbesmyester** [Nukesor/pueue#70]
**Describe the bug**

Wierd UI in GitHub

**To Reproduce**

Go to the top of GitHub, where Watch, Unstar, Fork etc are at the top of the page (in desktop)

You will see a "Used by" pulldown

Click it

It says: "Install via requirements.txt" and "pip install pueue"

**Expected behavior**

I'd just expectthat not to exist.

**Screenshots**

User could not find out how to upload a screenshot!

**Comment by Nukesor** [comment]
Jep. Pueue has been rewritten from python to rust. I couldn't figure out yet how to remove this :D
But tbh, it wasn't my top priority either.

**Comment by Nukesor** [comment]
I just moved the legacy python branch into it's own project and adjusted the repo url for the legacy project.
Hopefully this fixes the issue. Otherwise we would have to contact the Github staff.

Closing for now

**Comment by Nukesor** [comment]
I contacted Github's Support and they say that this cannot be removed for now.
