### ISSUE TITLE
Arm and aarch64 binaries

### ISSUE THREAD

**Issue by T4P4N** [Nukesor/pueue#71]
Please add binaries for arm and aarch64 architectures

**Comment by Nukesor** [comment]
TBH, I'm not very familiar with arm and aarch64 architectures. I'm not even sure, if Github actions is capable of building them easily.

If you want these binaries, please update the workflow file and create a pull request :)

**Comment by T4P4N** [comment]
i tried to find usable github actions workflow file, and i found one which can cross compile rust, but i encountered some errors, sorry to say but i giveup. Here is link to example workflow i file i used to cross compile pueue https://github.com/actions-rs/example/blob/master/.github/workflows/cross_compile.yml

**Comment by Nukesor** [comment]
Damn. Anyway, thanks for trying!
I'll leave this issue open for reference :)

**Comment by Nukesor** [comment]
Done. Binaries will be available with the next release

**Comment by T4P4N** [comment]
Thank you very much! 👍🏽
