### ISSUE TITLE
Stop on error

### ISSUE THREAD

**Issue by juliuswz** [Nukesor/pueue#76]
it would be interesting to have an option to pause execution if a task fails.

**Comment by Nukesor** [comment]
I agree, this could be a useful feature.

We will probably need a nice cli interface for configuration stuff. This won't be the last flag.
Do you know some good and intuitive cli tools that can be configured during runtime?

**Comment by Nukesor** [comment]
The flag is implemented, but can only be changed via editing the config file and restarting the daemon for now.

The name of the option is `pause_on_failure` and default `false` for now.
You can start the client once. This should add the default flag to the config file.

https://github.com/Nukesor/pueue/commit/ed3de4c8c600f703cc1820282a7de276f763fd28

**Comment by Nukesor** [comment]
Closing for now

**Comment by juliuswz** [comment]
So sorry for the late reply. It was exactly what I had in mind, thanks for the quick implementation.
