### ISSUE TITLE
[BUG] Error: Connection refused (os error 61)

### ISSUE THREAD

**Issue by ebauger** [Nukesor/pueue#77]
OS : macOS Catalina 10.15.4
Pueue client 0.2.1

I tried this:

```
> pueue add ls
Error: Connection refused (os error 61)
```

**Comment by ebauger** [comment]
I figured out by reading the readme on the repo. 😅

Maybe a better message error with pueued -d command into suggestion

**Comment by Nukesor** [comment]
True, this one should have a proper error message :D

**Comment by Nukesor** [comment]
Done
