### ISSUE TITLE
Make environment of `pueue add` take precedence over `pueued`

### ISSUE THREAD

**Issue by EntilZha** [Nukesor/pueue#78]
**Is your feature request related to a problem? Please describe.**
I've been giving `pueue` a try while also looking at [task spooler](https://manpages.ubuntu.com/manpages/xenial/man1/tsp.1.html) and noticed that commands run with `pueue add` run under the environment in which `pueued` is created.

In particular, I work a lot with python virtual environments so it would be great to be able to do something like:
```bash
$ pueued -d
$ conda activate myenv
$ pueue add which python
```
where the output would show the python related to the anaconda/conda/virtualenv python and not the system python. Currently that would print the python related to where `pueued` was run.

It would be great for this to be configurable so that the environment of the `add` command can be used.

There are some workarounds, like wrapping my command in a script that sources the environment, but then that adds another thing to do. Task spooler handles this I think incidentally since it does not have a daemon so the default environment is the one used in spawning a task like `ts which python`

I'd love for any workarounds to this or a feature added to handle this.

**Comment by Nukesor** [comment]
Phew. I guess this would require catching all environment variables of the client and passing them through to the daemon, which then injects them into the shell process.

I'll probably not build it any time soon, since there are some other features I want to build first.
However, I'll happily review any PR regarding this issue. Would you be interested in adding this functionality?

**Comment by EntilZha** [comment]
Although I'd be interested in adding it, I'm pretty time crunched on other projects so doubt I'd have time to implement it any time soon either. Perhaps someone else could take it up or I'll have some free time later though.

**Comment by Nukesor** [comment]
Just looked at it. This should actually be fairly easy:

Catch with:
https://doc.rust-lang.org/std/env/fn.vars.html

Set with:
https://doc.rust-lang.org/std/process/struct.Command.html#method.envs

**Comment by Nukesor** [comment]
Implemented in https://github.com/Nukesor/pueue/commit/9118318c8547c37c7b6c4791ff38d11f49d1fa29
