### ISSUE TITLE
[BUG] Task does not have start time

### ISSUE THREAD

**Issue by mars90226** [Nukesor/pueue#80]
**Describe the bug**

On pueue 1.6, task has start time. On pueue 2.0 and above, task has no start time.

**To Reproduce**
1. `pueue add -- ls`
2. `pueue status`

No start time

**Expected behavior**

Task has start time

**Screenshots**
Only needed if the problem is of graphic
![pueue_no_start_time](https://user-images.githubusercontent.com/1523214/78869847-cac7a580-7a77-11ea-928c-9e507e3abc0f.png)

**Additional context**
- Operating System: Ubuntu 18.04
- Pueue version. Can be seen at the top of `pueue -h` output: 0.3.0

I use `git bisect` to find out the latest good commit is `3b55623e376d81a0d26d309d3d9377deae616aaf`. And I try to solve this problem by adding `task.start = Some(Local::now());` at the end of `TaskHandler::start_process()`. But I'm not sure if it's the correct way to fix it.

**Comment by Nukesor** [comment]
Thanks for reporting!
I somehow completely missed that.
Previously this has been set in a handler (dirty) and I forgot to adjust the usage, when I stopped using that convenience handler.
