### ISSUE TITLE
[BUG] excessive memory and CPU usage with large outputs

### ISSUE THREAD

**Issue by sourcefrog** [Nukesor/pueue#82]
I'm using pueue to queue up some large file copies -- and it's pretty nice!

However I notice after a while, it's taking several seconds of pueued CPU time to `pueue add date` a new task. I would have expected it's just adding it to some kind of in-memory or on-disk queue, and the time should be proportional to the fairly short command line.

I also see `pueued` seems to be using a lot of memory for what it's doing:

```
  PID TTY      STAT   TIME  MAJFL   TRS   DRS   RSS %MEM COMMAND 
16885 pts/11   SNl+   2:54     71  1930 1043077 779556 13.3 pueued
```

I don't know how to reproduce it, but maybe it's connected to some of these commands producing a lot of output? Ideally it would just stay on files on disk and not be in memory.

This is pueue 0.3.1 from Cargo, on Debian Buster.

**Comment by sourcefrog** [comment]
Yep, it looks like (in https://github.com/Nukesor/pueue/blob/f85e5b4b6e3e15c911c7087fd2386aee2190f246/shared/task.rs#L24-L36) the `Task` struct includes a String of all the stdout/stderr from the task, and also the struct is `Clone`. 

I think that means when inserting entries into the `state.tasks` BTreeMap (https://github.com/Nukesor/pueue/blob/f85e5b4b6e3e15c911c7087fd2386aee2190f246/shared/state.rs#L17-L23) it'll end up not only holding the output in memory, but possibly copying it many times. 

I guess I've learned I should redirect bulk output to a file, not let pueue hold it. If that's just the intention perhaps it should be in the instructions. 

However perhaps it's not uncommon to want to run something that does produce a lot of output within a queue manager. So could I suggest perhaps 

 - keep output on disk not in memory?
 - or, at least, store them in `Cow<String>` rather than copying every time the `Task` is copied?

**Comment by Nukesor** [comment]
Yep. That's a problem that already occurred in another form.

One person did pipe the output of `yes` to stdout instead into the program and completely filled their harddrive/ram with `y` in the log output :D.

To be honest, I don't think that this is a problem that should be handled by pueue. Maybe we can add some in-memory compression. In general, I think it's way too convenient to have your logs ready to use. If we want to add another step and write to/read from disk, we might have a considerable delay when issuing commands.

Plus, in my opinion, piping gigabytes of data to stdout can be considered as an edgecase.

As long as you're not piping binary output to stdout, in-memory compression should already solve a lot of problems.

If you're interested in adding this, feel free to create a PR :+1:

**Comment by sourcefrog** [comment]
Yes, I'm not sure if manually spilling them to disk is worthwhile or not. After all, running `yes` will eventually fill your disk.

I think there's no downside to using `Cow` to avoid mindlessly copying strings if they are in memory, though? Or adding a warning to the documentation?

It is a case where it's distinctly different to tmux, from which both of us switched. tmux retains only a bounded amount of history (normally?) so running something that produces lots of output is harmless. Maybe eventually there should be a history limit in pueue.

**Comment by sourcefrog** [comment]
In testing #84 I find it's pretty easy to get pueued into a state where it's overwhelmed by the volume of logs. But, this PR does seem to make it rather better. In particular it makes it fast to remove items from the queue when there's some large output, which could previously be very slow.

Killing `pueued` doesn't really resolve the problem because it will try to load them again when it starts up, which is not a great user experience - presumably I'd have to delete or do some surgery on its state directory. So, I think it would still be a good idea to keep log output primarily on disk. If it's small, reading it on demand won't create any noticeable delay.

**Comment by Nukesor** [comment]
If we decide to keep log output only on disk, we won't have to change too much.
Log output is written onto disk anyway. It's only loaded into memory after completion for convenience purposes.

**Comment by sourcefrog** [comment]
Yeah, that was what I was just noticing. If this is OK in principle with you, I might send a later PR. This one is an incremental improvement, though.

**Comment by Nukesor** [comment]
Sorry for leaving this lying around for so long.
I wanted to resolve the other PR and the implied internal refactoring before continuing with this.

I'm planning to free some time next week (30.04-01.05) to look at this and probably refactor the current log/stdout/stderr handling.

Thanks for your input and for sticking around :)

**Comment by sourcefrog** [comment]
sounds good, thanks

**Comment by Nukesor** [comment]
Ok,

There is one more thing that needs to be discussed.
Pueue does log/state rotation of queues every time a queue get's reset or a `clean` is issued.

I've been thinking about whether this ration/backup feature is actually useful or if this could be rather removed. Especially, since this becomes a lot less convenient, if the logs no longer live in the actual state.

To be honest, I'm not even sure if anyone ever used that feature. Just thought it would be nice to be able to look into old logs in case you accidentally did a `clean` and noticed that there was some important stuff you forgot to copy afterwards.

**Comment by sourcefrog** [comment]
You could move them to the OS trash, so they eventually get deleted:
https://docs.rs/trash/1.0.0/trash/

**Comment by Nukesor** [comment]
Hm.

I'm not sure if this is a good solution, since the Trash folder is mostly unused on servers and basically never get's emptied. It's rather opaque as well.

Many bare-bones linux setups don't use trash folders as well. I don't think that this solution is feasible

**Comment by Nukesor** [comment]
First optimization is implemented in #88 

Tests with 1GB output log files

Master:
![image_2020-04-30_02-51-07](https://user-images.githubusercontent.com/3322822/80717160-d0edf680-8af8-11ea-9d25-35d34132ecfa.png)

Log output stored outside of memory:
![image_2020-04-30_02-45-54](https://user-images.githubusercontent.com/3322822/80717356-22968100-8af9-11ea-9840-85e7666662d1.png)

Memory is reduced by a peak factor of 1/3 . Normal operation barely has any memory footprint.

**Comment by sourcefrog** [comment]
Great. How did you get the nice heap profile and graphs?

It seems like later, you could stream the task logs and never need the whole thing in memory? Although, that might be hard with the json proto encoding.

**Comment by Nukesor** [comment]
I'm already working on an in-memory compression with brotli.

I agree that streaming them directly would remove any memory problems immediately, but also remove the possibility to easily use pueue's output format in other programs (i.e. a status bar tool)

**Comment by Nukesor** [comment]
The heap profile has been taken with valgrind and the `--tool=massif` option.
Visualization via `massive-visualizer`

**Comment by Nukesor** [comment]
Ok. I added compression with snap and changed the serialization from json to bincode to support binary data.

We're down to this:
![image_2020-04-30_22-33-46](https://user-images.githubusercontent.com/3322822/80758584-23013d00-8b36-11ea-9e63-30a522127dbf.png)

The remaining duplicated storage overhead comes from the message that's being serialized.
I'm not exactly sure how this could be handled without sending it directly without any kind of serialization.

That needs a more complicated protocol though.

**Comment by sourcefrog** [comment]
How about just send the filename to the client and have the client read it directly?

I guess there might be exceptions but isn't the by-far most common case going to be that the client is on the same machine, running as the same user, and able to read the files directly? For "weird" cases like a shared secret between different accounts or running pueue over ssh, you could fall back to copying the contents.

**Comment by Nukesor** [comment]
Yep.
That would be a possible solution as well, but I really want to have a proper communication as well.
It's planned for 1.0 to allow remote secure connections directly via tcp.

Another thing that would be awesome to have is unix socket support.

There are just way too many features that have to be built.

**Comment by Nukesor** [comment]
Ok. This took a little more refactoring than expected.
Anyhow, we now have a client that can read logs from disk :))

![image](https://user-images.githubusercontent.com/3322822/80836091-57d3c980-8bf4-11ea-9b1c-8629ae9c5dd7.png)
