### ISSUE TITLE
Task complete callback command

### ISSUE THREAD

**Issue by james2doyle** [Nukesor/pueue#89]
**Is your feature request related to a problem? Please describe.**
I want to be able to run a callback command whenever a command has finished (regardless of exitcode)

**Describe the solution you'd like**
Just a flag for the callback command or the ability to set a default one in the config

**Describe alternatives you've considered**
You could probably inline this, but you would have to do it to every command every time

**Additional context**
Example: `pueue add sleep 10 --callback 'osascript -e "display notification \"Sleep finished\" with title \"Task complete\""'`

If `pueue` set some ENV vars, you could do this in the settings file:

```diff
---
client:
  daemon_port: "6924"
  secret: "your_secret"
  read_local_logs: true

daemon:
  pueue_directory: /home/$USER/.local/share/pueue
  default_parallel_tasks: 1
  pause_on_failure: false
  port: "6924"
  secret: "your_secret"
+ callback: osascript -e "display notification \"Finished $COMMAND\"\
+ with title \"Task $STATUS\""
```

**Comment by Nukesor** [comment]
I like this.

I would rather implement this using a simple templating engine for assembling the command than using environment variables. This should allow easier execution of those commands as well. 
Handlebar could be used for stuff like this before (already used it for a similar purpose before)

It would probably be best to make call this command directly via [Command](https://doc.rust-lang.org/std/process/struct.Command.html). I.e. there will be no bash/shell semantics.
Complex commands have to be wrapped in a script.

**Comment by james2doyle** [comment]
Ah ok. Glad you agree!

So you're thinking something like this instead: `callback: osascript -e "display notification \"Finished {{ command }}\" with title \"Task {{ status }}\"` then?

**Comment by Nukesor** [comment]
Precicely :)

**Comment by Nukesor** [comment]
Implemented in https://github.com/Nukesor/pueue/commit/c45e00c4e145d2d5fbde2646a26e45e58ebd94cc

**Comment by james2doyle** [comment]
Awesome! Super handy!

**Comment by Nukesor** [comment]
I used a shell subprocess to interpret the callback after all -.-`
It's probably more convenient for users, since they can use shell syntax in their callbacks.
However, it's also a lot easier code-wise, since I don't have to split the callback string into executable and arguments.

Using rust's bare-bones subprocesses with arbitrary user input is a little tricky :smile:

**Comment by james2doyle** [comment]
Yeah absolutely. I think it's easier but also more intuitive that it works
that way
