### ISSUE TITLE
Defaults for Follow

### ISSUE THREAD

**Issue by JP-Ellis** [Nukesor/pueue#95]
It would be good if the `follow` subcommand was a little smarter if no tasks are specified.  In particular:

- If there are no tasks running, `pueue follow` should simply say that there are no tasks running.
- If there is only one task running, `pueue follow` should follow that running task
- If there are multiple tasks running, `pueue follow` could either:
  - List which tasks are running and warn the user a task ID has to be specified; or,
  - Follow the last task

In the last case, I prefer the first option as it doesn't assume anything unreasonable.

In all case, `pueue follow <task-id>` should remain unchanged.

If you would like this added, I'm happy to work on a PR request.

**Comment by Nukesor** [comment]
I like it! This should definitely improve the ergonomics of the sub command.

Feel free to start hacking, I would love to see this added to the project :+1:

**Comment by Nukesor** [comment]
Hey @JP-Ellis,

I just wanted to ask, when you're planning to build this feature :)
I'm thinking about creating a new release, but I would like to wait for your feature, so it can be included in 0.6.0.

If you need some time, I'll push a patch release for the new features :)

Anyhow, no pressure, just take your time :)

**Comment by JP-Ellis** [comment]
I was hoping to have a go at this this weekend.
